export const ListeArmesImpériales = [
    {
        Id: 1,
        Nom: "Couteau",
        Description: "Du hachoir d'un boucher à grox au stylet d'un assassin, de nombreuses petites armes blanches peuvent être qualifiées de « Couteaux ». Cela inclut toutes les lames qui peuvent être fixées à une arme comme une baïonnette.",
        Type: "Armes de mêlée",
        PénétrationArmure: "-",
        Dégâts: "(F) + 2",
        DésDégâtsSupplémentaires: "2",
        Portée: "Lancer (F) x 4",
        Rafale: "-",
        Traits: "-",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "LAME, [AU CHOIX]"
    },
    {
        Id: 2,
        Nom: "Couteau de combat Astartes",
        Description: "Cette grande lame exceptionnellement tranchante fait partie de l'équipement standard de nombreux Space Marines. Aussi long que les épées courtes des humains ordinaires, ce couteau possède un tranchant monomoléculaire qui ne s'émousse jamais.",
        Type: "Armes de mêlée",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 3",
        DésDégâtsSupplémentaires: "2",
        Portée: "-",
        Rafale: "-",
        Traits: "Fiable",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "LAME, ADEPTUS ASTARTES"
    },
    {
        Id: 3,
        Nom: "Épée",
        Description: "Aussi anciennes et variées que l'Imperium de l'humanité lui-même, des épées de toutes formes et tailles peuvent être trouvées dans tout l'univers déchiré par la guerre.",
        Type: "Armes de mêlée",
        PénétrationArmure: "-",
        Dégâts: "(F) + 3",
        DésDégâtsSupplémentaires: "3",
        Portée: "-",
        Rafale: "-",
        Traits: "Parade",
        Valeur: "3",
        Rareté: "Courant",
        MotsClés: "LAME, [AU CHOIX]"
    },
    {
        Id: 4,
        Nom: "Couteau monomoléculaire",
        Description: "Ces lames robustes sont forgées à partir de matériaux de haute qualité et affûtées jusqu'à obtenir un tranchant monomoléculaire capable de traverser facilement de fines couches de métal.",
        Type: "Armes de mêlée",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 3",
        DésDégâtsSupplémentaires: "2",
        Portée: "-",
        Rafale: "-",
        Traits: "Perforant (1)",
        Valeur: "5",
        Rareté: "Peu courant",
        MotsClés: "LAME, IMPERIUM, RACAILLE"
    },
    {
        Id: 5,
        Nom: "Matraque improvisée",
        Description: "Ces armes sont des outils normalement pensés pour l'industrie lourde, par exemple l'exploitation minière, la fonte ou la construction. Conçus pour arracher, plier, couper, serrer ou tailler à travers le plastacier, ces instruments simplistes s'avèrent très efficaces lorsqu'ils sont utilisés sur la chair et les os.",
        Type: "Armes de mêlée",
        PénétrationArmure: "-",
        Dégâts: "(F) + 4",
        DésDégâtsSupplémentaires: "2",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal, Encombrant (1)",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 6,
        Nom: "Miséricorde de la Psykana",
        Description: "Les Psykers assermentés sont équipés d'une lame tranchante à utiliser en dernier recours si leurs pouvoirs échappent à leur contrôle. Si un malheureux devait faire face à la tragédie d'une possession démoniaque imminente, la lame lui offre une échappatoire salutaire. Les « Chasseurs de sorcières » improvisés qui opèrent dans tout le système de Gilead considèrent ces lames comme de prestigieux trophées et n'hésitent pas à exhiber leurs plus belles prises en privé. Une Miséricorde de la Psykana a le même profil qu'un Couteau, mais avec une PA à -1 et le Mot-clé ADEPTUS ASTRA TELEPATHICA.",
        Type: "Armes de mêlée",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 2",
        DésDégâtsSupplémentaires: "2",
        Portée: "Lancer (F) x 4",
        Rafale: "-",
        Traits: "-",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "LAME, ADEPTUS ASTRA TELEPATHICA"
    },
    {
        Id: 7,
        Nom: "Baïonnette tronçonneuse",
        Description: "Au prix de l'augmentation spectaculaire du poids d'un fusil, une Baïonnette tronçonneuse peut offrir une fin rapide et sanglante à tous les ennemis qui se rapprochent de son porteur.",
        Type: "Armes tronçonneuses",
        PénétrationArmure: "-",
        Dégâts: "(F) + 4",
        DésDégâtsSupplémentaires: "3",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal",
        Valeur: "3",
        Rareté: "Rare",
        MotsClés: "TRONÇONNEUSE, IMPERIUM, CHAOS"
    },
    {
        Id: 8,
        Nom: "Épée tronçonneuse",
        Description: "Malgré leur apparence brutale et leur rugissement rauque distinct, les épées tronçonneuses (parfois appelées « Lames tronçonneuses ») nécessitent de l'entraînement pour être maniées efficacement. Un duel entre deux porteurs d'Épée tronçonneuse entraînés est un spectacle qui vaut le détour : ces combattants sont capables de modifier la vitesse et la direction des chaînes dentelées pour contrer, parer et vaincre leur adversaire avec une grâce sauvage.",
        Type: "Armes tronçonneuses",
        PénétrationArmure: "-",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal, Parade",
        Valeur: "4",
        Rareté: "Peu courant",
        MotsClés: "TRONÇONNEUSE, AELDARI, IMPERIUM, CHAOS"
    },
    {
        Id: 9,
        Nom: "Eviscerator",
        Description: "Emporté au combat par des fanatiques et des repentis, un Eviscerator est une grande Épée tronçonneuse sur laquelle on a installé un champ de force primitif. Une seule frappe peut couper à travers des hordes de mécréants et de damnés et faire pleuvoir le sang dans un vacarme de chaînes dentelées.",
        Type: "Armes tronçonneuses",
        PénétrationArmure: "-4",
        Dégâts: "(F) + 6",
        DésDégâtsSupplémentaires: "6",
        Portée: "2",
        Rafale: "-",
        Traits: "Brutal, Encombrant (2)",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "TRONÇONNEUSE, À 2 MAINS, ADEPTUS ASTARTES, ADEPTUS MINISTORUM, ADEPTA SORORITAS, CHAMP DE FORCE"
    },
    {
        Id: 10,
        Nom: "Hache tronçonneuse",
        Description: "Combinant l'action tranchante d'une Épée tronçonneuse avec la force d'une hache, les Haches tronçonneuses peuvent être trouvées entre les mains des guerriers les plus brutaux, qui les utilisent volontiers pour arracher de grands lambeaux de chair et de déchirants cris de douleur à leurs victimes.",
        Type: "Armes tronçonneuses",
        PénétrationArmure: "-",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal, Perforant (1)",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "TRONÇONNEUSE, CHAOS"
    },
    {
        Id: 11,
        Nom: "Poing tronçonneur",
        Description: "Conçus pour être utilisés dans les opérations d'abordage de vaisseaux spatiaux, ces Gantelets énergétiques améliorés arborent une lame tronçonneuse additionnelle qui s'avère tout aussi capable de transpercer les fortifications et les véhicules renforcés que les cloisons des vaisseaux.",
        Type: "Armes tronçonneuses",
        PénétrationArmure: "-4",
        Dégâts: "(F) + 7",
        DésDégâtsSupplémentaires: "6",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal, Encombrant (3)",
        Valeur: "10",
        Rareté: "Très rare",
        MotsClés: "TRONÇONNEUSE, CHAMP DE FORCE, IMPERIUM, CHAOS, ADEPTUS ASTARTES"
    },
    {
        Id: 12,
        Nom: "Électrofouet",
        Description: "Grâce à une longe en matériau conducteur alimentée par une cellule énergétique dans la poignée, l'Électrofouet craquette et bourdonne d'un courant électrique capable de paralyser ses victimes.",
        Type: "Armes de mêlée exotiques",
        PénétrationArmure: "-",
        Dégâts: "(F) + 4",
        DésDégâtsSupplémentaires: "2",
        Portée: "4",
        Rafale: "-",
        Traits: "Douloureux, Perforant (2)",
        Valeur: "4",
        Rareté: "Très rare",
        MotsClés: "EXOTIQUE, [AU CHOIX]"
    },
    {
        Id: 13,
        Nom: "Fouet",
        Description: "Fabriqué à partir de toutes sortes de peaux, de cordes ou d'autres matériaux exotiques, le Fouet primitif peut être trouvé à travers l'univers entre les mains des dresseurs d'animaux et des esclavagistes.",
        Type: "Armes de mêlée exotiques",
        PénétrationArmure: "-",
        Dégâts: "(F) + 1",
        DésDégâtsSupplémentaires: "1",
        Portée: "4",
        Rafale: "-",
        Traits: "Douloureux",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "PRIMITIVE, [AU CHOIX]"
    },
    {
        Id: 14,
        Nom: "Fouet neural",
        Description: "Fabriqués à partir de matériaux psychoconducteurs, ces longs fouets crépitants envoient de terribles signaux neuronaux à travers la chair et jusqu'au centre de douleur du cerveau.",
        Type: "Armes de mêlée exotiques",
        PénétrationArmure: "-2",
        Dégâts: "(F) + 3",
        DésDégâtsSupplémentaires: "2",
        Portée: "4",
        Rafale: "-",
        Traits: "Douloureux",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "EXOTIQUE, ADEPTA SORORITAS"
    },
    {
        Id: 15,
        Nom: "Matraque à décharge",
        Description: "Les juges et bourreaux de l'Adeptus Arbites utilisent ces lourdes matraques électrifiées pour assommer les suspects et disperser les rassemblements illégaux.",
        Type: "Armes de mêlée exotiques",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 4",
        DésDégâtsSupplémentaires: "4",
        Portée: "1",
        Rafale: "-",
        Traits: "Brutal, Douloureux",
        Valeur: "5",
        Rareté: "Peu courant",
        MotsClés: "EXOTIQUE, ADEPTUS ARBITES"
    },
    {
        Id: 16,
        Nom: "Bâton de force",
        Description: "Les Bâtons de force sont dotés d'une psy-matrice complexe qui leur permet d'agir comme une batterie psychique, afin de stocker de l'énergie psychique qui pourra être déchaînée avec une efficacité redoutable.",
        Type: "Armes de force",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 4",
        DésDégâtsSupplémentaires: "2",
        Portée: "2",
        Rafale: "-",
        Traits: "Brutal, Force",
        Valeur: "2",
        Rareté: "Rare",
        MotsClés: "FORCE, AELDARI, À 2 MAINS, INQUISITION, ADEPTUS ASTARTES, ADEPTUS ASTRA TELEPATHICA"
    },
    {
        Id: 17,
        Nom: "Épée de force",
        Description: "Combinez l'élégance d'une lame bien forgée avec les circuits psychosensibles et la puissance immatérielle de toute arme de force et vous obtenez une Épée de force : un objet dont le potentiel est véritablement spectaculaire entre les mains d'un Psyker entraîné.",
        Type: "Armes de force",
        PénétrationArmure: "-3",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Force, Parade",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "FORCE, AELDARI, INQUISITION, ADEPTUS ASTARTES"
    },
    {
        Id: 18,
        Nom: "Hache de force",
        Description: "Ces lames de hache en alliage incorporent un motif serpentin connu sous le nom de matrice psi qui dirige l'énergie psychique concentrée, afin d'amplifier la puissance des coups de son porteur.",
        Type: "Armes de force",
        PénétrationArmure: "-2",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Force",
        Valeur: "6",
        Rareté: "Très rare",
        MotsClés: "FORCE, INQUISITION, ADEPTUS ASTARTES"
    },
    {
        Id: 19,
        Nom: "Marteau tueur de démons Némésis",
        Description: "Maniées principalement par les Inquisiteurs de l'Ordo Malleus doués de pouvoirs psychiques, ces armes lentes, mais puissantes usent d'énergies physiques et psychiques pour infliger d'importants dégâts.",
        Type: "Armes de force",
        PénétrationArmure: "-3",
        Dégâts: "(F) + 8",
        DésDégâtsSupplémentaires: "6",
        Portée: "2",
        Rafale: "-",
        Traits: "Brutal, Encombrant (2), Force",
        Valeur: "10",
        Rareté: "Unique",
        MotsClés: "FORCE, À 2 MAINS, INQUISITION, ADEPTUS ASTARTES"
    },
    {
        Id: 20,
        Nom: "Épée énergétique",
        Description: "Ces armes rares sont réservées aux héros de renom et aux officiers les plus prestigieux. L'énergie qui jaillit le long du fil d'une Épée énergétique est à la fois un avertissement et un défi pour tous ceux qui se dressent face à son porteur.",
        Type: "Armes énergétiques",
        PénétrationArmure: "-3",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Parade",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "CHAMP DE FORCE, IMPERIUM, AELDARI"
    },
    {
        Id: 21,
        Nom: "Gantelet énergétique",
        Description: "Le générateur de champ de force à l'intérieur de ce lourd gantelet mécanisé enveloppe celui-ci d'énergie. Son porteur est alors capable de déchirer des plaques de céramite et d'adamantium comme s'il s'agissait de papier.",
        Type: "Armes énergétiques",
        PénétrationArmure: "-3",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal, Encombrant (2)",
        Valeur: "8",
        Rareté: "Très rare",
        MotsClés: "CHAMP DE FORCE, IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 22,
        Nom: "Hache de l'Omnimessie / Hache énergétique",
        Description: "Symbole du pouvoir du Dieu-Machine, la Hache de l'Omnimessie est ornée d'icônes Mechanicus et d'engrenages ornementaux. / Une Hache énergétique coupe avec la force d'un éclair. Cette arme est capable de fendre une armure et de démembrer sa victime comme un bûcheron le ferait avec des bûches.",
        Type: "Armes énergétiques",
        PénétrationArmure: "-2",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "5",
        Portée: "2",
        Rafale: "-",
        Traits: "-",
        Valeur: "6",
        Rareté: "Très rare",
        MotsClés: "CHAMP DE FORCE, À 2 MAINS, ADEPTUS MECHANICUS"
    },
    {
        Id: 23,
        Nom: "Hache énergétique",
        Description: "Une Hache énergétique coupe avec la force d'un éclair. Cette arme est capable de fendre une armure et de démembrer sa victime comme un bûcheron le ferait avec des bûches.",
        Type: "Armes énergétiques",
        PénétrationArmure: "-2",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Perforant (1)",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "CHAMP DE FORCE, IMPERIUM, ADEPTUS ASTARTES, ADEPTUS MECHANICUS, AELDARI"
    },
    {
        Id: 24,
        Nom: "Lame énergétique du Culte de la Mort",
        Description: "Portées par des assassins du Culte de la Mort, ces fines lames n'ont peut-être pas la portée ni le poids d'autres armes énergétiques, mais les champs énergétiques qu'elles projettent sont tout aussi capables de fendre la matière.",
        Type: "Armes énergétiques",
        PénétrationArmure: "-2",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Parade",
        Valeur: "6",
        Rareté: "Très rare",
        MotsClés: "CHAMP DE FORCE, IMPERIUM, ADEPTUS MINISTORUM"
    },
    {
        Id: 25,
        Nom: "Marteau tonnerre",
        Description: "Le Marteau tonnerre est l'arme suprême de combat rapproché de l'Adeptus Astartes. Un seul coup de cette arme suffit à briser une armure en mille morceaux et à liquéfier la chair qu'elle tentait vainement de protéger.",
        Type: "Armes énergétiques",
        PénétrationArmure: "-3",
        Dégâts: "(F) + 8",
        DésDégâtsSupplémentaires: "6",
        Portée: "2",
        Rafale: "-",
        Traits: "Brutal, Encombrant (2)",
        Valeur: "9",
        Rareté: "Unique",
        MotsClés: "CHAMP DE FORCE, À 2 MAINS, IMPERIUM, ADEPTUS ASTARTES, INQUISITION"
    },
    {
        Id: 26,
        Nom: "Bolter",
        Description: "Difficiles à manier par de simples mortels, les Bolters sont pensés pour les Astartes. Ces fusils polyvalents sont comme le prolongement du corps d'un Space Marine.",
        Type: "Arme à Bolt",
        PénétrationArmure: "-1",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "1",
        Portée: "12 / 24 / 36",
        Rafale: "2",
        Traits: "Brutal, Tir rapide (2)",
        Valeur: "5",
        Rareté: "Peu courant",
        MotsClés: "BOLT, IMPERIUM"
    },
    {
        Id: 27,
        Nom: "Bolter d'assaut",
        Description: "Doté d'un bouclier magnétique et d'un système de chargement automatique pour optimiser encore davantage son potentiel destructeur, le Bolter d'assaut est un instrument de mort implacable que l'on retrouve entre les mains de l'élite des Astartes Primaris.",
        Type: "Arme à Bolt",
        PénétrationArmure: "0",
        Dégâts: "12",
        DésDégâtsSupplémentaires: "2",
        Portée: "9 / 18 / 27",
        Rafale: "3",
        Traits: "Assaut, Brutal, Tir rapide (3)",
        Valeur: "8",
        Rareté: "Héroïque",
        MotsClés: "BOLT, IMPERIUM, ADEPTUS ASTARTES, PRIMARIS"
    },
    {
        Id: 28,
        Nom: "Bolter lourd",
        Description: "Ces armes surdimensionnées sont aussi terrifiantes que ce que leur nom suggère. Avec un tir soutenu, ces énormes canons peuvent réduire l'infanterie lourdement blindée et les véhicules légers à des morceaux méconnaissables de ruines fumantes.",
        Type: "Arme à Bolt",
        PénétrationArmure: "-1",
        Dégâts: "12",
        DésDégâtsSupplémentaires: "2",
        Portée: "18 / 36 / 54",
        Rafale: "3",
        Traits: "Brutal, Lourd (4), Tir rapide (3)",
        Valeur: "10",
        Rareté: "Peu courant",
        MotsClés: "BOLT, IMPERIUM"
    },
    {
        Id: 29,
        Nom: "Bolter Storm",
        Description: "Un Bolter à double canon, avec toutes les réserves de munitions et le poids prodigieux que cela implique. Les Bolters Storm envoient de véritables torrents de bolts capables de réduire leur cible en charpie en l'espace de quelques instants.",
        Type: "Arme à Bolt",
        PénétrationArmure: "0",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "1",
        Portée: "12 / 24 / 36",
        Rafale: "4",
        Traits: "Brutal, Lourd (3), Tir rapide (3)",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "BOLT, IMPERIUM"
    },
    {
        Id: 30,
        Nom: "Fusil bolter",
        Description: "Fabriqué par l'Archimagos Dominus Belisarius Cawl, le Fusil bolter Mk II est l'évolution naturelle de l'arme la plus emblématique des Astartes. Ces Bolters surdimensionnés tirent des bolts de gros calibre avec une portée et une capacité de pénétration de blindage améliorées.",
        Type: "Arme à Bolt",
        PénétrationArmure: "-1",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "2",
        Portée: "15 / 30 / 45",
        Rafale: "2",
        Traits: "Brutal, Tir rapide (2)",
        Valeur: "7",
        Rareté: "Très rare",
        MotsClés: "BOLT, IMPERIUM, ADEPTUS ASTARTES, PRIMARIS"
    },
    {
        Id: 31,
        Nom: "Pistolet bolter",
        Description: "Toute la puissance et la fureur d'une arme à bolt, mais dans un format compact. Les spécialistes du combat rapproché affrontant des ennemis dangereux et les officiers désireux de marquer les esprits privilégient ces armes aussi redoutables que maniables.",
        Type: "Arme à Bolt",
        PénétrationArmure: "0",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "1",
        Portée: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Brutal, Pistolet",
        Valeur: "4",
        Rareté: "Peu courant",
        MotsClés: "BOLT, IMPERIUM"
    },
    {
        Id: 32,
        Nom: "Pistolet bolter lourd",
        Description: "Ces énormes armes de poing ont été forgées pour s'adapter aux paumes prodigieuses des Astartes Primaris. Aucun autre pistolet ne leur arrive à la cheville, que ce soit en termes de taille ou de potentiel destructeur.",
        Type: "Arme à Bolt",
        PénétrationArmure: "-1",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "1",
        Portée: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Brutal, Pistolet",
        Valeur: "5",
        Rareté: "Très rare",
        MotsClés: "BOLT, IMPERIUM, ADEPTUS ASTARTES, PRIMARIS"
    },
    {
        Id: 33,
        Nom: "Canon laser",
        Description: "Les Canons laser sont des armes encombrantes et destructrices alimentées par des cellules énergétiques surdimensionnées. Ils sont produits en série par l'Imperium pour faire face aux innombrables terreurs blindées qui sévissent dans la galaxie.",
        Type: "Armes Laser",
        PénétrationArmure: "-3",
        Dégâts: "16",
        DésDégâtsSupplémentaires: "3",
        Portée: "24 / 48 / 72",
        Rafale: "1",
        Traits: "Fiable, Lourd (8)",
        Valeur: "9",
        Rareté: "Peu courant",
        MotsClés: "LASER, IMPERIUM"
    },
    {
        Id: 34,
        Nom: "Fusil de sniper laser",
        Description: "Conçu pour une portée plus grande, méticuleusement réglé pour plus de précision et alimenté par des chargeurs pleine-bourre à tir unique, le Fusil de sniper laser est l'arme préférée du tireur d'élite impérial.",
        Type: "Armes Laser",
        PénétrationArmure: "-",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "1",
        Portée: "18 / 36 / 54",
        Rafale: "0",
        Traits: "Fiable, Précis (1)",
        Valeur: "6",
        Rareté: "Peu courant",
        MotsClés: "LASER, IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 35,
        Nom: "Fusil laser",
        Description: "Les Fusils laser sont les armes les plus fabriquées et les plus modifiées de l'Humanité. Alors que le modèle standard de masse du Fusil laser peut être trouvé dans tout l'Imperium, il existe d'innombrables variantes.",
        Type: "Armes Laser",
        PénétrationArmure: "-",
        Dégâts: "7",
        DésDégâtsSupplémentaires: "1",
        Portée: "12 / 24 / 36",
        Rafale: "2",
        Traits: "Fiable, Tir rapide (1)",
        Valeur: "3",
        Rareté: "Courant",
        MotsClés: "LASER, IMPERIUM"
    },
    {
        Id: 36,
        Nom: "Fusil radiant à salve",
        Description: "Composé de deux fusils pleine-bourre jumelés à un système de tir alterné, le Fusil radiant à salve est une arme lourde et redoutable conçue pour libérer un véritable torrent de mort.",
        Type: "Armes Laser",
        PénétrationArmure: "-2",
        Dégâts: "11",
        DésDégâtsSupplémentaires: "1",
        Portée: "12 / 24 / 36",
        Rafale: "4",
        Traits: "Fiable, Lourd (4)",
        Valeur: "8",
        Rareté: "Rare",
        MotsClés: "LASER, IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 37,
        Nom: "Fusil radiant laser",
        Description: "Le Fusil radiant laser, ou « Fusil pleine-bourre », est un Fusil laser classique auquel on a enlevé plusieurs mécanismes de sécurité afin de projeter un faisceau de lumière plus puissant à travers un canon renforcé.",
        Type: "Armes Laser",
        PénétrationArmure: "-2",
        Dégâts: "9",
        DésDégâtsSupplémentaires: "1",
        Portée: "9 / 18 / 27",
        Rafale: "2",
        Traits: "Fiable, Tir rapide (2)",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "LASER, IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 38,
        Nom: "Pistolet laser",
        Description: "Petit, facile à produire et fiable, le toujours très utile Pistolet laser est l'arme de poing standard de l'Astra Militarum. Bien qu'il n'ait pas la puissance d'arrêt des armes de poing plus lourdes, sa robustesse garantit qu'il fonctionnera dans presque toutes les conditions.",
        Type: "Armes Laser",
        PénétrationArmure: "-",
        Dégâts: "7",
        DésDégâtsSupplémentaires: "1",
        Portée: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Fiable, Pistolet",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "LASER, IMPERIUM"
    },
    {
        Id: 39,
        Nom: "Pistolet laser de maître",
        Description: "Ornés de graves baroques, de matériaux rares et de noms poétiques, ces Pistolets laser améliorés sont conçus pour être à la fois puissants et agréables à l'œil. Spécialement commandées par des nobles soucieux de leur statut ou par des porte-flingues auxquels la chance a souri, ces armes sont utilisées pour mettre un terme aux différends personnels d'une manière rapide, civilisée et définitive.",
        Type: "Armes laser",
        PénétrationArmure: "-",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "1",
        Portée: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Fiable, Pistolet",
        Valeur: "6",
        Rareté: "Très rare",
        MotsClés: "LASER, IMPERIUM"
    },
    {
        Id: 40,
        Nom: "Pistolet radiant laser",
        Description: "Également appelées « Pistolets pleine-bourre », ces armes laser améliorées offrent une puissance de feu supérieure, mais au prix d'une portée plus faible et d'un encombrement plus important. Les Pistolets pleine-bourre se distinguent également par leur cellule énergétique déportée, qu'il est possible d'accrocher à une bandoulière ou à la ceinture. L'arme en elle-même est compacte et peut être tirée à une main, ce qui en fait un équipement de choix pour les officiers et les guerriers qui aiment voir de près la peur dans les yeux de l'ennemi.",
        Type: "Armes laser",
        PénétrationArmure: "-2",
        Dégâts: "7",
        DésDégâtsSupplémentaires: "1",
        Portée: "3 / 6 / 9",
        Rafale: "1",
        Traits: "Fiable, Pistolet",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "LASER, IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 41,
        Nom: "Grenade à plasma",
        Description: "Un potentiel terrifiant dans un format compact. Une grenade à plasma n’est guère plus qu’un collecteur de plasma miniaturisé conçu pour surchauffer brutalement sur commande. Ce globe de destruction instable est assez puissant pour que quiconque y réfléchisse à deux fois avant même de le garder sur soi.",
        Type: "Grenades et Missiles",
        Degats: "10",
        DS: "5",
        PA: "-1",
        Portee: "(F) x 4 m ou portée du lance-grenades",
        Rafale: "-",
        Traits: "Explosion (6)",
        Valeur: "5",
        Rarete: "Très rare",
        MotsClés: "EXPLOSIF, AELDARI"
    },
    {
        Id: 42,
        Nom: "Grenade Frag",
        Description: "Compactes, faciles à fabriquer et si simples que même un habitant d’un monde sauvage arriéré pourrait s’en servir : les grenades à fragmentation sont l’explosif antipersonnel de choix dans tout l’Imperium.",
        Type: "Grenades et Missiles",
        Degats: "10",
        DS: "4",
        PA: "-",
        Portee: "(F) x 4 m ou portée du lance-grenades",
        Rafale: "-",
        Traits: "Explosion (6)",
        Valeur: "2",
        Rarete: "Courant",
        MotsClés: "EXPLOSIF, IMPERIUM"
    },
    {
        Id: 43,
        Nom: "Grenade Krak",
        Description: "Comparable aux grenades Frag, mais remplie d’agents explosifs enfermés dans un boîtier à charge creuse. Conçues pour ouvrir des fortifications et des véhicules, les grenades Krak sont souvent fixées à leurs cibles et déclenchées via une minuterie ou une télécommande, mais il est déjà arrivé que des soldats désespérés les utilisent de manière plus traditionnelle.",
        Type: "Grenades et Missiles",
        Degats: "14",
        DS: "5",
        PA: "-2",
        Portee: "(F) x 4 m ou portée du lance-grenades",
        Rafale: "-",
        Traits: "Explosion (4)",
        Valeur: "4",
        Rarete: "Peu courant",
        MotsClés: "EXPLOSIF, IMPERIUM"
    },
    {
        Id: 44,
        Nom: "Lance-grenades Militarum Tempestus",
        Description: "Ce lance-grenades alimenté par un chargeur tambour peut lancer des explosifs à une distance et à une vitesse suffisantes pour transformer la moindre recrue en un véritable instrument de mort. Le recul est assez puissant pour meurtrir son porteur, le bruit des déflagrations risque fortement d'endommager l'ouïe de façon irréversible et les autres soldats se tiennent bien à l'écart de quiconque transporte des munitions aussi dangereuses, mais tout le monde convient qu'utiliser une arme aussi dévastatrice est une expérience particulièrement grisante.",
        Type: "Grenades et Missiles",
        Degats: "Utilise le profil de la grenade tirée",
        DS: "Utilise le profil de la grenade tirée",
        PA: "Utilise le profil de la grenade tirée",
        Portee: "14 / 28 / 42",
        Rafale: "-",
        Traits: "Assaut",
        Valeur: "6",
        Rarete: "Peu courant",
        MotsClés: "EXPLOSIF, IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 45,
        Nom: "Lance-missiles",
        Description: "De conception simple, les Lance-missiles ne sont souvent guère plus que des tubes en plastacier dotés de mécanismes de déclenchement infaillibles, conçus pour envoyer leurs charges utiles automotrices vers leurs malheureuses cibles.",
        Type: "Grenades et Missiles",
        Degats: "Utilise le profil du missile tiré",
        DS: "Utilise le profil du missile tiré",
        PA: "Utilise le profil du missile tiré",
        Portee: "24 / 48 / 72",
        Rafale: "-",
        Traits: "Lourd (6)",
        Valeur: "4",
        Rarete: "Courant",
        MotsClés: "EXPLOSIF, IMPERIUM"
    },
    {
        Id: 46,
        Nom: "Lance-missiles Cyclone",
        Description: "Équipé de doubles râteliers de munitions à chargement rapide, ce lance-missiles a été conçu pour les Astartes en armure tactique Dreadnought, connus sous le nom de Terminators, afin de lancer un barrage incessant d'explosions sur les ennemis de l'Imperium. Cette arme se charge avec 2 Munitions de missiles du même type, qui sont tirées toutes les deux en une seule attaque. Faites le Test de Capacité de Tir (A) comme d'habitude contre une cible à portée. Lors du calcul des dégâts, traitez cela comme une attaque unique avec le double de la valeur des Dégâts et de DS d'un seul missile.",
        Type: "Grenades et Missiles",
        Degats: "Utilise le profil du missile tiré",
        DS: "Utilise le profil du missile tiré",
        PA: "Utilise le profil du missile tiré",
        Portee: "18 / 36 / 54",
        Rafale: "-",
        Traits: "Lourd (8)",
        Valeur: "11",
        Rarete: "Très rare",
        MotsClés: "EXPLOSIF, IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 47,
        Nom: "Missile Frag",
        Description: "Le noyau de ce missile renferme un paquet d'explosifs antipersonnels concentrés qui se déclenchent à l'impact, afin de projeter du shrapnel sur une vaste zone.",
        Type: "Grenades et Missiles",
        Degats: "12",
        DS: "5",
        PA: "-",
        Portee: "-",
        Rafale: "-",
        Traits: "Explosion (10)",
        Valeur: "4",
        Rarete: "Courant",
        MotsClés: "EXPLOSIF, IMPERIUM"
    },
    {
        Id: 48,
        Nom: "Missile Krak",
        Description: "Ces missiles surmontés de puissantes charges creuses perforent des cibles blindées avec une force implosive assez puissante pour perforer les tympans.",
        Type: "Grenades et Missiles",
        Degats: "16",
        DS: "6",
        PA: "-2",
        Portee: "-",
        Rafale: "-",
        Traits: "Explosion (4)",
        Valeur: "6",
        Rarete: "Courant",
        MotsClés: "EXPLOSIF, IMPERIUM"
    },
    {
        Id: 49,
        Nom: "Carabine à radium",
        Description: "Ces armes baroques tirent un torrent de projectiles solides hyper-irradiés qui génèrent de terribles tempêtes de radiations, afin de déchirer la structure génétique de la cible et du porteur.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Degats: "7",
        DS: "1",
        PA: "-",
        Portee: "9 / 18 / 27",
        Rafale: "3",
        Traits: "Assaut, Radiation (2)",
        Valeur: "6",
        Rarete: "Très rare",
        MotsClés: "PROJECTILE, ADEPTUS MECHANICUS"
    },
    {
        Id: 50,
        Nom: "Éclateur volkite",
        Description: "Reliques archaïques des époques passées, les armes volkites dirigent des faisceaux focalisés de chaleur infernale pour faire fondre les ennemis de l'intérieur.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Degats: "14",
        DS: "2",
        PA: "-",
        Portee: "12 / 24 / 48",
        Rafale: "2",
        Traits: "Explosion (2), Inflige En feu, Lourd (4), Tir rapide (2)",
        Valeur: "11",
        Rarete: "Unique",
        MotsClés: "ADEPTUS MECHANICUS, FLAMME"
    },
    {
        Id: 51,
        Nom: "Électrofusil",
        Description: "Alimentés par des condensateurs énergétiques construits à l'aube de l'Imperium, ces fusils tirent des éclairs crépitants irisés qui brûlent la chair, surchargent les impulsions neuronales et détruisent les machines en un coup.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Degats: "14",
        DS: "1",
        PA: "-1",
        Portee: "12 / 24 / 36",
        Rafale: "2",
        Traits: "Électro (2), Tir rapide (1)",
        Valeur: "6",
        Rarete: "Rare",
        MotsClés: "ÉLECTRO, ADEPTUS MECHANICUS"
    },
    {
        Id: 52,
        Nom: "Électropistolet",
        Description: "Cette arme électro miniaturisée prisée des Rangers Skitarii est capable de décharger de violentes explosions d'énergie concentrée à courte portée.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Degats: "14",
        DS: "1",
        PA: "-1",
        Portee: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Électro (2), Pistolet",
        Valeur: "5",
        Rarete: "Rare",
        MotsClés: "ÉLECTRO, ADEPTUS MECHANICUS"
    },
    {
        Id: 53,
        Nom: "Fusil galvanique",
        Description: "Rappelant les anciennes armes à silex, les Fusils galvaniques tirent des projectiles électromagnétiques intégrant des servitors de guidage. Chaque munition est dotée d'un esprit-machine sauvage et obsédé par l'idée d'infliger un maximum de dégâts à sa cible.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Degats: "10",
        DS: "1",
        PA: "-",
        Portee: "15 / 30 / 45",
        Rafale: "2",
        Traits: "Perforant (1), Tir rapide (1)",
        Valeur: "5",
        Rarete: "Rare",
        MotsClés: "PROJECTILE, ADEPTUS MECHANICUS"
    },
    {
        Id: 54,
        Nom: "Pistolet à radium",
        Description: "Aussi beau et dangereux que les autres armes à radium, les Pistolets à radium sont utilisés presque exclusivement par les Skitarii, pour qui le contact cancérigène du radium n'est qu'une autre des bénédictions de l'Omnimessie.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Degats: "7",
        DS: "1",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Pistolet, Radiation (2)",
        Valeur: "6",
        Rarete: "Rare",
        MotsClés: "PROJECTILE, ADEPTUS MECHANICUS"
    },
    {
        Id: 55,
        Nom: "Mitrailleuse",
        Description: "Cette grosse arme à projectiles alimentée par courroie peut être aussi bien utilisée pour lancer une formidable rafale de tirs de suppression que pour décimer l'infanterie.",
        Type: "Armes à projectiles (suite)",
        Degats: "10",
        DS: "2",
        PA: "-",
        Portee: "18 / 36 / 54",
        Rafale: "3",
        Traits: "Lourd (4)",
        Valeur: "5",
        Rarete: "Peu courant",
        MotsClés: "PROJECTILE, IMPERIUM, RACAILLE"
    },
    {
        Id: 56,
        Nom: "Pistolet-mitrailleur",
        Description: "La détonation distinctive d'un Pistolet-mitrailleur est un bruit trop courant dans les ruelles de la société impériale. Avec des cartouches de plus petit calibre que celles d'un Fusil d'assaut, une pression sur la gâchette peut vider un chargeur entier sur un ennemi imprudent.",
        Type: "Armes à projectiles (suite)",
        Degats: "7",
        DS: "1",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "2",
        Traits: "Pistolet",
        Valeur: "3",
        Rarete: "Courant",
        MotsClés: "PROJECTILE, IMPERIUM, RACAILLE"
    },
    {
        Id: 57,
        Nom: "Pistolet à aiguilles",
        Description: "Dotés de mécanismes élégants, rares et complexes, ces lanceurs de fléchettes faciles à dissimuler combinent de puissantes substances toxiques avec la technologie laser pour éliminer silencieusement et discrètement les ennemis.",
        Type: "Armes à projectiles (suite)",
        Degats: "8",
        DS: "2",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Douloureux, Inflige (Empoisonné 4), Pistolet, Silencieux",
        Valeur: "6",
        Rarete: "Très rare",
        MotsClés: "AIGUILLE, IMPERIUM"
    },
    {
        Id: 58,
        Nom: "Revolver",
        Description: "Ces revolvers à barillet surdimensionnés existent depuis le deuxième millénaire. Ils sont faciles à acquérir et adulés par les traditionalistes comme des armes de poing fiables et incapables de s'enrayer.",
        Type: "Armes à projectiles (suite)",
        Degats: "7",
        DS: "1",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Pistolet",
        Valeur: "2",
        Rarete: "Courant",
        MotsClés: "PROJECTILE, IMPERIUM, RACAILLE"
    },
    {
        Id: 59,
        Nom: "Lance-flammes",
        Description: "Cette arme exploite un mécanisme brutalement simple : du prométhium liquide et collant est propulsé dans le canon et à travers une veilleuse fixe. Ce jet de liquide enflammé adhère à toutes les surfaces qu'il touche et peut faire fondre la chair comme le plastacier.",
        Type: "Armes lance-flammes",
        Degats: "10",
        DS: "1",
        PA: "-",
        Portee: "4 / 8 / 12",
        Rafale: "1",
        Traits: "Assaut, Flamme",
        Valeur: "5",
        Rarete: "Peu courant",
        MotsClés: "FLAMME, IMPERIUM"
    },
    {
        Id: 60,
        Nom: "Lance-flammes lourd",
        Description: "Souvent dotés de plusieurs barils et de gros réservoirs pour les alimenter, les Lance-flammes lourds projettent de grands arcs de flammes liquides sur le champ de bataille. Ils se spécialisent dans l'inondation des tranchées et des bâtiments, qui sont rapidement engloutis sous un brasier dévorant.",
        Type: "Armes lance-flammes",
        Degats: "12",
        DS: "2",
        PA: "-1",
        Portee: "4 / 8 / 12",
        Rafale: "2",
        Traits: "Flamme, Lourd (6)",
        Valeur: "5",
        Rarete: "Peu courant",
        MotsClés: "FLAMME, IMPERIUM"
    },
    {
        Id: 61,
        Nom: "Pistolet lance-flammes",
        Description: "Fréquemment utilisé par les acolytes de l'Inquisition et les Rédemptionistes, cet enfer de poche ne demande qu'à être libéré. Son potentiel destructeur n'est limité que par la faible taille de ses réservoirs de carburant.",
        Type: "Armes lance-flammes",
        Degats: "7",
        DS: "1",
        PA: "-",
        Portee: "3 / 6 / 9",
        Rafale: "1",
        Traits: "Flamme, Pistolet",
        Valeur: "5",
        Rarete: "Peu courant",
        MotsClés: "FLAMME, IMPERIUM"
    },
    {
        Id: 62,
        Nom: "Autocanon",
        Description: "L'Autocanon est une arme lourde très utilisée, généralement à des fins anti-infanterie ou anti-aériennes. Ses cartouches lourdes, sa longue portée et sa cadence de tir élevée en font un équipement polyvalent dans les conflits à travers la galaxie.",
        Type: "Armes à projectiles",
        Degats: "16",
        DS: "1",
        PA: "1",
        Portee: "24 / 48 / 72",
        Rafale: "3",
        Traits: "Lourd (8)",
        Valeur: "8",
        Rarete: "Courant",
        MotsClés: "PROJECTILE, IMPERIUM"
    },
    {
        Id: 63,
        Nom: "Canon d'assaut",
        Description: "Un Canon d'assaut est une arme anti-infanterie dévastatrice. Dotée de plusieurs canons rotatifs, sa cadence de tir étonnante peut décimer les ennemis, mais une utilisation à outrance conduit souvent à des enrayages fréquents.",
        Type: "Armes à projectiles",
        Degats: "14",
        DS: "2",
        PA: "-1",
        Portee: "12 / 24 / 36",
        Rafale: "6",
        Traits: "Lourd (8)",
        Valeur: "6",
        Rarete: "Peu courant",
        MotsClés: "PROJECTILE, IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 64,
        Nom: "Canon de poing",
        Description: "Différents de pistolets lourds et de gros calibre existent dans tout l'Imperium. De nombreuses racailles appellent ces armes des « canons de poing », en raison de la déflagration assourdissante et des dégâts dévastateurs qu'ils provoquent.",
        Type: "Armes à projectiles",
        Degats: "9",
        DS: "1",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Pistolet",
        Valeur: "4",
        Rarete: "Courant",
        MotsClés: "PROJECTILE, IMPERIUM, RACAILLE"
    },
    {
        Id: 65,
        Nom: "Canon revolver",
        Description: "Évolution logique du déjà imposant Revolver, ces armes surdimensionnées tirent de grosses munitions largement répandues pour faire des trous tout aussi gros chez leurs victimes.",
        Type: "Armes à projectiles",
        Degats: "9",
        DS: "1",
        PA: "-",
        Portee: "9 / 18 / 27",
        Rafale: "1",
        Traits: "Brutal",
        Valeur: "5",
        Rarete: "Courant",
        MotsClés: "PROJECTILE, IMPERIUM, RACAILLE"
    },
    {
        Id: 66,
        Nom: "Fusil à aiguilles",
        Description: "Avec des canons allongés pour une plus grande portée, ces fusils rares délivrent les mêmes poisons mortels que les Pistolets à aiguilles.",
        Type: "Armes à projectiles",
        Degats: "8",
        DS: "2",
        PA: "-",
        Portee: "14 / 28 / 42",
        Rafale: "2",
        Traits: "Douloureux, Inflige (Empoisonné 4), Silencieux",
        Valeur: "6",
        Rarete: "Très rare",
        MotsClés: "AIGUILLE, IMPERIUM"
    },
    {
        Id: 67,
        Nom: "Fusil à pompe",
        Description: "Primitifs même par rapport aux autres armes à projectiles, les Fusils à pompe sont fiables et offrent une puissance d'arrêt importante à courte portée.",
        Type: "Armes à projectiles",
        Degats: "8",
        DS: "1",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Assaut, Dispersion",
        Valeur: "3",
        Rarete: "Courant",
        MotsClés: "PROJECTILE, IMPERIUM, RACAILLE"
    },
    {
        Id: 68,
        Nom: "Fusil à pompe Astartes",
        Description: "Ces fusils à pompe multi-action à chargeur font partie de l'équipement standard des Scouts Astartes. Ils tirent des cartouches de fusil de chasse surdimensionnées et sont capables d'arracher les charnières des portes et les membres des ennemis.",
        Type: "Armes à projectiles",
        Degats: "10",
        DS: "1",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "2",
        Traits: "Assaut, Dispersion, Fiable",
        Valeur: "6",
        Rarete: "Rare",
        MotsClés: "PROJECTILE, IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 69,
        Nom: "Fusil à pompe de combat",
        Description: "Populaires parmi les Forces de sécurité de main et le personnel de la Marine impériale, ces fusils à pompe automatiques et alimentés par un chargeur sont capables de soutenir d'interminables tirs de suppression pour mieux contrôler l'ennemi.",
        Type: "Armes à projectiles",
        Degats: "9",
        DS: "1",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "2",
        Traits: "Assaut, Dispersion, Tir rapide (1)",
        Valeur: "5",
        Rarete: "Peu courant",
        MotsClés: "PROJECTILE, IMPERIUM"
    },
    {
        Id: 70,
        Nom: "Fusil d'assaut",
        Description: "Faciles à fabriquer et à utiliser, les Fusils d'assaut sont prisés sur d'innombrables mondes impériaux. Leur robustesse et leurs munitions abondantes en font l'arme de choix pour les gangs des ruches et autres racailles qui se délectent du bruit et du carnage des rafales de plomb.",
        Type: "Armes à projectiles",
        Degats: "7",
        DS: "1",
        PA: "-",
        Portee: "12 / 24 / 36",
        Rafale: "3",
        Traits: "Tir rapide (1)",
        Valeur: "3",
        Rarete: "Courant",
        MotsClés: "PROJECTILE, IMPERIUM, RACAILLE"
    },
    {
        Id: 71,
        Nom: "Fusil de sniper Astartes",
        Description: "Les Fusils de sniper Astartes tirent de minuscules fléchettes de neurotoxine congelée le long d'un faisceau de guidage laser invisible. Ces armes presque complètement silencieuses permettent d'éliminer des cibles stratégiques avec discrétion et efficacité.",
        Type: "Armes à projectiles",
        Degats: "10",
        DS: "1",
        PA: "-",
        Portee: "18 / 36 / 54",
        Rafale: "0",
        Traits: "Précis (2), Silencieux",
        Valeur: "6",
        Rarete: "Peu courant",
        MotsClés: "PROJECTILE, IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 72,
        Nom: "Fuseur",
        Description: "Également connue sous le nom de « micro-ondes » ou de « Fusil à fusion », cette arme à fusion encombrante de la taille d'un fusil trouve son utilisation sur les lignes de front, afin d'ouvrir facilement les fortifications et les véhicules lourds. Le sifflement distinctif de l'air en ébullition et le tumulte consécutif du plastacier enflammé ont ponctué les derniers instants d'innombrables équipages de chars.",
        Type: "Armes à fusion",
        Degats: "16",
        DS: "2",
        PA: "-4",
        Portee: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Assaut, Fusion",
        Valeur: "6",
        Rarete: "Peu courant",
        MotsClés: "FUSION, IMPERIUM"
    },
    {
        Id: 73,
        Nom: "Multi-fuseur",
        Description: "Le Multi-fuseur est la plus grosse arme à fusion mobile d'infanterie en service. Ses doubles canons créent un faisceau de dévastation plus large et à plus longue portée qui réduit les cibles en flaques de scories fumantes.",
        Type: "Armes à fusion",
        Degats: "16",
        DS: "3",
        PA: "-4",
        Portee: "12 / 24 / 36",
        Rafale: "1",
        Traits: "Fusion, Lourd (8)",
        Valeur: "7",
        Rarete: "Rare",
        MotsClés: "FUSION, IMPERIUM"
    },
    {
        Id: 74,
        Nom: "Pistolet Inferno",
        Description: "Le modèle archéotechnologique du Pistolet Inferno est considéré comme perdu, et cette arme à fusion de poing est donc particulièrement prisée. La plupart des exemplaires sont des héritages au passé mouvementé, transmis de génération en génération.",
        Type: "Armes à fusion",
        Degats: "16",
        DS: "1",
        PA: "-4",
        Portee: "3 / 6 / 9",
        Rafale: "1",
        Traits: "Fusion, pistolet",
        Valeur: "6",
        Rarete: "Très rare",
        MotsClés: "FUSION, IMPERIUM, ADEPTUS ASTARTES, ADEPTA SORORITAS"
    },
    {
        Id: 75,
        Nom: "Fusil Kroot (mêlée)",
        Description: "Toutes les armes Kroot intègrent des lames, écho des bâtons de combat de leurs ancêtres. La plupart privilégient les lanceurs de limaces à canon long personnalisés avec des lames récupérées lors d'engagements mercenaires, leur permettant de charger leurs ennemis avec la fureur bestiale et les coups rapides à deux mains pour lesquels leur espèce est connue.",
        Type: "Armes de mêlée",
        PénétrationArmure: "-",
        Dégâts: "(F) + 4",
        DésDégâtsSupplémentaires: "3",
        Portée: "-",
        Rafale: "-",
        Traits: "2 mains",
        Valeur: "3",
        Rareté: "3",
        MotsClés: "LAME, KROOT, PRIMITIF"
    },
    {
        Id: 76,
        Nom: "Lame Bénie",
        Description: "Rarement, un saint impérial bénira une arme, lui insufflant un soupçon du pouvoir sacré de la foi inébranlable en l'Empereur-Dieu. Ces armes sont des reliques jalousement gardées de l'Ecclésiarchie, prisées pour leur capacité à abattre les ennemis démoniaques et accordées seulement à ses plus grands guerriers.",
        Type: "Armes de mêlée de l'Imperium",
        PénétrationArmure: "-3",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Bénie (3), Parade, Déchirant (1)",
        Valeur: "8",
        Rareté: "3",
        MotsClés: "LAME, IMPERIUM, ADEPTUS MINISTORUM, ADEPTA SORORITAS"
    },
    {
        Id: 77,
        Nom: "Crozius Arcanum",
        Description: "Pour un Chapelain Astartes, la méthode la plus pure d'adorer l'Empereur est de massacrer Ses ennemis dans une bataille glorieuse. De manière appropriée, le Crozius Arcanum porté par chaque Chapelain est à la fois un insigne de fonction et une arme mortelle : une masse avec une tête en forme de symbole sacré, crépitant de l'énergie d'un champ énergétique mortel.",
        Type: "Armes de mêlée de l'Imperium",
        PénétrationArmure: "-2",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal",
        Valeur: "6",
        Rareté: "3",
        MotsClés: "CHAMP ÉNERGÉTIQUE, IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 78,
        Nom: "Bâton de Dialogus",
        Description: "Ces bâtons solidement construits servent trois objectifs : la forme sculptée unique marque son porteur comme une Sœur Dialogus, le haut-parleur intégré diffuse sa rhétorique entraînante par-dessus le fracas de la bataille, et sa construction robuste en fait une arme de mêlée puissante lorsqu'elle est associée à la force ou à une armure assistée Sororitas.",
        Type: "Armes de mêlée de l'Imperium",
        PénétrationArmure: "-",
        Dégâts: "(F) + 3",
        DésDégâtsSupplémentaires: "3",
        Portée: "-",
        Rafale: "-",
        Traits: "Fiable",
        Valeur: "5",
        Rareté: "2",
        MotsClés: "ADEPTA SORORITAS"
    },
    {
        Id: 79,
        Nom: "Masse Énergétique",
        Description: "Simple masse améliorée par un champ énergétique, ces armes sont appréciées pour leur utilité. Comme le champ énergétique couvre une zone plus restreinte de l'arme, son intensité peut être ajustée, lui permettant de porter des coups capables d'impacter une armure assistée ou des tapes d'avertissement non létales sur un crâne humain.",
        Type: "Armes de mêlée de l'Imperium",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal",
        Valeur: "6",
        Rareté: "3",
        MotsClés: "CHAMP ÉNERGÉTIQUE, IMPERIUM, ADEPTUS ASTARTES, ADEPTUS MINISTORUM"
    },
    {
        Id: 80,
        Nom: "Aiguillon Taser",
        Description: "Un aiguillon taser est une arme longue, semblable à une épée, qui crépite avec la Force Motrice qu'il dérobe à l'air. Lorsqu'un aiguillon taser frappe sa cible, il libère l'électricité emprisonnée dans un paroxysme précis, transmettant la colère mortelle de l'Omnissie.",
        Type: "Armes de mêlée de l'Adeptus Mechanicus",
        PénétrationArmure: "-",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Agonisant",
        Valeur: "4",
        Rareté: "2",
        MotsClés: "ADEPTUS MECHANICUS"
    },
    {
        Id: 81,
        Nom: "Lame Transonique",
        Description: "Ces lames résonnantes bourdonnent d'un champ sonique hostile, retournant l'estomac de tous ceux qui l'entendent. Lorsqu'elle est ajustée à la bonne résonance, une lame transonique tranche l'air et l'armure avec la même rapidité dérangeante.",
        Type: "Armes de mêlée de l'Adeptus Mechanicus",
        PénétrationArmure: "-",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Parade, Déchirant (5)",
        Valeur: "6",
        Rareté: "3",
        MotsClés: "LAME, TRANSONIQUE, ADEPTUS MECHANICUS"
    },
    {
        Id: 82,
        Nom: "Masse de Bullgryn",
        Description: "Rien de plus qu'une énorme dalle de métal façonnée en un gourdin rudimentaire et dotée d'une poignée surdimensionnée adaptée aux Ogryns, une masse de Bullgryn est aussi émoussée qu'efficace. Presque aussi grande qu'un humain, la taille et le poids monstrueux d'une masse de Bullgryn sont ses seuls atouts au combat.",
        Type: "Armes de mêlée Ogryn",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 4",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal",
        Valeur: "3",
        Rareté: "1",
        MotsClés: "IMPERIUM, ASTRA MILITARUM, MILITARUM AUXILLA"
    },
    {
        Id: 83,
        Nom: "Baïonnette de l'Écorcheur",
        Description: "Les membres du Departmento Munitorum plaisantent en disant que les baïonnettes ont été installées à l'origine sur les fusils écorcheurs Ogryn pour que leurs porteurs à l'esprit lent sachent quelle partie de l'arme pointer vers l'ennemi. En vérité, une charge d'Ogryn est rendue beaucoup plus mortelle par ces larges dalles de métal affûtées.",
        Type: "Armes de mêlée Ogryn",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 3",
        DésDégâtsSupplémentaires: "3",
        Portée: "-",
        Rafale: "-",
        Traits: "Fiable",
        Valeur: "3",
        Rareté: "1",
        MotsClés: "LAME, IMPERIUM, ASTRA MILITARUM, MILITARUM AUXILLA"
    },
    {
        Id: 94,
        Nom: "Fusil Kroot",
        Description: "Les Kroot ont créé des lanceurs de projectiles chimiques primitifs il y a des siècles, et depuis qu'ils ont été exposés aux T'au et à d'autres espèces avancées, ils ont modifié et amélioré leurs armes tout comme ils modifient leur propre biologie.",
        Type: "Armes à distance",
        Dégâts: "8",
        DésDégâtsSupplémentaires: "1",
        PénétrationArmure: "-",
        Portée: "12/24/36",
        Rafale: "2",
        Traits: "Tir Rapide (1)",
        Valeur: "3",
        Rareté: "3",
        MotsClés: "2 MAINS, PROJECTILE, KROOT"
    },
    {
        Id: 84,
        Nom: "Carabine Bolter",
        Description: "Variante compacte du fusil Bolter Primaris, la carabine Bolter dispose d'une poignée supplémentaire montée à l'avant de l'arme pour une précision accrue en combat rapproché.",
        Type: "Armes à distance",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "1",
        PénétrationArmure: "-",
        Portée: "12/24/36",
        Rafale: "2",
        Traits: "Assaut, Brutal, Tir Rapide (2)",
        Valeur: "6",
        Rareté: "3",
        MotsClés: "BOLT, IMPERIUM, ADEPTUS ASTARTES, PRIMARIS"
    },
    {
        Id: 85,
        Nom: "Bolter Condemnor",
        Description: "Une arme rare qui combine la puissance brute d'un Bolter avec la théurgie repoussant le Warp des fidèles de l'Empereur ; un Bolter est combiné à une arbalète archaïque qui tire des pieux en argent gravés de sceaux sacrés de rupture du Warp qui retournent les dons vils d'un psyker contre lui pour infliger des blessures périlleuses.",
        Type: "Armes à distance",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "1",
        PénétrationArmure: "-",
        Portée: "12/24/36",
        Rafale: "2",
        Traits: "Béni (3), Brutal, Tir Rapide (2)",
        Valeur: "6",
        Rareté: "4",
        MotsClés: "BOLT, IMPERIUM, ADEPTA SORORITAS"
    },
    {
        Id: 86,
        Nom: "Rayon d'Éradication",
        Description: "Rares reliques de l'Âge Sombre de la Technologie, les machines impitoyables qui alimentent le Rayon d'Éradication sont peu comprises au 41ème millénaire, bien que ses effets soient indéniables. Tout ce qui est pris dans le faisceau maladif produit par un Rayon d'Éradication est désassemblé atome par atome et effacé de la réalité.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Dégâts: "13",
        DésDégâtsSupplémentaires: "1",
        PénétrationArmure: "-2",
        Portée: "12/24/36",
        Rafale: "1",
        Traits: "Lourd (5), Déchirant (3)",
        Valeur: "8",
        Rareté: "3",
        MotsClés: "ADEPTUS MECHANICUS"
    },
    {
        Id: 87,
        Nom: "Éclateur à Fléchettes",
        Description: "Crachant une fusillade de micro-fléchettes à courte portée, les éclateurs à fléchettes sont l'arme de poing standard des Sicarian Infiltrators, facilement maniables d'une main tout en traquant une proie. Les munitions à fléchettes utilisent une technologie bioélectrique avancée pour se guider sur la cible du porteur, garantissant que ceux frappés par un seul projectile sont ensuite abattus par mille autres entailles.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Dégâts: "8",
        DésDégâtsSupplémentaires: "2",
        PénétrationArmure: "-",
        Portée: "6/12/18",
        Rafale: "2",
        Traits: "Pistolet, Tir Rapide (4)",
        Valeur: "4",
        Rareté: "1",
        MotsClés: "PROJECTILE, ADEPTUS MECHANICUS"
    },
    {
        Id: 88,
        Nom: "Macrostubbe",
        Description: "Bien loin des simples lanceurs de projectiles, chaque macrostubbe est une relique hautement avancée capable de déchaîner une grêle de balles. Les macrostubbes utilisent des technologies de rechargement automatique et de refroidissement pour garantir que l'arme ne se déforme pas ou ne fonde pas malgré la chaleur intense générée par le torrent de balles.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Dégâts: "9",
        DésDégâtsSupplémentaires: "2",
        PénétrationArmure: "-",
        Portée: "6/12/18",
        Rafale: "3",
        Traits: "Pistolet, Tir Rapide (3)",
        Valeur: "6",
        Rareté: "3",
        MotsClés: "PROJECTILE, ADEPTUS MECHANICUS"
    },
    {
        Id: 89,
        Nom: "Serpenta à Phosphore",
        Description: "Une arme de poing chimique de conception antique, une serpenta à phosphore tire des projectiles incendiaires brûlants qui provoquent des conflagrations toxiques. Ceux frappés par une salve de phosphore vil brûlent rapidement alors qu'il grésille à travers la chair et l'armure, et ceux qui survivent trouvent bientôt que l'explosion lumineuse fait d'eux une cible plus facile pour les tirs suivants.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Dégâts: "12",
        DésDégâtsSupplémentaires: "2",
        PénétrationArmure: "-1",
        Portée: "9/18/27",
        Rafale: "1",
        Traits: "Assaut, Fusion",
        Valeur: "7",
        Rareté: "3",
        MotsClés: "PHOSPHEX, ADEPTUS MECHANICUS"
    },
    {
        Id: 90,
        Nom: "Carabine Stub",
        Description: "Combinant la machinerie avancée du Mechanicus avec la fiabilité des armes à projectiles traditionnelles, la carabine stub peut déchaîner un torrent de balles comparable à un Stubber lourd tout en étant assez petite pour être maniée par un Skitarii.",
        Type: "Armes à distance de l'Adeptus Mechanicus",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "1",
        PénétrationArmure: "-",
        Portée: "9/18/27",
        Rafale: "3",
        Traits: "Pistolet",
        Valeur: "6",
        Rareté: "2",
        MotsClés: "PROJECTILE, ADEPTUS MECHANICUS"
    },
    {
        Id: 91,
        Nom: "Gantelet Grenadier",
        Description: "Ces lance-grenades de la taille d'un Ogryn sont construits pour être incroyablement stables, et peuvent être utilisés en toute sécurité comme des masses massives sans risque de détonations accidentelles. Utilisant le même mécanisme de tir simple que le fusil écorcheur, les Bullgryns utilisent les gantelets grenadiers pour assaillir les ennemis avec des explosions de masse derrière des murs de boucliers impénétrables.",
        Type: "Armes à distance du Militarum Auxilla",
        Dégâts: "11",
        DésDégâtsSupplémentaires: "3",
        PénétrationArmure: "-",
        Portée: "6/12/18",
        Rafale: "1",
        Traits: "Assaut, Explosion (2), Lourd (5)",
        Valeur: "6",
        Rareté: "3",
        MotsClés: "EXPLOSIF, ASTRA MILITARUM, MILITARUM AUXILLA"
    },
    {
        Id: 92,
        Nom: "Fusil Ratling",
        Description: "Bien que construit à une échelle légèrement plus petite que les autres armes impériales, le long canon de ces fusils de précision dépasse la taille d'un Ratling. Bien que les fusils Ratling soient presque universellement de simples lanceurs de projectiles, ils sont mortels entre les mains de leur espèce à la vue perçante.",
        Type: "Armes à distance du Militarum Auxilla",
        Dégâts: "9",
        DésDégâtsSupplémentaires: "1",
        PénétrationArmure: "-",
        Portée: "18/36/54",
        Rafale: "0",
        Traits: "Sniper (3), Fiable",
        Valeur: "6",
        Rareté: "1",
        MotsClés: "PROJECTILE, IMPERIUM, ASTRA MILITARUM, MILITARUM AUXILLA"
    },
    {
        Id: 93,
        Nom: "Fusil Écorcheur",
        Description: "Grand, robuste et basique, le fusil écorcheur (Ripper Gun) est conçu pour être manié par les Ogryns. Pour cette raison, sa taille et sa construction solide garantissent qu'il est aussi utile comme gourdin que comme arme à feu. La stupidité et l'imprécision typiques d'un Ogryn ont façonné la conception du fusil écorcheur, résultant en un mécanisme de détente personnalisé activé en pressant la poignée pour tirer une rafale. Un limiteur de rafale est câblé dans chaque fusil écorcheur pour s'assurer qu'un Ogryn excité ne vide pas un chargeur entier dès la première pression.",
        Type: "Armes à distance du Militarum Auxilla",
        Dégâts: "11",
        DésDégâtsSupplémentaires: "2",
        PénétrationArmure: "-",
        Portée: "6/12/18",
        Rafale: "2",
        Traits: "Assaut, Brutal, Lourd (5)",
        Valeur: "5",
        Rareté: "3",
        MotsClés: "PROJECTILE, IMPERIUM, ASTRA MILITARUM, MILITARUM AUXILLA"
    },
    {
        Id: 95,
        Nom: "Bombe à Fragmentations (Frag)",
        Description: "Conçues spécialement pour les mains surdimensionnées des Ogryns, les bombes à fragmentations sont simplement des grenades frag améliorées et simplifiées pour des esprits frustes. Une bombe frag provoque une explosion de shrapnels plus large et plus mortelle, bien que des plaques de pression doivent être intégrées dans chaque bombe au cas où un Ogryn oublierait de la lancer après avoir retiré la goupille.",
        Type: "Grenades",
        Dégâts: "12",
        DésDégâtsSupplémentaires: "4",
        PénétrationArmure: "-",
        Portée: "(F) x 2m ou via Lanceur",
        Rafale: "-",
        Traits: "Explosion (8)",
        Valeur: "5",
        Rareté: "1",
        MotsClés: "EXPLOSIF, IMPERIUM"
    },
    {
        Id: 96,
        Nom: "Bombes à Fusion (Melta)",
        Description: "En compressant une technologie sous-moléculaire, une bombe à fusion produit l'intensité solaire d'un fuseur dans une explosion portative terrifiante. Ces explosifs peuvent réduire même les coques les plus épaisses de vaisseaux spatiaux en scories en fusion en quelques secondes.",
        Type: "Grenades",
        Dégâts: "16",
        DésDégâtsSupplémentaires: "4",
        PénétrationArmure: "-4",
        Portée: "(F) x 2m ou via Lanceur",
        Rafale: "-",
        Traits: "Explosion (4)",
        Valeur: "5",
        Rareté: "3",
        MotsClés: "EXPLOSIF, IMPERIUM"
    },
    {
        Id: 97,
        Nom: "Grenade Brouille-cerveau (Mindscrambler)",
        Description: "Déchargeant des vagues sauvages de bio-électricité dans les circuits et les systèmes nerveux, les grenades brouille-cerveau sont tout aussi mortelles contre les ennemis organiques ou mécaniques. Cas rare d'anciennes études Biologis appliquées directement à l'armement, chaque grenade contient la réplique d'organes d'une créature xenos capable de produire des décharges électriques à haute tension.",
        Type: "Grenades",
        Dégâts: "10",
        DésDégâtsSupplémentaires: "4",
        PénétrationArmure: "-",
        Portée: "(F) x 4m ou via Lanceur",
        Rafale: "-",
        Traits: "Agonisant, Arc (4), Explosion (6)",
        Valeur: "5",
        Rareté: "2",
        MotsClés: "EXPLOSIF, ADEPTUS MECHANICUS"
    },
    {
        Id: 98,
        Nom: "Grenade à Choc (Shock)",
        Description: "Éclatant dans une explosion assourdissante de lumière aveuglante, les grenades à choc sont utilisées pour désorienter et terrifier les cibles malheureuses des Primaris Reivers afin de garantir une charge dévastatrice. Une grenade à choc inflige des dégâts de Choc aux cibles prises dans le rayon d'explosion au lieu de blessures.",
        Type: "Grenades",
        Dégâts: "3 (Choc)",
        DésDégâtsSupplémentaires: "-",
        PénétrationArmure: "-",
        Portée: "(F) x 4m ou via Lanceur",
        Rafale: "-",
        Traits: "Explosion (6), Inflige (Aveuglé 1, Vulnérable 1)",
        Valeur: "2",
        Rareté: "1",
        MotsClés: "EXPLOSIF, IMPERIUM"
    },
    {
        Id: 99,
        Nom: "Chordclaw (Profil d'Arme)",
        Description: "Les doigts scalpels d'une Chordclaw sont connus pour désassembler un corps avec l'efficacité sans âme typique de l'Adeptus Mechanicus. Les trois chiffres acérés comme des aiguilles d'une Chordclaw bougent avec une vitesse déconcertante, accélérée par la résonance sonique de toutes les armes transoniques qui retourne l'estomac.",
        Type: "Mêlée",
        Dégâts: "(F) +3",
        DésDégâtsSupplémentaires: "3",
        PénétrationArmure: "-",
        Portée: "-",
        Rafale: "-",
        Traits: "Agonisant, Déchirant (6)",
        Valeur: "5",
        Rareté: "3",
        MotsClés: "LAME, TRANSONIQUE, ADEPTUS MECHANICUS"
    }
]