export const ListeArmesAeldari = [
    {
        Id: 1,
        Nom: "Lance chantante",
        Description: "Les Lances chantantes sont de longues pièces de métal argenté étincelant incrusté de pierres précieuses, qui bourdonnent et vibrent entre les mains d'un Psyker Eldar. Lorsqu'elles sont lancées, elles volent et frappent avec une précision remarquable avant de revenir dans la main du lanceur en un éclat de lumière.",
        Type: "Armes de mêlée Aeldari",
        PénétrationArmure: "-",
        Dégâts: "(F) + 6",
        DésDégâtsSupplémentaires: "5",
        Portée: "Lancer 2 m ; F x 5",
        Rafale: "-",
        Traits: "Assaut, Force, Warp",
        Valeur: "11",
        Rareté: "Unique",
        MotsClés: "FORCE, AELDARI, ASURYANI"
    },
    {
        Id: 2,
        Nom: "Lame sorcière",
        Description: "Maniées par les Psycharques et les Grands prophètes, les Lames sorcières canalisent les énergies psychiques de leur porteur pour trancher aussi bien des matières ordinaires que des matériaux issus du Warp.",
        Type: "Armes de mêlée Aeldari",
        PénétrationArmure: "-",
        Dégâts: "(F) + 6",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Force, Parade, Warp",
        Valeur: "9",
        Rareté: "Très rare",
        MotsClés: "FORCE, AELDARI, ASURYANI"
    },
    {
        Id: 3,
        Nom: "Sabre du vide",
        Description: "Fabriquées à partir de longerons de moelle spectrale souillés, arrachées à la carcasse d'un Vaisseau-monde tombé ou volées à un vaisseau toujours en vie, ces lames projettent une terrible aura de tourment capable de traverser aisément du plastacier. Le porteur d'une arme aussi maudite est tenu en grande estime parmi les groupes de Corsaires les plus brutaux, mais il est à jamais damné aux yeux de ses cousins des Vaisseaux-mondes. Tout Test effectué dans le cadre d'interactions sociales avec un individu avec le Mot-clé ASURYANI subit une pénalité de +4 SD.",
        Type: "Armes de mêlée Aeldari",
        PénétrationArmure: "-3",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal, Parade",
        Valeur: "6",
        Rareté: "Très rare",
        MotsClés: "CHAMP DE FORCE, AELDARI, ANHRATHE"
    },
    {
        Id: 4,
        Nom: "Catapulte shuriken",
        Description: "Ces fusils élégants tirent des centaines de disques monomoléculaires à partir de leur noyau de munitions en un clin d'œil. Les ennemis sont ainsi submergés par une tempête de projectiles incroyablement tranchants qui lacèrent facilement la chair et les os.",
        Type: "Armes à distance Aeldari",
        Degats: "10",
        DS: "1",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "3",
        Traits: "Assaut, Perforant (3)",
        Valeur: "6",
        Rarete: "Rare",
        MotsClés: "SHURIKEN, AELDARI, ASURYANI"
    },
    {
        Id: 5,
        Nom: "Éclateur laser",
        Description: "Ces armes d'assaut laser utilisent des prismes de cristal à harmonisation psychique pour concentrer des faisceaux brillants de lumière le long de leurs barils réfléchissants. Lorsqu'ils sont déchargés, ils traversent leurs cibles dans un élégant spectacle lumineux de mort et de destruction.",
        Type: "Armes à distance Aeldari",
        Degats: "7",
        DS: "1",
        PA: "-",
        Portee: "12 / 24 / 36",
        Rafale: "4",
        Traits: "Assaut",
        Valeur: "5",
        Rarete: "Très rare",
        MotsClés: "LASER, AELDARI"
    },
    {
        Id: 6,
        Nom: "Fusil à fusion",
        Description: "Les Fusils à fusion sont similaires aux Fuseurs utilisés par l'Imperium et hyper-agitent les molécules de leur cible pour obtenir de terrifiants effets. La chaleur et l'énergie générées provoquent une immolation instantanée et la vaporisation de tout ce qui se trouve autour de la cible.",
        Type: "Armes à distance Aeldari",
        Degats: "16",
        DS: "2",
        PA: "-4",
        Portee: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Assaut, Fusion",
        Valeur: "6",
        Rarete: "Très rare",
        MotsClés: "FUSION, AELDARI"
    },
    {
        Id: 7,
        Nom: "Long fusil de ranger",
        Description: "Cultivé avec beaucoup de difficulté et sculpté à la main par les Chanteurs de moelle Aeldari, chaque Long fusil de ranger est une œuvre d'art exquise spécialement conçue pour un seul Ranger Aeldari. Ses stabilisateurs gyrostatiques éliminent tout recul et sa technologie cristalline énigmatique projette des faisceaux de lumière mortelle à travers le champ de bataille avec une précision extrême.",
        Type: "Armes à distance Aeldari",
        Degats: "10",
        DS: "1",
        PA: "-",
        Portee: "18 / 36 / 54",
        Rafale: "0",
        Traits: "Précis (4)",
        Valeur: "7",
        Rarete: "Très rare",
        MotsClés: "LASER, AELDARI"
    },
    {
        Id: 8,
        Nom: "Pistolet shuriken",
        Description: "Avec leur facilité d'utilisation et leur recul quasi inexistant, les Pistolets shuriken sont prisés par les Aeldari qui cherchent une rapide victoire grâce à une rafale précise de shurikens à courte portée.",
        Type: "Armes à distance Aeldari",
        Degats: "10",
        DS: "1",
        PA: "-",
        Portee: "6 / 12 / 18",
        Rafale: "2",
        Traits: "Pistolet, Perforant (3)",
        Valeur: "6",
        Rarete: "Rare",
        MotsClés: "SHURIKEN, AELDARI, ASURYANI"
    }
]