export const ListeArmesOrk = [
    {
        Id: 1,
        Nom: "Lance chantante",
        Description: "Les Lances chantantes sont de longues pièces de métal argenté étincelant incrusté de pierres précieuses, qui bourdonnent et vibrent entre les mains d'un Psyker Eldar. Lorsqu'elles sont lancées, elles volent et frappent avec une précision remarquable avant de revenir dans la main du lanceur en un éclat de lumière.",
        Type: "Armes de mêlée Aeldari",
        PénétrationArmure: "-",
        Dégâts: "(F) + 6",
        DésDégâtsSupplémentaires: "5",
        Portée: "Lancer 2 m ; F x 5",
        Rafale: "-",
        Traits: "Assaut, Force, Warp",
        Valeur: "11",
        Rareté: "Unique",
        MotsClés: "FORCE, AELDARI, ASURYANI"
    },
    {
        Id: 2,
        Nom: "Lame sorcière",
        Description: "Maniées par les Psycharques et les Grands prophètes, les Lames sorcières canalisent les énergies psychiques de leur porteur pour trancher aussi bien des matières ordinaires que des matériaux issus du Warp.",
        Type: "Armes de mêlée Aeldari",
        PénétrationArmure: "-",
        Dégâts: "(F) + 6",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Force, Parade, Warp",
        Valeur: "9",
        Rareté: "Très rare",
        MotsClés: "FORCE, AELDARI, ASURYANI"
    },
    {
        Id: 3,
        Nom: "Sabre du vide",
        Description: "Fabriquées à partir de longerons de moelle spectrale souillés, arrachées à la carcasse d'un Vaisseau-monde tombé ou volées à un vaisseau toujours en vie, ces lames projettent une terrible aura de tourment capable de traverser aisément du plastacier. Le porteur d'une arme aussi maudite est tenu en grande estime parmi les groupes de Corsaires les plus brutaux, mais il est à jamais damné aux yeux de ses cousins des Vaisseaux-mondes. Tout Test effectué dans le cadre d'interactions sociales avec un individu avec le Mot-clé ASURYANI subit une pénalité de +4 SD.",
        Type: "Armes de mêlée Aeldari",
        PénétrationArmure: "-3",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal, Parade",
        Valeur: "6",
        Rareté: "Très rare",
        MotsClés: "CHAMP DE FORCE, AELDARI, ANHRATHE"
    },
    {
        Id: 4,
        Nom: "Bâton de Bizarboy",
        Description: "Les Bâtons de Bizarboy sont d'étranges assemblages de tuyaux en cuivre, d'ampoules en verre et de fétiches cliquetants qui accordent aux Psykers Orks un semblant de contrôle sur leurs pouvoirs si imprévisibles.",
        Type: "Armes de mêlée Orks",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 4",
        DésDégâtsSupplémentaires: "1",
        Portée: "2",
        Rafale: "-",
        Traits: "Force, Waaagh!",
        Valeur: "5",
        Rareté: "Très rare",
        MotsClés: "FORCE, À 2 MAINS, ORK"
    },
    {
        Id: 5,
        Nom: "Gros kikoup'",
        Description: "Les Gros kikoup' se résument à de gigantesques morceaux de métal maniés à deux mains. Leur apparence et leur construction sont incroyablement variées, mais le résultat final de leur utilisation entre les mains d'un Ork en colère est toujours inoubliable.",
        Type: "Armes de mêlée Orks",
        PénétrationArmure: "-1",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "5",
        Portée: "-",
        Rafale: "-",
        Traits: "Waaagh!",
        Valeur: "4",
        Rareté: "Rare",
        MotsClés: "LAME, À 2 MAINS, ORK"
    },
    {
        Id: 6,
        Nom: "Kikoup'",
        Description: "Souvent la première arme qu'un jeune Ork tient dans ses mains, les Kikoup' sont de simples lames lourdes qui se combinent avec la force naturelle d'un Ork pour réduire l'infanterie ennemie en charpie.",
        Type: "Armes de mêlée Orks",
        PénétrationArmure: "-",
        Dégâts: "(F) + 3",
        DésDégâtsSupplémentaires: "3",
        Portée: "-",
        Rafale: "-",
        Traits: "Fiable, Waaagh!",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "LAME, ORK"
    },
    {
        Id: 7,
        Nom: "Kikoup' tronçonneur",
        Description: "Approximation grossière des armes impériales similaires, les Kikoup' tronçonneurs sont généralement mal entretenus, émettent un grincement insupportable et consomment du carburant à une vitesse affolante. Cela ne les empêche cependant pas de traverser leurs cibles avec une efficacité et une brutalité remarquables.",
        Type: "Armes de mêlée Orks",
        PénétrationArmure: "-",
        Dégâts: "(F) + 5",
        DésDégâtsSupplémentaires: "4",
        Portée: "-",
        Rafale: "-",
        Traits: "Brutal, Waaagh!",
        Valeur: "5",
        Rareté: "Très rare",
        MotsClés: "TRONÇONNEUSE, ORK"
    },
    {
        Id: 8,
        Nom: "Pince énergétik'",
        Description: "Ces pinces encombrantes utilisent des moteurs hydrauliques pour actionner une paire de griffes brutales, chacune entourée d'un champ énergétique grésillant, autour de leur malheureuse victime, qui finit broyée et débitée avec une force implacable.",
        Type: "Armes de mêlée Orks",
        PénétrationArmure: "-3",
        Dégâts: "(F) + 6",
        DésDégâtsSupplémentaires: "5",
        Portée: "1",
        Rafale: "-",
        Traits: "Brutal, Encombrant (3), Waaagh!",
        Valeur: "8",
        Rareté: "Très rare",
        MotsClés: "CHAMP DE FORCE, ORK"
    },
    {
        Id: 9,
        Nom: "Kalibr'",
        Description: "Ces gros pistolets sont bruyants et grossiers. Ils tirent des munitions tellement chargées de poudre à canon qu'elles sont presque inutiles sauf à bout portant.",
        Type: "Armes à distance Orks",
        Dégâts: "1",
        PénétrationArmure: "-",
        Portée: "6 / 12 / 18",
        Rafale: "1",
        Traits: "Pistolet, Waaagh!",
        Valeur: "3",
        Rareté: "Courant",
        MotsClés: "PROJECTILE, ORK"
    },
    {
        Id: 10,
        Nom: "Fling'",
        Description: "Le type d'arme à feu Ork le plus courant. Ces fusils encombrants fabriqués avec de la ferraille sont à mi-chemin entre un gourdin et une arme automatique. Ils vomissent des murs de balles imprécis et de gros calibre avec une détonation assourdissante souvent appelée « Dakka » par leurs propriétaires peaux-vertes.",
        Type: "Armes à distance Orks",
        Dégâts: "1",
        PénétrationArmure: "-",
        Portée: "9 / 18 / 27",
        Rafale: "2",
        Traits: "Assaut, Waaagh!",
        Valeur: "4",
        Rareté: "Peu courant",
        MotsClés: "PROJECTILE, ORK"
    },
    {
        Id: 11,
        Nom: "Krameur",
        Description: "Ces lance-flammes fuitent et crachent n'importe quel mélange de liquides inflammables que leur propriétaire peut trouver. Les Krameurs sont des armes dangereuses et imprévisibles qui peuvent même être utilisées comme des torches de soudage improvisées en cas de besoin.",
        Type: "Armes à distance Orks",
        Dégâts: "1",
        PénétrationArmure: "-",
        Portée: "4 / 8 / 12",
        Rafale: "1",
        Traits: "Assaut, Flamme",
        Valeur: "5",
        Rareté: "Peu courant",
        MotsClés: "FLAMME, ORK"
    },
    {
        Id: 12,
        Nom: "Gros fling'",
        Description: "Ces armes massives et entièrement automatiques sont essentiellement des Fling' à plus grande échelle. Ils tirent un flux cacophonique de munitions surdimensionnées qui ne manquera pas de faire sourire jusqu'aux oreilles les Orks à proximité.",
        Type: "Armes à distance Orks",
        Dégâts: "2",
        PénétrationArmure: "-",
        Portée: "18 / 36 / 54",
        Rafale: "3",
        Traits: "Assaut, Waaagh!",
        Valeur: "5",
        Rareté: "Peu courant",
        MotsClés: "PROJECTILE, ORK"
    },
    {
        Id: 13,
        Nom: "Fling' de lux'",
        Description: "Ajusté pour augmenter la cadence de tir, charger des munitions au calibre improbable ou même produire des décharges énergétiques imprévisibles, chaque Fling' de lux' est une arme unique créée pour un Frimeur obsédé par l'image et décoré de bidules kibrill' et de trophées précieux.",
        Type: "Armes à distance Orks",
        Dégâts: "2",
        PénétrationArmure: "-2",
        Portée: "12 / 24 / 36",
        Rafale: "3",
        Traits: "Kustom, Lourd (4)",
        Valeur: "8",
        Rareté: "Unique",
        MotsClés: "ORK"
    },
    {
        Id: 14,
        Nom: "Lance-rokettes",
        Description: "Les Lance-rokettes tirent des explosifs simplistes avec des charges utiles extrêmement variables.",
        Type: "Armes à distance Orks",
        Dégâts: "1d3",
        PénétrationArmure: "-2",
        Portée: "12 / 24 / 36",
        Rafale: "-",
        Traits: "Assaut, Explosion (4)",
        Valeur: "7",
        Rareté: "Rare",
        MotsClés: "EXPLOSIF, ORK"
    },
    {
        Id: 15,
        Nom: "Frag à manche",
        Description: "Un explosif brut doté d'une poignée pratique. Il arrive que des Orks submergés par une « WAAAGH! » utilisent ces grenades volumineuses comme des gourdins, avec plus ou moins de succès.",
        Type: "Armes à distance Orks",
        Dégâts: "5",
        PénétrationArmure: "-",
        Portée: "(F) x 4 m ou portée du lance-grenades",
        Rafale: "-",
        Traits: "Explosion (6)",
        Valeur: "2",
        Rareté: "Peu courant",
        MotsClés: "EXPLOSIF, ORK"
    }
]