export const ListeDisciplineBibliothecaire = [
    {
        Id: 1,
        Nom: "Voile du Temps",
        CoûtPX: "20",
        SD: "8",
        Activation: "Action",
        Durée: "Maintenue",
        Portée: "20m",
        CiblesMultiples: "Oui",
        MotsClés: "PSYCHIQUE",
        Prerequis: "ADEPTUS ASTARTES",
        Effet: "Vous canalisez le Warp pour déformer le flux du temps, étirant artificiellement un seul instant. Tant que vous maintenez ce pouvoir, votre cible peut effectuer deux tours par round.",
        Surpuissance: ""
    },
    {
        Id: 2,
        Nom: "Puissance des Héros",
        CoûtPX: "15",
        SD: "7",
        Activation: "Action",
        Durée: "Maintenue",
        Portée: "15m",
        CiblesMultiples: "Non",
        MotsClés: "PSYCHIQUE",
        Prerequis: "ADEPTUS ASTARTES",
        Effet: "Invoquant le savoir labyrinthique de votre Librarius, vous conférez la puissance martiale de vos ancêtres Astartes à votre allié. Votre cible gagne +1 en Force, Endurance et Initiative jusqu'au début de votre prochain tour.",
        Surpuissance: "[3] La cible gagne +1 supplémentaire en Force, Endurance et Initiative."
    },
    {
        Id: 3,
        Nom: "Fléau Psychique",
        CoûtPX: "20",
        SD: "Volonté de la cible",
        Activation: "Action",
        Durée: "Instantanée",
        Portée: "20m",
        CiblesMultiples: "Oui",
        MotsClés: "PSYCHIQUE",
        Prerequis: "ADEPTUS ASTARTES",
        Effet: "Vous perforez l'esprit de votre cible, le dépouillant d'informations de manière incroyablement douloureuse. Pour activer ce pouvoir, vous devez gagner un test de Volonté opposé. En cas de succès, vous infligez 1d3 Blessures Mortelles et la cible subit l'état de Peur.",
        Surpuissance: "[3] +1 Blessure Mortelle"
    },
    {
        Id: 4,
        Nom: "Fureur des Anciens",
        CoûtPX: "15",
        SD: "10",
        Activation: "Action",
        Durée: "Instantanée",
        Portée: "14m",
        CiblesMultiples: "Non",
        MotsClés: "PSYCHIQUE",
        Prerequis: "ADEPTUS ASTARTES",
        Effet: "Manifestant une monstruosité issue de l'histoire de votre Chapitre, vous déchaînez une terreur née du Warp sur vos ennemis. Le pouvoir voyage en ligne droite sur 14m ; tous les ennemis sur cette ligne subissent 2d3 Blessures Mortelles.",
        Surpuissance: "[1] +7m de portée. [2] +1 Blessure Mortelle."
    },
    {
        Id: 5,
        Nom: "Forteresse Psychique",
        CoûtPX: "15",
        SD: "6",
        Activation: "Maintenue",
        Durée: "Instantanée",
        Portée: "20m",
        CiblesMultiples: "Oui",
        MotsClés: "PSYCHIQUE",
        Prerequis: "ADEPTUS ASTARTES",
        Effet: "Vous fortifiez l'esprit de votre cible avec des sceaux hexagrammiques mentaux. La cible devient immunisée aux états de Peur et de Terreur tant que vous maintenez ce pouvoir, et gagne des dés de bonus de Détermination contre les pouvoirs psychiques.",
        Surpuissance: ""
    },
    {
        Id: 6,
        Nom: "Zone de Nullité",
        CoûtPX: "15",
        SD: "7",
        Activation: "Action",
        Durée: "Instantanée",
        Portée: "20m",
        CiblesMultiples: "Non",
        MotsClés: "PSYCHIQUE",
        Prerequis: "ADEPTUS ASTARTES",
        Effet: "Vous créez une zone de nullité d'un rayon de 6m centrée sur un point ou une cible. Le SD de tous les tests de Maîtrise Psychique (Vol) effectués dans la zone est augmenté de votre score de Volonté. Le trait Armure Invulnérable n'a aucun effet dans la zone.",
        Surpuissance: "[1] +10m de portée. [2] Double le rayon de la zone."
    }
]