export const ListeDomaineDesRunesDeBataille = [
    {
        Id: 1,
        Nom: "Bravoure/Horreur",
        CoûtPX: "20",
        SD: "5",
        Activation: "Action",
        Durée: "Maintien",
        Portée: "25 mètres",
        CiblesMultiples: "Non",
        MotsClés: "AELDARI, PSYCHIQUE",
        Prerequis: "le Psyker doit avoir le Mot-clé AELDARI",
        Effet: "vous vous projetez dans l'esprit de ceux qui vous entourent, afin de renforcer ou de saper leur détermination. Une fois ce pouvoir activé, vous pouvez choisir un des effets suivants : Bravoure : vous inculquez courage et détermination à vos alliés. Tant que le pouvoir est maintenu, vous et tous vos alliés à moins de 5 m gagnez +1 dé bonus aux Tests de Résolution. Horreur : vous sapez le courage et la détermination de vos ennemis. Ciblez un ennemi à portée comme point central d'une zone d'effet Explosion (6). Tous les ennemis dans cette zone subissent une pénalité de +1 SD aux Tests de Résolution tant que le pouvoir est maintenu.",
        Surpuissance: "[2] Bravoure : +1 dé bonus aux Tests de Résolution. [2] Horreur : pénalité de +1 SD aux Tests de Résolution de la cible."
    },
    {
        Id: 2,
        Nom: "Célérité/Entrave",
        CoûtPX: "20",
        SD: "5",
        Activation: "Action",
        Durée: "Maintien",
        Portée: "25 mètres",
        CiblesMultiples: "Non",
        MotsClés: "AELDARI, PSYCHIQUE",
        Prerequis: "le Psyker doit avoir le Mot-clé AELDARI",
        Effet: "vous modifiez la nature même du temps. Le flux temporel est temporairement modifié pour quelques privilégiés sur le champ de bataille. Une fois ce pouvoir activé, vous pouvez provoquer un des effets suivants : Célérité : vous modifiez l'écoulement du temps pour vous-même et vos alliés, et vous manifestez alors une vitesse surnaturelle. Tant que le pouvoir est maintenu, vous et tous vos alliés à moins de 5 m pouvez effectuer un Mouvement supplémentaire à chacun de vos Tours. Entrave : vous modifiez l'écoulement du temps pour vos ennemis, en les forçant à se mouvoir comme s'ils traversaient des eaux profondes. Ciblez un ennemi à portée comme point central d'une zone d'effet Explosion (6). Tous les ennemis dans cette zone alors que le pouvoir est maintenu se déplacent comme s'ils étaient en Terrain difficile.",
        Surpuissance: "[2] Célérité : augmente le rayon de l'effet sur les alliés à moins de 10 m. [2] Entrave : la zone d'effet devient Explosion (10)."
    },
    {
        Id: 3,
        Nom: "Dissimulation/Révélation",
        CoûtPX: "20",
        SD: "5",
        Activation: "Action",
        Durée: "Maintien",
        Portée: "25 mètres",
        CiblesMultiples: "Oui",
        MotsClés: "AELDARI, PSYCHIQUE",
        Prerequis: "le Psyker doit avoir le Mot-clé AELDARI",
        Effet: "vous projetez votre esprit et prenez le contrôle des ombres, que vous pouvez alors plier et façonner à votre guise. Une fois ce pouvoir activé, vous pouvez provoquer un des effets suivants : Dissimulation : vous attirez les ombres et les enfilez comme une cape pour dissimuler votre position. Tant que le pouvoir est maintenu, vous et vos alliés à moins de 5 m gagnez un bonus de +1 à votre Défense et +1 aux dés bonus à tous les Tests de Furtivité (A) que vous effectuez. Révélation : vous éloignez les ombres d'une cible à portée pour l'exposer complètement. Ciblez un ennemi à portée comme point central d'une zone d'effet Explosion (6). Tout ennemi dans cette zone pendant que le pouvoir est maintenu ne peut pas bénéficier de bonus aux Tests de Défense ou de Furtivité lié à un couvert.",
        Surpuissance: "[3] Dissimulation : les avantages augmentent de +1 en Défense et de +1d en Furtivité. [2] Révélation : la zone d'effet devient Explosion (10)."
    },
    {
        Id: 4,
        Nom: "Maîtrise/Maladresse",
        CoûtPX: "30",
        SD: "7",
        Activation: "Action",
        Durée: "Maintien",
        Portée: "25 mètres",
        CiblesMultiples: "Non",
        MotsClés: "AELDARI, PSYCHIQUE",
        Prerequis: "le Psyker doit avoir le Mot-clé AELDARI",
        Effet: "grâce à la faveur de Khaine, vous améliorez les prouesses au combat de vos alliés ou diminuez celles de vos ennemis. Une fois ce pouvoir activé, vous pouvez provoquer un des effets suivants : Maîtrise : vous canalisez une fraction de la puissance de Khaine pour améliorer les capacités de combat de vos alliés. Tant que le pouvoir est maintenu, vous et tous vos alliés à moins de 5 m gagnez +1 dé bonus à tous les Tests de Capacité de Combat (I) effectués. Maladresse : vous permettez à une partie de la colère et du mépris de Khaine de réprimer les capacités de combat de vos ennemis. Ciblez un ennemi à portée comme point central d'une zone d'effet Explosion (6). Tous les ennemis dans cette zone tant que le pouvoir est maintenu subissent un +1 SD à tous les Tests de Capacité de Combat (I) effectués.",
        Surpuissance: "[2] Maîtrise : +1 dé bonus supplémentaire aux Tests de Capacité de Combat (I). [2] Maladresse : +1 SD supplémentaire aux Tests de Capacité de Combat (I) de la cible."
    },
    {
        Id: 5,
        Nom: "Protection/Spoliation",
        CoûtPX: "20",
        SD: "5",
        Activation: "Action",
        Durée: "Maintien",
        Portée: "25 mètres",
        CiblesMultiples: "Non",
        MotsClés: "AELDARI, PSYCHIQUE",
        Prerequis: "le Psyker doit avoir le Mot-clé AELDARI",
        Effet: "vous tirez sur les fils du destin qui entourent n'importe quel champ de bataille afin d'isoler et de lier ceux d'un individu spécifique, dont le destin est modifié en conséquence. Une fois ce pouvoir activé, vous pouvez provoquer un des effets suivants : Protection : vous tissez votre destin et celui de vos alliés pour mieux vous protéger. Tant que le pouvoir est maintenu, vous et tous vos alliés à moins de 5 m gagnez un bonus de +1 à la Résistance de base. Spoliation : vous tissez le destin de vos ennemis pour les rendre plus vulnérables. Ciblez un ennemi à portée comme point central d'une zone d'effet Explosion (6). Tous les ennemis dans cette zone tant que le pouvoir est maintenu subissent une pénalité de -1 à leur Résistance de base.",
        Surpuissance: "[3] Protection : bonus supplémentaire de +1 à la Résistance. [3] Spoliation : pénalité supplémentaire de -1 à la Résistance."
    },
    {
        Id: 6,
        Nom: "Puissance/Atonie",
        CoûtPX: "30",
        SD: "7",
        Activation: "Action",
        Durée: "Maintien",
        Portée: "25 mètres",
        CiblesMultiples: "Non",
        MotsClés: "AELDARI, PSYCHIQUE",
        Prerequis: "le Psyker doit avoir le Mot-clé AELDARI",
        Effet: "vous communiez avec les esprits de ceux qui vous entourent, afin d'étendre leur potentiel ou de drainer leur volonté de se battre. Une fois ce pouvoir activé, vous pouvez provoquer un des effets suivants : Puissance : vous renforcez votre esprit et celui de vos alliés. Tant que ce pouvoir est maintenu, vous et tous vos alliés à moins de 5 m gagnez +1 DS à toute attaque de mêlée réussie. Atonie : vous sapez l'esprit de vos ennemis, qui sont alors envahis par le doute et le désespoir. Tous les ennemis dans une zone d'Explosion (6) à portée subissent une pénalité de -1 DS à toute attaque de mêlée réussie, jusqu'à un minimum de 0.",
        Surpuissance: "[3] Puissance : +1 DS aux dégâts. [3] Atonie : -1 DS aux dégâts de la cible."
    }
]