export const ListeEquipementsImpériales = [
    {
        Id: 1,
        Nom: "Armure primitive",
        Description: "Une telle armure est rarement capable de résister aux horreurs du 41e millénaire. Ce terme peut regrouper une grande variété d'équipements, des peaux de bêtes épaisses aux cuirs xenos écailleux, en passant par des combinaisons complètes de plaques de métal grossièrement martelées.",
        Ar: "2",
        Effet: "",
        Traits: "Massive (2)",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "LOURDE, PRIMITIVE"
    },
    {
        Id: 2,
        Nom: "Combinaison renforcée",
        Description: "Tissée à partir de microfibres résistantes aux chocs, les combinaisons renforcées offrent une protection discrète et peuvent être dissimulées sous les vêtements ou enfilées sous une armure plus lourde.",
        Ar: "2",
        Effet: "",
        Traits: "-",
        Valeur: "3",
        Rareté: "Rare",
        MotsClés: "LÉGÈRE, IMPERIUM, ADEPTUS MINISTORUM"
    },
    {
        Id: 3,
        Nom: "Armure composite",
        Description: "Fabriquée à partir d'écailles thermoplastiques microscopiques, l'Armure composite est aussi flexible que du tissu dans des circonstances normales, mais elle réagit instantanément aux chocs et à la chaleur et se rigidifie alors pour répartir la force cinétique sur sa surface.",
        Ar: "3",
        Effet: "",
        Traits: "-",
        Valeur: "3",
        Rareté: "Rare",
        MotsClés: "LÉGÈRE, IMPERIUM, [AU CHOIX]"
    },
    {
        Id: 4,
        Nom: "Gilet pare-balles",
        Description: "Composée de couches de matériaux absorbant les chocs, la surface ablative du Gilet pare-balles est particulièrement résistante aux éclats de shrapnel et aux explosions.",
        Ar: "3",
        Effet: "",
        Traits: "-",
        Valeur: "4",
        Rareté: "Courant",
        MotsClés: "PARE-BALLES, IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 5,
        Nom: "Manteau pare-balles",
        Description: "Les Commissaires et autres officiers supérieurs de la Garde impériale privilégient cette alternative légère au Gilet pare-balles standard.",
        Ar: "3",
        Effet: "",
        Traits: "-",
        Valeur: "4",
        Rareté: "Peu courant",
        MotsClés: "PARE-BALLES, IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 6,
        Nom: "Cuirasse Skitarii",
        Description: "Constituée de plaques solides d'armaplast protégées contre les radiations, la Cuirasse Skitarii protège son porteur à la fois de ses ennemis et des rayonnements dangereux produits par ses propres armes radioactives.",
        Ar: "4",
        Effet: "",
        Traits: "-",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "LOURDE, IMPERIUM, ADEPTUS MECHANICUS, SKITARII"
    },
    {
        Id: 7,
        Nom: "Armure carapace",
        Description: "Fabriquée à partir de plaques superposées d'armaplast rigides, l'Armure carapace offre une excellente protection contre les impacts directs, au détriment de la mobilité et de la flexibilité.",
        Ar: "4",
        Effet: "",
        Traits: "Massive (1)",
        Valeur: "5",
        Rareté: "Peu courant",
        MotsClés: "IMPERIUM, ADEPTUS ASTARTES, ASTRA MILITARUM"
    },
    {
        Id: 8,
        Nom: "Armure carapace Tempestus",
        Description: "Favorisée par les soldats d'élite du Militarum Tempestus, la silhouette imposante de l'Armure carapace Tempestus est à la fois intimidante et très résistante aux dégâts.",
        Ar: "4",
        Effet: "",
        Traits: "-",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "LOURDE, IMPERIUM, ASTRA MILITARUM, MILITARUM TEMPESTUS"
    },
    {
        Id: 9,
        Nom: "Armure énergétique légère",
        Description: "En réduisant l'encombrement des plaques de céramite, l'Armure énergétique légère offre les avantages d'une force servomoteur augmentée et d'une coque en céramite durable, mais sans sacrifier la mobilité ou l'agilité de son porteur.",
        Ar: "4",
        Effet: "",
        Traits: "Énergétique (1)",
        Valeur: "6",
        Rareté: "Très rare",
        MotsClés: "ÉNERGÉTIQUE, IMPERIUM"
    },
    {
        Id: 10,
        Nom: "Armure énergétique Sororitas",
        Description: "Fabriquée pour l'usage exclusif des Sœurs de bataille, l'Armure énergétique Sororitas est bénie et purifiée avec une grande ferveur religieuse pour protéger sa porteuse des hérétiques et des démons.",
        Ar: "5",
        Effet: "",
        Traits: "Énergétique (2)",
        Valeur: "6",
        Rareté: "Très rare",
        MotsClés: "ÉNERGÉTIQUE, IMPERIUM, ADEPTA SORORITAS"
    },
    {
        Id: 11,
        Nom: "Armure énergétique Ignatius",
        Description: "Prisée par les Inquisiteurs soucieux de leur sécurité, cette armure de maître très recherchée repousse efficacement d'innombrables coups qui pourraient mettre en danger l'individu de haut rang enfermé dans sa carapace gravée et blasonnée.",
        Ar: "5",
        Effet: "",
        Traits: "Énergétique (2)",
        Valeur: "7",
        Rareté: "Très rare",
        MotsClés: "ÉNERGÉTIQUE, IMPERIUM, INQUISITION"
    },
    {
        Id: 12,
        Nom: "Armure énergétique lourde",
        Description: "Sacrifiant la mobilité pour une couche de plaques plus épaisse et des moteurs internes de qualité industrielle, l'Armure énergétique lourde transforme son porteur en un char d'assaut ambulant, capable de traverser une tempête de balles sans même broncher.",
        Ar: "6",
        Effet: "",
        Traits: "Encombrante, Énergétique (3), Massive (1)",
        Valeur: "8",
        Rareté: "Très rare",
        MotsClés: "LOURDE, ÉNERGÉTIQUE, IMPERIUM, INQUISITION"
    },
    {
        Id: 13,
        Nom: "Bouclier tempête",
        Description: "Un Bouclier tempête est un bouclier lourd en forme de dalle de céramite renforcée et d'armaplast, augmenté d'un projecteur de champ interne qui l'entoure d'une énergie crépitante. Ces boucliers sont le plus souvent portés par des gardes du corps protégeant des individus d'une importance capitale ou par de prestigieux Astartes spécialistes du combat rapproché.",
        Ar: "*2",
        Effet: "",
        Traits: "Bouclier, Champ de force, Massive (1)",
        Valeur: "8",
        Rareté: "Unique",
        MotsClés: "CHAMP DE FORCE, IMPERIUM, ADEPTUS ASTARTES, ADEPTUS MINISTORUM, INQUISITION"
    },
    {
        Id: 14,
        Nom: "Champ réfracteur",
        Description: "Souvent dissimulés dans des bijoux sophistiqués, ces petits émetteurs de champ restent en veille jusqu'à ce qu'ils soient activés, après quoi ils érigent un champ de protection à courte portée autour d'un individu. Le Champ réfracteur dévie les attaques avec des éclats éblouissants de lumière multispectrale.",
        Ar: "*3",
        Effet: "",
        Traits: "Champ de force",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "CHAMP DE FORCE, IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 15,
        Nom: "Rosarius",
        Description: "Symbole de fonction pour l'Adeptus Ministorum et les Chapelains des Space Marines, le Rosarius prend la forme d'un Aquila impérial ou d'une croix gothique avec un bijou ou un crâne en son centre. Le Rosarius abrite un puissant émetteur de champ de force qui protège le porteur des attaques en convertissant toute l'énergie cinétique en éclats de lumière.",
        Ar: "*4",
        Effet: "",
        Traits: "Champ de force",
        Valeur: "7",
        Rareté: "Très rare",
        MotsClés: "CHAMP DE FORCE, IMPERIUM, ADEPTUS ASTARTES, ADEPTUS MINISTORUM"
    },
    {
        Id: 16,
        Nom: "Armure scout",
        Description: "Des plaques de céramite épaisses se combinent avec un tissage en carbone exceptionnellement résistant pour offrir une protection inégalée sur le champ de bataille sans sacrifier la mobilité.",
        Ar: "4",
        Effet: "",
        Traits: "-",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 17,
        Nom: "Armure Mk VII Aquila",
        Description: "Parfaitement adaptée à son porteur, l'Armure Aquila est l'un des modèles d'armure Astartes les plus anciens en circulation. Cette vénérable combinaison a fait ses preuves à maintes reprises dans une galaxie éternellement en guerre.",
        Ar: "5",
        Effet: "",
        Traits: "Énergétique (3)",
        Valeur: "8",
        Rareté: "Très rare",
        MotsClés: "ÉNERGÉTIQUE, IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 18,
        Nom: "Armure Mk X Tacticus",
        Description: "Les Astartes Primaris utilisent leur propre modèle d'armure énergétique, en raison des proportions stupéfiantes de leur organisme. L'Armure Mk X Tacticus s'inspire des protections d'autrefois, tout en intégrant les progrès du 41e millénaire en matière de déviation balistique pour incarner le summum de la gloire des Astartes.",
        Ar: "5",
        Effet: "",
        Traits: "Énergétique (4)",
        Valeur: "9",
        Rareté: "Très rare",
        MotsClés: "ÉNERGÉTIQUE, IMPERIUM, ADEPTUS ASTARTES, PRIMARIS"
    },
    {
        Id: 19,
        Nom: "Armure Terminator",
        Description: "L'Armure tactique Dreadnought a été conçue à l'origine pour les opérations d'abordage de vaisseaux spatiaux. Ces reliques des premiers siècles de l'Imperium sont dotées de plaques de blindage incroyablement épaisses et de moteurs surdimensionnés qui procurent aux Space Marines, déjà massifs, une stature de géant. Lorsque vous portez cette armure, vous êtes considéré comme étant de taille Grand.",
        Ar: "7",
        Effet: "",
        Traits: "Encombrante, Énergétique (4)",
        Valeur: "10",
        Rareté: "Unique",
        MotsClés: "ÉNERGÉTIQUE, IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 20,
        Nom: "Auspex",
        Description: "Un Auspex est un scanner portable polyvalent qui peut détecter de nombreux phénomènes avec un degré élevé de précision.",
        Ar: "",
        Effet: "activé en tant qu'Action de combat pour détecter les émissions d'énergie, les mouvements et autres signes de vie dans un rayon de 50 mètres.",
        Traits: "",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "IMPERIUM, ADEPTUS MECHANICUS"
    },
    {
        Id: 21,
        Nom: "Auto-reliquaire d'apaisement balistique (modèle Absolutis)",
        Description: "Délivré aux Space Marines Primaris, cet appareil contient des esprits-machines sophistiqués qui s'interfacent avec les armes et promulguent les bénédictions de l'Omnimessie sur celles-ci. Cet auto-reliquaire aide à restaurer le fonctionnement d'une arme enrayée et apaise l'esprit de guerre de l'arme.",
        Ar: "",
        Effet: "permet de réparer une arme enrayée avec une Action gratuite.",
        Traits: "",
        Valeur: "6",
        Rareté: "Très rare",
        MotsClés: "IMPERIUM, ADEPTUS ASTARTES, PRIMARIS"
    },
    {
        Id: 22,
        Nom: "Bottes magnétiques",
        Description: "Intégrées aux pieds de la plupart des Combinaisons spatiales et à l'armure des troupes impériales d'élite, ces bottes volumineuses peuvent être fortement magnétisées au gré du porteur pour les fixer à une surface métallique. Les Bottes magnétiques sont utilisées par les techniciens de la Marine impériale pour effectuer la maintenance des vaisseaux dans l'espace, ainsi que par l'Adeptus Astartes et les Fils du Tempestus pendant les manœuvres de combat entre plusieurs vaisseaux.",
        Ar: "",
        Effet: "quand les bottes sont activées avec une Action simple, les pieds du porteur sont entièrement fixés à n'importe quelle surface métallique. Les pieds du porteur ne peuvent être retirés de la surface métallique autrement que de leur propre gré. Le porteur peut marcher et se déplacer sur la surface métallique pendant que les bottes sont activées, mais sa Vitesse est réduite de 3.",
        Traits: "",
        Valeur: "4",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX], NAVIS IMPERIALIS"
    },
    {
        Id: 23,
        Nom: "Cape de caméléoline",
        Description: "Tissée à partir de fibres photo-réactives, la Cape caméléoline présente des couleurs changeantes qui brouillent les contours du porteur.",
        Ar: "",
        Effet: "+1 dé bonus aux Tests de Furtivité (A) et +1 à la Défense dans l'ombre ou à couvert.",
        Traits: "",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 24,
        Nom: "Chapelet de l'Ecclésiarchie",
        Description: "Ce symbole religieux est une icône de l'Adeptus Ministorum accrochée à un cordon de perles d'adamantium. Certains ordres de l'Adepta Sororitas considèrent chaque perle sur la corde comme une représentation d'actes de pénitence.",
        Ar: "",
        Effet: "le Chapelet peut être utilisé comme Symbole d'autorité (p. 240) ou, si nécessaire, comme garrot.",
        Traits: "",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "IMPERIUM, ADEPTUS MINISTORUM, ADEPTA SORORITAS"
    },
    {
        Id: 25,
        Nom: "Code des Sororitas",
        Description: "Ce petit livre détaille les traditions et les croyances des membres de l'Adepta Sororitas. Beaucoup d'entre elles personnalisent leur exemplaire pour refléter la nature particulière de leur Ordre.",
        Ar: "",
        Effet: "si vous possédez le Mot-clé ADEPTA SORORITAS, vous pouvez lire le Code des Sororitas dans le cadre d'un Rassemblement pour récupérer 1d3 Stress.",
        Traits: "",
        Valeur: "2",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 26,
        Nom: "Combi-outils",
        Description: "Omniprésents dans les rangs de l'Adeptus Mechanicus, ces appareils polyvalents sont le bon outil pour pratiquement tous les travaux techniques.",
        Ar: "",
        Effet: "vous ignorez les pénalités de SD pour construire, réparer, entretenir et saboter la technologie impériale.",
        Traits: "",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 27,
        Nom: "Combinaison spatiale",
        Description: "Trouvées dans divers styles et états de délabrement dans les compartiments de stockage des vaisseaux spatiaux, les Combinaisons spatiales protègent le porteur des rigueurs de la basse pression atmosphérique, du rayonnement solaire et du vide.",
        Ar: "",
        Effet: "protège le porteur du vide de l'espace, avec suffisamment d'oxygène pour cinq heures d'utilisation continue. Comprend un émetteur vox.",
        Traits: "",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 28,
        Nom: "Diagnosteur",
        Description: "Ce cogitateur médical sensible surveille la santé et les biorythmes d'un patient et aide au diagnostic de pratiquement n'importe quelle maladie physique.",
        Ar: "",
        Effet: "+1 dé bonus aux Tests de Medicae (Int) pour détecter et diagnostiquer les maladies, les blessures et les maux, ainsi que pour déterminer la cause de la mort.",
        Traits: "",
        Valeur: "5",
        Rareté: "Très rare",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 29,
        Nom: "Grav-chute",
        Description: "Ce dispositif anti-gravité de la taille d'un sac à dos peut contrôler une chute de presque n'importe quelle hauteur, y compris depuis des altitudes suborbitales. Il permet aux troupes impériales de flotter en toute sécurité jusqu'à un point d'atterrissage sur une colonne de force anti-gravitique. Un Grav-chute émet un champ suspenseur qui contrecarre la force de gravité au niveau particulaire, et deux petits propulseurs alimentés au prométhéum fournissent un certain contrôle directionnel.",
        Ar: "",
        Effet: "vous pouvez survoler ou contrôler une chute pendant une durée maximale d'une heure. Vous pouvez recharger la batterie solaire du Grav-chute en l'exposant au soleil pendant une heure.",
        Traits: "",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 30,
        Nom: "Horologium",
        Description: "Cette petite horloge peut être attachée au poignet ou tenue confortablement dans la main.",
        Ar: "",
        Effet: "les réglages sur l'écran de l'Horologium permettent de suivre avec précision l'heure impériale standard, ainsi que l'heure locale sur un vaisseau spatial ou une planète.",
        Traits: "",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 31,
        Nom: "Huile sanctifiée du Mechanicus",
        Description: "Bénie par l'Omnimessie, cette huile a une valeur considérable pour l'Adeptus Mechanicus. On raconte qu'elle est capable d'apaiser un esprit-machine agité.",
        Ar: "",
        Effet: "vous pouvez choisir d'ignorer une seule Complication impliquant la technologie impériale dans n'importe quelle scène.",
        Traits: "",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "IMPERIUM, ADEPTUS MECHANICUS"
    },
    {
        Id: 32,
        Nom: "Kit de missionnaire",
        Description: "Ces kits prêts à voyager identifient le porteur comme membre du Missionarus Galaxia et contiennent les éléments suivants : Textes sacrés du Credo Impérial, Sainte icône, Encens, Émetteur d'hymnes portable, Brochures liturgiques traduites en plusieurs variantes de bas gothique.",
        Ar: "",
        Effet: "+1 dé bonus aux Tests de Persuasion (Soc) effectués impliquant des convertis au Credo impérial et ceux qui cherchent la rédemption par la grâce de l'Empereur-Dieu.",
        Traits: "",
        Valeur: "2",
        Rareté: "Peu courant",
        MotsClés: "IMPERIUM, ADEPTUS MINISTORUM"
    },
    {
        Id: 33,
        Nom: "Kit Periculum",
        Description: "Assemblées pour les agents de la flotte Varonius, ces solides sacoches en cuir de gros contiennent des fournitures qu'ils pourront distribuer aux rares personnes capables et désireuses de participer à la défense du système de Gilead. Un Kit Periculum contient les éléments suivants : Horologium, Lunette de visée, Micro-vox, 2 Bâtons de survie, Respirateur, Tablette de données.",
        Ar: "",
        Effet: "",
        Traits: "",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "IMPERIUM, [AU CHOIX]"
    },
    {
        Id: 34,
        Nom: "Kit d'écriture",
        Description: "Cette sacoche contient des encres, des plumes, du parchemin et d'autres outils nécessaires pour rédiger une missive sur un rouleau de parchemin.",
        Ar: "",
        Effet: "",
        Traits: "",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "IMPERIUM"
    },
    {
        Id: 35,
        Nom: "Kit de ration du Munitorum",
        Description: "Ce kit compact comprend un bol, une assiette, une micro-cuisinière, une gourde et un ensemble complet de couverts, afin de permettre à l'utilisateur de réchauffer des rations ou de préparer des repas simples à partir d'ingrédients récupérés sur le terrain. Il contient également une semaine de rations et de comprimés de purification d'eau.",
        Ar: "",
        Effet: "+1 dé bonus aux Tests de Survie (Fid) effectués pour trouver de la nourriture et de l'eau.",
        Traits: "",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 36,
        Nom: "Kit de survie",
        Description: "Cette collection d'outils permet de maintenir son propriétaire en vie dans un environnement hostile. Le kit est composé des éléments suivants : Boussole, Corde, Eau, Filtres de purification, Bandelettes de test chimique.",
        Ar: "",
        Effet: "+1 dé bonus à tous les Tests de Survie (Fid).",
        Traits: "",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 37,
        Nom: "Lunettes infrarouges",
        Description: "La technologie thermosensible de ces lunettes permet au porteur de voir les signatures thermiques, même dans l'obscurité.",
        Ar: "",
        Effet: "vous ignorez les pénalités aux Tests dues aux conditions visuelles.",
        Traits: "",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 38,
        Nom: "Manuel d'édification",
        Description: "Le Manuel d'édification du fantassin impérial est un compagnon fidèle et incontournable pour tous les membres de l'Astra Militarum. Ce livre couvre divers sujets tels que l'entretien des armes et de l'équipement, l'hygiène personnelle, les règles et règlements de l'Astra Militarum et la reconnaissance de l'ennemi. Mis à jour lorsque cela est possible au fur et à mesure que de nouvelles informations sont découvertes ou corrigé dans les marges par un gribouillage frénétique, chaque livre est un document vivant indissociable de son propriétaire.",
        Ar: "",
        Effet: "+1 dé bonus aux Tests de Connaissances (Int). En cas de Complication sur le Test, l'utilisateur reçoit une information fausse et potentiellement dangereuse déterminée par le MJ.",
        Traits: "",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 39,
        Nom: "Medikit",
        Description: "Remplis avec un assortiment d'analgésiques, de plâtre, de cataplasme et de cautères, les Medikits contiennent juste assez de matériel médical pour faire la différence entre la vie et la mort sur le champ de bataille.",
        Ar: "",
        Effet: "vous pouvez effectuer des Tests de Medicae (Int) pour effectuer des interventions chirurgicales et soigner les autres sans subir de pénalité de SD, y compris en prenant l'option Restaurer du Stress (p. 124).",
        Traits: "",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 40,
        Nom: "Instruments chirurgicaux",
        Description: "Cette trousse contient des onguents sacrés, des outils chirurgicaux, des stérilisateurs et des doses d'antalgiques. Délivrés aux Sœurs Hospitalières, ces outils peuvent s'avérer très utiles à la survie de leurs patients.",
        Ar: "",
        Effet: "fonctionne comme un Medikit. +2 dés bonus aux Tests de Medicae (Int) lorsqu'un personnage est Mourant.",
        Traits: "",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "IMPERIUM, ADEPTA SORORITAS"
    },
    {
        Id: 41,
        Nom: "Medikit « Don du Martyr »",
        Description: "Cette trousse améliorée est une version supérieure du Medikit standard de l'Astra Militarum. Chargée de stimulants de combat, de gel thermostatique à cicatrisation automatique et de membres bioniques jetables à usage unique, ce medikit permet aux Fils du Tempestus blessés de retourner rapidement et efficacement au combat. Le Don du Martyr comprend même une ceinture de charges à fragmentation sous-cutanées qui peuvent être utilisées pour piéger le corps d'un Fils mortellement blessé.",
        Ar: "",
        Effet: "fonctionne comme un Medikit. Comprend un remplacement bionique standard pour tout membre ou œil perdu (p. 242) ; l'Augmentique est temporaire et devient inutilisable après 24 heures. La charge à fragmentation sous-cutanée a le même profil de dégâts qu'un missile Frag (p. 220).",
        Traits: "",
        Valeur: "6",
        Rareté: "Rare",
        MotsClés: "IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 42,
        Nom: "Outil de tranchée 9-70",
        Description: "Plus qu'une simple pelle, le bord composite de cet outil peut briser même la terre tassée la plus compacte.",
        Ar: "",
        Effet: "un Outil de tranchée 9-70 réduit de moitié le temps nécessaire pour creuser des tranchées, des abris et d'autres fortifications en terre. Il constitue également une arme improvisée robuste, comme de nombreux Gardes peuvent en témoigner.",
        Traits: "",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 43,
        Nom: "Pix-enregistreur",
        Description: "Bien qu'il puisse être utilisé pour projeter un faisceau de lumière, le but principal d'un Pix-enregistreur est d'enregistrer et d'envoyer des données visuelles. Si une personne donnée possède les autorisations nécessaires et connaît les bonnes runes de commande, elle peut connecter sa Tablette de données au Pix-enregistreur et voir à travers l'objectif de l'appareil.",
        Ar: "",
        Effet: "peut servir de source de lumière et montre des images en direct en cas de connexion sans fil à une Tablette de données.",
        Traits: "",
        Valeur: "4",
        Rareté: "Rare",
        MotsClés: "IMPERIUM, MILITARUM TEMPESTUS"
    },
    {
        Id: 44,
        Nom: "Plume automatique",
        Description: "Souvent considérée comme la véritable arme du scribe, le mécanisme interne mystérieux d'une Plume automatique peut copier, reproduire ou falsifier des documents rapidement et avec précision.",
        Ar: "",
        Effet: "+2 dés bonus aux Tests de Falsification ou de modification de documents.",
        Traits: "",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "IMPERIUM, ADMINISTRATUM"
    },
    {
        Id: 45,
        Nom: "Psyconduit",
        Description: "Ces objets varient énormément en apparence. Certains peuvent prendre la forme d'une canne ou d'un bâton, tandis que d'autres peuvent simplement apparaître comme un « porte-bonheur » ou un jeu de Tarot de l'Empereur sortant de l'ordinaire.",
        Ar: "",
        Effet: "+1 dé bonus aux Tests de Maîtrise psychique (Wil).",
        Traits: "",
        Valeur: "3",
        Rareté: "Rare",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 46,
        Nom: "Rations de survie",
        Description: "Aussi nourrissantes que peu appétissantes, les barres, les briques, les poudres et les pâtes qui composent une Ration de survie standard contiennent suffisamment de nutriments pour nourrir un humain adulte pendant une journée.",
        Ar: "",
        Effet: "",
        Traits: "",
        Valeur: "1",
        Rareté: "Courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 47,
        Nom: "Réacteur dorsal",
        Description: "Les roquettes gyrostabilisées d'un Réacteur dorsal projettent l'utilisateur haut dans les airs avec suffisamment d'élan pour fondre sur une cible imprudente.",
        Ar: "",
        Effet: "en utilisant votre Déplacement, vous pouvez voler au double de votre Vitesse avec un Test de Pilotage (A) SD 3, en ignorant n'importe quel terrain. Si vous échouez au Test de Pilotage (A), votre mouvement dévie selon les règles de Dispersion (p. 185). Une Complication déclenche un crash, qui inflige un minimum de 1d3 Stress, plus des dégâts de chute (p. 201).",
        Traits: "",
        Valeur: "7",
        Rareté: "Rare",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 48,
        Nom: "Respirateur",
        Description: "Les Respirateurs prennent de nombreuses formes : une cagoule simple au poly-plastique orange à visière ou un masque facial sophistiqué. Ils utilisent des cartouches d'oxygène remplaçables et des épurateurs internes pour protéger le porteur des atmosphères limitées et des gaz toxiques.",
        Ar: "",
        Effet: "une cartouche d'oxygène fonctionne pendant 2 heures de respiration continue. Lorsque vous résistez à l'aide d'un Respirateur, vous êtes immunisé contre les poisons respirables et les atmosphères toxiques.",
        Traits: "",
        Valeur: "2",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 48,
        Nom: "Respirateur",
        Description: "Les Respirateurs prennent de nombreuses formes : une cagoule simple au poly-plastique orange à visière ou un masque facial sophistiqué. Ils utilisent des cartouches d'oxygène remplaçables et des épurateurs internes pour protéger le porteur des atmosphères limitées et des gaz toxiques.",
        Ar: "",
        Effet: "une cartouche d'oxygène fonctionne pendant 2 heures de respiration continue. Lorsque vous résistez à l'aide d'un Respirateur, vous êtes immunisé contre les poisons respirables et les atmosphères toxiques.",
        Traits: "",
        Valeur: "2",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 49,
        Nom: "Stimm",
        Description: "Un cocktail de drogues de combat ultra-sophistiquées, souvent conservé dans un injecteur à usage unique.",
        Ar: "",
        Effet: "peut être utilisé dans le cadre d'un Test de Medicae (Int) pour restaurer 1d3 + 3 Stress.",
        Traits: "",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "IMPERIUM, RACAILLE"
    },
    {
        Id: 50,
        Nom: "Symbole d'autorité",
        Description: "Un insigne, une bague, un sceau, une rosette, une amulette ou tout autre objet qui peut indiquer que son porteur doit être pris au sérieux par ceux qui connaissent la hiérarchie de sa culture.",
        Ar: "",
        Effet: "+1 dé bonus aux Tests de Commandement (FM) et d'Intimidation (FM) contre des cibles qui devraient respecter votre position.",
        Traits: "",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 51,
        Nom: "Tablette de données",
        Description: "Largement répandue dans tout l'Imperium, la Tablette de données renferme un simple cogitateur capable de contenir de nombreuses informations, qu'il s'agisse de journaux personnels ou de textes hérétiques, en passant par les modèles technologiques collectés par l'Archimage Dominus Belisarius Cawl.",
        Ar: "",
        Effet: "vous pouvez enregistrer sur votre Tablette de données toute information transférable à partir d'un cogitateur, par exemple des cartes locales, des dossiers familiaux ou des registres de manufactorum.",
        Traits: "",
        Valeur: "2",
        Rareté: "Courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 52,
        Nom: "Tablette Monitron",
        Description: "Cette Tablette de données est généralement incorporée dans le brassard ou le gantelet d'une armure. Elle surveille les signes vitaux du porteur et indique sa fréquence cardiaque, ainsi que son état de santé général.",
        Ar: "",
        Effet: "+2 dés bonus aux Tests de Medicae (Int) effectués pour soigner vos blessures.",
        Traits: "",
        Valeur: "4",
        Rareté: "Rare",
        MotsClés: "IMPERIUM, ASTRA MILITARUM"
    },
    {
        Id: 53,
        Nom: "Vêtement",
        Description: "Les vêtements courants prennent la forme de tenues religieuses, d'uniformes ou des combinaisons de protection d'ouvrier. Il est rare que quelqu'un puisse choisir ses vêtements, car ces derniers sont intrinsèquement liés à la mission commune de servir l'Imperium.",
        Ar: "",
        Effet: "les vêtements d'une Rareté plus élevée sont un signe de statut et peuvent accorder de petits bonus dans certains contextes pour des Tests de Compétences sociales (+1 dé bonus pour la Persuasion ou l'Influence, par exemple).",
        Traits: "",
        Valeur: "1",
        Rareté: "Variable",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 54,
        Nom: "Vox",
        Description: "Les technologies de communication sans fil portable sont souvent indispensables pour les opérateurs qui se séparent ou qui doivent faire leur rapport à leurs supérieurs.",
        Ar: "",
        Effet: "",
        Traits: "",
        Valeur: "",
        Rareté: "",
        MotsClés: ""
    },
    {
        Id: 55,
        Nom: "Micro-vox",
        Description: "Assez petits pour tenir confortablement dans un conduit auditif et suffisamment sensibles pour capter la voix du porteur, ces appareils sont souvent utilisés par des agents pour communiquer en chuchotant sur de longues distances afin de coordonner leurs actions.",
        Ar: "",
        Effet: "vous pouvez communiquer avec n'importe qui dans un rayon de 1000 mètres (un kilomètre) possédant une unité vox réglée sur la même fréquence.",
        Traits: "",
        Valeur: "3",
        Rareté: "Peu courant",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 56,
        Nom: "Émetteur Vox",
        Description: "Prenant la forme de sacs à dos bourrés de technologies radio sans fil, ces unités vox fonctionnent sur de grandes distances et sur plusieurs gammes d'ondes en simultané. Elles sont ainsi privilégiées par les commandants sur le champ de bataille et par les assistants des grandes suites impériales.",
        Ar: "",
        Effet: "vous pouvez communiquer avec n'importe qui dans un rayon de 100 000 mètres (100 kilomètres) possédant une unité vox.",
        Traits: "",
        Valeur: "5",
        Rareté: "Rare",
        MotsClés: "[AU CHOIX]"
    },
    {
        Id: 57,
        Nom: "Armure Kroot",
        Description: "À peine plus que des morceaux de métal ficelés ensemble pour protéger les quelques parties vulnérables de la biologie Kroot, cette armure est assemblée avec soin pour s'assurer qu'elle n'entrave pas les mouvements.",
        Ar: "2",
        Effet: "",
        Traits: "-",
        Valeur: "1",
        Rareté: "1",
        MotsClés: "LÉGER, PRIMITIF, KROOT"
    },
    {
        Id: 58,
        Nom: "Armure Énergétique Phobos Mk X",
        Description: "Variante de l'armure énergétique Mark 10 Tacticus optimisée pour la furtivité et la mobilité, l'armure Phobos dispose de servo-moteurs réingénierés pour garantir un mouvement silencieux. Grâce à l'utilisation de plaques de céramite plus petites, l'armure Phobos maximise la mobilité du porteur mais sacrifie une petite quantité de protection.",
        Ar: "4",
        Effet: "",
        Traits: "Alimenté (3)",
        Valeur: "9",
        Rareté: "3",
        MotsClés: "ALIMENTÉ, IMPERIUM, ADEPTUS ASTARTES, PRIMARIS"
    },
    {
        Id: 59,
        Nom: "Armure de Bataille Sicarienne",
        Description: "Installée sur les corps lourdement augmentés des Sicarians, cette armure mince et flexible protège parfaitement les rares parties biologiques d'une killcade sans limiter leur mobilité cruciale.",
        Ar: "4",
        Effet: "",
        Traits: "Champ Énergétique",
        Valeur: "6",
        Rareté: "2",
        MotsClés: "IMPERIUM, ADEPTUS MECHANICUS, SKITARII"
    },
    {
        Id: 60,
        Nom: "Plaque Bullgryn",
        Description: "Le Departmento Munitorum a découvert il y a longtemps que les Ogryns étaient assez forts pour porter des blindages de véhicules recyclés, et utilise depuis lors tout surplus pour équiper les Bullgryns avec ce que l'on appelle la Plaque Bullgryn.",
        Ar: "4",
        Effet: "Cette armure est conçue pour les Ogryns. Les personnages de taille moyenne ne peuvent pas porter d'armure Ogryn.",
        Traits: "-",
        Valeur: "5",
        Rareté: "1",
        MotsClés: "LOURD, IMPERIUM, ASTRA MILITARUM, MILITARUM AUXILLA"
    },
    {
        Id: 61,
        Nom: "Bouclier Brute",
        Description: "Les Bullgryns les plus adaptés au combat rapproché sont équipés de Boucliers Brutes, d'épaisses dalles de plastacier incorporant un champ réflecteur pour s'assurer qu'ils atteignent les lignes de front même sous un feu d'artillerie lourd.",
        Ar: "*3",
        Effet: "Les personnages de taille moyenne traitent les boucliers Ogryns comme ayant le trait Encombrant (2).",
        Traits: "Bouclier",
        Valeur: "5",
        Rareté: "2",
        MotsClés: "LOURD, IMPERIUM, ASTRA MILITARUM, MILITARUM AUXILLA"
    },
    {
        Id: 62,
        Nom: "Bouclier Dalle (Slabshield)",
        Description: "Ces épaisses dalles de plastacier renforcé nécessitent la force d'un Ogryn pour être soulevées, et sont utilisées par les Bullgryns pour former d'impassibles murs de boucliers. La base est pointue pour être plantée dans le sol, et les côtés sont entaillés pour s'emboîter les uns dans les autres. La fente de vision à l'avant est une nécessité de conception, car la plupart des Ogryns manquent de la coordination requise pour avancer tout en bloquant leur propre vision.",
        Ar: "4",
        Effet: "Les personnages de taille moyenne traitent les boucliers Ogryns comme ayant le trait Encombrant (2).",
        Traits: "Encombrant, Bouclier",
        Valeur: "5",
        Rareté: "2",
        MotsClés: "LOURD, IMPERIUM, ASTRA MILITARUM, MILITARUM AUXILLA"
    },
    {
        Id: 63,
        Nom: "Brasero de Feu Sacré",
        Description: "Le zèle ardent de l'Ecclésiarchie rendu réel sous forme de flamme sacrée, enchâssé dans du fer forgé par les souffrances des prêtres ; un Brasero de Feu Sacré ne peut être allumé que par un véritable dévot de l'Empereur, et sa lumière porte une part de Son magnifique pouvoir.",
        Ar: "",
        Effet: "N'importe qui peut tenter d'allumer le brasero (Action de Combat). Une fois allumé, il projette une lumière vive sur 6 mètres. Si un personnage avec au moins 1 point de Foi le manie, tout personnage ayant le mot-clé DÉMON touché par sa lumière est Entravé. En dépensant 1 point de Foi (Action Réflexe), le porteur peut déchaîner les flammes : l'attaque fonctionne comme un Lance-flammes léger (p.219) mais avec +3 ED (+6 ED contre les DÉMONS).",
        Traits: "",
        Valeur: "5",
        Rareté: "4",
        MotsClés: "IMPERIUM, ADEPTUS MINISTORUM, ADEPTA SORORITAS"
    },
    {
        Id: 64,
        Nom: "Casque Diagnostiqueur",
        Description: "Les auto-sens intégrés dans une armure énergétique Astartes sont parfaitement optimisés pour la bataille, mais ceux portés par les Apothicaires sont réglés pour se concentrer sur l'aide médicale.",
        Ar: "",
        Effet: "+1 dé de bonus aux tests de Médicaé (Int) pour détecter et diagnostiquer les maladies, blessures et affections, et pour déterminer la cause du décès. Si la cible est un Adeptus Astartes ou un Primaris, ce bonus passe à +2 dés.",
        Traits: "",
        Valeur: "5",
        Rareté: "3",
        MotsClés: "IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 65,
        Nom: "Excruciateur",
        Description: "Des centaines de fils étiquetés de symboles hexagrammiques inscrutables de l'Inquisition dépassent de ce cube noir compact. Chaque fil, lorsqu'il est correctement appliqué sur la chair d'un individu, s'infiltre dans son système nerveux.",
        Ar: "",
        Effet: "Action de Combat. Inflige 1 dommage de Choc et l'état Entravé 1. Peut être appliqué à plusieurs reprises, infligeant +1 Choc et augmentant l'état Entravé de +1 à chaque utilisation supplémentaire. À la discrétion du MJ, cela peut altérer les émotions de la cible.",
        Traits: "",
        Valeur: "3",
        Rareté: "2",
        MotsClés: "ADEPTUS MINISTORUM, INQUISITION"
    },
    {
        Id: 66,
        Nom: "Haut-parleur de Vox (Laud-Hailer)",
        Description: "Utilisant une technologie vox modifiée, un Haut-parleur peut amplifier une voix pour la rendre audible par une foule entière.",
        Ar: "",
        Effet: "Rend votre voix audible à deux fois la portée normale. Si vous avez un Talent ou une Capacité utilisant votre voix, sa portée est doublée.",
        Traits: "",
        Valeur: "3",
        Rareté: "0",
        MotsClés: "[TOUS]"
    },
    {
        Id: 67,
        Nom: "Lance-grappin",
        Description: "Outil simple utilisé par les forces Primaris en insertion profonde, un lance-grappin peut remonter silencieusement le poids total d'un Primaris Astartes vers une position verticale avantageuse en quelques secondes.",
        Ar: "",
        Effet: "Portée moyenne de 30 mètres. Tiré comme une arme à distance normale sur une surface (ND 3). S'il est réussi, le grappin s'accroche et peut être rétracté pour vous tirer vers cette surface (Action Gratuite).",
        Traits: "",
        Valeur: "4",
        Rareté: "1",
        MotsClés: "IMPERIUM, ADEPTUS ASTARTES, PRIMARIS"
    },
    {
        Id: 68,
        Nom: "Infraviseur",
        Description: "Visière technologique avancée souvent installée dans les augures et les yeux augmentiques de l'Adeptus Mechanicus, l'Infraviseur permet de voir dans une large gamme de spectres simultanément.",
        Ar: "",
        Effet: "Fonctionne comme des Lunettes de Présence (p.239) et permet également de détecter des niveaux élevés de radiation dans votre environnement immédiat.",
        Traits: "",
        Valeur: "5",
        Rareté: "3",
        MotsClés: "IMPERIUM, ADEPTUS MECHANICUS"
    },
    {
        Id: 69,
        Nom: "Narthecium",
        Description: "Pratiquer les premiers secours sur un Space Marine en armure énergétique au milieu de la bataille est difficile, même pour les talentueux Apothicaires Astartes. À cette fin, chaque Apothicaire personnalise son propre Narthecium, un ensemble d'outils médicaux montés au poignet. Bien que chacun soit unique, la plupart des Nartheciums partagent certains outils : une liaison biométrique avec les auto-sens de l'utilisateur, un ensemble de seringues télescopiques, et les jumeaux de terreur que sont la lame-chaîne et la perceuse d'Apothicaire pour percer l'armure, la chair et l'os. Le plus crucial de tous est le Réducteur, un dispositif capable de récupérer rapidement le patrimoine génétique d'un Astartes tombé au combat et de le stocker en toute sécurité en stase.",
        Ar: "",
        Effet: "Vous pouvez effectuer des tests de Médicaé (Int) pour réaliser des chirurgies et soigner autrui sans subir de pénalités de ND liées à la situation actuelle. Lorsque vous effectuez un test de Médicaé (Int) en utilisant un Narthecium dans le cadre d'une Multi-Action en combat, la pénalité de ND est réduite de 2. La plupart des Nartheciums intègrent un Réducteur, qui permet de récupérer le patrimoine génétique d'un Astartes décédé par une Action Simple.",
        Traits: "",
        Valeur: "5",
        Rareté: "2",
        MotsClés: "IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 70,
        Nom: "Bâton d'Annulation (Null Rod)",
        Description: "Forgé dans une obsidienne impénétrable, un Bâton d'Annulation possède la capacité hautement prisée de limiter l'influence insidieuse du Warp dans une zone restreinte.",
        Ar: "",
        Effet: "Tant que vous maniez un Bâton d'Annulation d'une main, tout test de Maîtrise Psychique (Vol) effectué à moins de 18 mètres de vous subit une pénalité de ND de +3.",
        Traits: "",
        Valeur: "5",
        Rareté: "2",
        MotsClés: "IMPERIUM, ADEPTUS SORORITAS"
    },
    {
        Id: 71,
        Nom: "Sceau de Pureté",
        Description: "Les prières et litanies du Culte Impérial sont écrites sur du simple vélin, puis scellées à la cire sur les armes et armures sacrées de Ses guerriers. Ces sceaux de pureté sont décernés aux guerriers héroïques et aux plus purs parmi les fidèles, protégeant leur porteur de l'immonde souillure du Chaos.",
        Ar: "",
        Effet: "Tant que vous n'avez aucun point de Corruption, vous gagnez +1 dé de bonus à tout test de Corruption pour chaque Sceau de Pureté que vous possédez.",
        Traits: "",
        Valeur: "2",
        Rareté: "2",
        MotsClés: "IMPERIUM"
    },
    {
        Id: 72,
        Nom: "Coiffe Psychique",
        Description: "Souvent intégrée à l'armure énergétique d'un Archiviste Astartes, une Coiffe Psychique est reliée directement à l'esprit supérieur de son porteur. Utilisant une technologie cristalline psycho-active arcane, la Coiffe Psychique améliore la capacité du porteur à exercer son influence sur le Warp sans s'exposer indûment à ses innombrables maux, améliorant même sa capacité à annuler la sorcellerie d'autrui.",
        Ar: "",
        Effet: "+1 dé de bonus aux tests de Maîtrise Psychique (Vol). Chaque fois que vous utilisez le pouvoir psychique Abjurer le Sorcier, la ND est égale à 1 + la ND du pouvoir psychique que vous tentez d'abjurer.",
        Traits: "",
        Valeur: "5",
        Rareté: "3",
        MotsClés: "IMPERIUM, ADEPTUS ASTARTES"
    },
    {
        Id: 73,
        Nom: "Simulacrum Imperialis",
        Description: "Intégrant souvent les ossements de saints ou des statues sculptées à leur sainte ressemblance, un Simulacrum Imperialis est brandi sur le champ de bataille, inspirant les dévots à des exploits d'héroïsme.",
        Ar: "",
        Effet: "Tant que vous portez le Simulacrum Imperialis d'au moins une main, vous et tous les alliés fidèles au Culte Impérial à moins de 15 mètres gagnez +2 dés de bonus à tout test de Corruption.",
        Traits: "",
        Valeur: "5",
        Rareté: "4",
        MotsClés: "IMPERIUM, ADEPTUS MINISTORUM, ADEPTA SORORITAS"
    },
    {
        Id: 74,
        Nom: "Heaume Crânien",
        Description: "Le Heaume Crânien grimaçant d'un Chapelain est un terrifiant memento mori, instillant la peur dans le cœur des ennemis malheureux de l'Adeptus Astartes et rappelant aux fidèles de l'Imperium à la fois le sacrifice divin de l'Empereur et leur propre mortalité envers Lui.",
        Ar: "",
        Effet: "En portant un Heaume Crânien, vous gagnez +1 dé de bonus à tous les tests de Commandement (Vol) effectués contre des cibles possédant le mot-clé ADEPTUS ASTARTES.",
        Traits: "",
        Valeur: "4",
        Rareté: "3",
        MotsClés: "IMPERIUM, ADEPTUS ASTARTES"
    }
]