export const ListeAliens = [
    /*"K'tharr*/
    {
        Id: "Ktharr",
        Titre: "K'tharr",
        Description: "Un alien qui se déplace vite, se camoufle et assassine ses ennemies.",
        Chemin: "/Ktharr",
        Icone: "\u{1F419}",
        Details: {
            Force: "12",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "6",
            Sagesse: "6",
            Charisme: "12",
            Protection: "12",
            PointsVie: "20",
            CheminImage: "/Images/CygnusProjects/Aliens/K'Tharr.png",
            ImageWidth: "680px",
            ImageHeight: "680px",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Vision Nocturne : Peut voir parfaitement dans l'obscurité totale.",
                "Camouflage : Peut se camoufler dans le décor pour se fondre dans son environnement (pendant 2 tours).",
                "Sens Acérés : Ses sens sont aiguisés et lui permettent de détecter ses proies à distance (10 cases).",
                "Sang Froid : Le K'tharr ne panique pas, même dans les situations les plus dangereuses.",
                "Agilité Supérieure : Le K'tharr peut effectuer des sauts acrobatiques et escalader des surfaces lisses avec une aisance incroyable.",
                "Régénération : Le K'tharr peut se régénérer, soignant ses blessures mineures et moyennes rapidement (1D4 recharge 3 tours).",
                "Invisibilité Partielle : Peut déformer la lumière autour de lui, le rendant plus difficile à repérer.",
                "Traque d'Ombre : Le K'tharr est plus rapide dans les ombres que dans la lumière.",
                "Vision Thermique : Peut voir la chaleur dégagée par ses proies à travers les murs.",
                "Frappe Ciblée : Il a la capacité d'identifier les points faibles d'un ennemi pour infliger des dégâts critiques sur une seule frappe.",
                "Invisibilité Totale : Le K'tharr peut se rendre totalement invisible pour une courte durée (pendant 3 tours).",
                "Maître de la Furtivité : Le K'tharr est le maître de la furtivité, il ne peut être détecté (sauf en étant proche d'un ennemis, 2 cases).",
                "Mimétisme Vocal : Le K'tharr peut imiter les voix ou les cris d'autres créatures pour attirer une proie ou semer la confusion.",
                "Vitesse Prédatrice : Il peut entrer dans une course fulgurante pour rattraper sa proie ou s'échapper (x2 vitesse pendant 2 tours, recharge 6 tours) .",
                "Instinct de Survie : Il possède un instinct très développé qui lui permet d'anticiper les dangers.",
                "Attaque Furtive : Le K'tharr maîtrise l'art de l'embuscade, infligeant des dégâts supplémentaires lorsqu'il attaque par surprise (x3 dés dégâts)",
                "Création de Pièges : Peut créer des pièges pour ses proies, les immobilisant et les rendant vulnérables (pose de piège filet).",
                "Frappe Foudroyante : Une attaque unique qui peut briser l'armure d'un ennemi, le rendant vulnérable aux attaques (x2 dés dégâts, stun 1 tour, recharge 5 tours).",
                "Démoralisation : La présence du K'tharr peut démoraliser et affaiblir les ennemis, les rendant incapables de se battre en posant des totems avec des restes organiques (à la prédator).",
                "La Chasse Finale (Active) : Le K'tharr entre dans un état de chasse ultime. Il devient totalement indétectable par tous les sens (thermique, sonique, etc.) et peut percevoir la peur de sa proie comme une lumière guide. Dégâts augmentés (x3 D), vitesse augmenté (x3)."
            ],
            Capacites: [
                "",
                "Hurlement de Chasse (Active) : Un hurlement strident qui désoriente et assourdit momentanément les ennemis, les laissant vulnérables à une attaque.",
                "",
                "Camouflage (Passive) : Le K'tharr peut se camoufler dans le décor pour se fondre dans son environnement.",
                "",
                "Pistage Silencieux (Passive) : Le K'tharr peut pister ses proies sans faire de bruit (persoit les traces des ennemis sur ses 3 derniers tours).",
                "",
                "Vision Thermique (Passive) : Le K'tharr peut voir la chaleur dégagée par ses proies.",
                "",
                "Invisibilité Totale (Active) : Le K'tharr peut se rendre totalement invisible pour une courte durée (3 tours).",
                "",
                "Maître du Sang Froid (Passive) : Le K'tharr est immunisé aux attaques psychologiques.",
                "",
                "Monarque de la Nuit (Passive) : Le K'tharr est plus puissant la nuit (nuit sur des planètes, fonctionne pas dans l'espace).",
                "",
                "Téléportation (Active) : Le K'tharr peut se téléporter sur de courtes distances (5 cases).",
                "",
                "Création d'Illusion (Active) : Le K'tharr peut créer une illusion qui trompe ses proies.",
                "",
                "Marque de la Proie (Active) : Le K'tharr peut marquer une cible (à moins de 4 cases de lui). Tant que la marque persiste, il peut la localiser et la suivre, peu importe où elle se cache."
            ]
        }
    },
    /*Causticon*/
    {
        Id: "Causticon",
        Titre: "Causticon",
        Description: "Un alien qui contrôle l'acide pour en faire une arme létale.",
        Chemin: "/Causticon",
        Icone: "\u{1F9EA}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "6",
            Charisme: "12",
            Protection: "4",
            PointsVie: "35",
            CheminImage: "/Images/CygnusProjects/Aliens/Causticon.png",
            ImageWidth: "310px",
            ImageHeight: "413,5px",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Jet d'Acide Basique : Peut cracher un jet d'acide corrosif capable de dissoudre des matériaux légers (1D6 dégâts).",
                "Absorption d'Énergie Thermique : Peut absorber l'énergie thermique pour se soigner et se régénérer.",
                "Sang Acide : Son sang est acide et peut blesser quiconque l'attaque au corps à corps.",
                "Piège Acide : Peut créer un piège d'acide qui se déclenche lorsque quelqu'un passe à proximité, le recouvrant d'une substance corrosive (1D4 dégâts, 3 tours de recharge).",
                "Jet d'Acide Concentré : Peut projeter un jet d'acide concentré, capable de dissoudre des matériaux plus résistants (1D8 dagâts).",
                "Mur de Vapeur : Peut expulser une brume acide qui obstrue la vue sur 5 cases de long max et 1 case de large et inflige des dégâts mineurs à ceux qui la traversent 1D4 (recharge en 7 tours).",
                "Champ de Corrosion : Peut créer un champ de corrosion autour de lui, endommageant les ennemis à proximité (2D4 dégâts au CAC, 1D4 à 2-3 cases).",
                "Filaments de Soie Acide : Le Causticon peut projeter des filaments d'acide collants, immobilisant ses ennemis faisant 2 dégâts.",
                "Bombe Acide : Le Causticon crache un projectile d'acide concentré qui explose à l'impact, couvrant une zone d'une substance corrosive qui blesse quiconque s'y trouve.",
                "Maître de la Corrosion : Peut dissoudre n'importe quel matériau.",
                "Transfusion Corrosive : Peut injecter une substance acide directement dans la circulation sanguine d'une victime, provoquant des dégâts internes sur la durée (1D4 tous les tours jusqu'à la mort ou remède, recharge en 15 tours).",
                "Bombe à Retardement Acide : Le Causticon peut poser une bombe acide qui explose après un certain temps (2 tours après, recharge en 5 tours).",
                "Déphasage Acide : Le Causticon peut se dissoudre et se reformer ailleurs se déplace 3 fois plus vite mais prend 2 fois plus de dégâts.",
                "",
                "Perforation Rapide : Peut concentrer un jet d'acide à ultra-haute pression pour percer instantanément une petite surface d'armure (ignore les blindages et protections).",
                "",
                "Création d'Ouverture Ultime : Le Causticon peut créer une ouverture dans un mur en 2 fois moins de tour.",
                "",
                "",
                "Création de Vie : Le Causticon peut créer une forme de vie à partir de l'acide (un minion d'acide), prend 3 tours pour qu'il sorte de la flaque d'acide."
            ],
            Capacites: [
                "",
                "Jet d'Acide Concentré (Active) : Peut projeter un jet d'acide très corrosif sur une cible pour l'endommager.",
                "",
                "Sol Acide (Active) : Le Causticon peut recouvrir le sol d'une flaque d'acide visqueuse. Les ennemis qui y marchent subissent des dégâts et sont ralentis.",
                "",
                "Création de Passage (Active) : Le Causticon peut créer une ouverture dans un mur standars ou une porte standars (prend 2 tours).",
                "",
                "Démoralisation (Passif) : L'apparence du Causticon est si terrifiante qu'elle démoralise les ennemis.",
                "",
                "Champ de Corrosion (Active) : Le Causticon peut créer un champ de corrosion qui endommage les ennemis à proximité (un cercle de 3 cases, recharge en 5 tours).",
                "",
                "Bouclier Acide (Active) : Le Causticon peut créer un bouclier d'acide qui le protège des attaques (15 points de dégâts, recharge en 10 tours).",
                "",
                "Création de Passage (Active) : Le Causticon peut créer une ouverture dans un mur lourd ou une porte lourde (prend 4 tours).",
                "",
                "Toxine Acide (Active) : Le Causticon peut créer une toxine acide qui peut tuer une personne en quelques secondes.",
                "",
                "Vague de Corrosion (Active) : Le Causticon peut libérer une vague de corrosion qui détruit tout sur son passage (3 cases de large, 6 de long [progressif sur 3 tours] recharge en 10 tours après la fin de la vague).",
                "",
                "Détection Acide (Passif) : produit un liquide acide en continue qui recouvre les cases où il se déplace, quand quelqu'un ou quelque chose se déplace dessus Causticon est averti (comme une toile d'araignée)"
            ]
        }
    },
    /*Genitrix*/
    {
        Id: "Genitrix",
        Titre: "Genitrix",
        Description: "Un alien qui pond des oeufs et qui contrôle ses enfants pour créer une armée redoutable.",
        Chemin: "/Genitrix",
        Icone: "\u{1F95A}",
        Details: {
            Force: "12",
            Dextérité: "6",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "12",
            Charisme: "6",
            Protection: "10",
            PointsVie: "25",
            CheminImage: "/Images/CygnusProjects/Aliens/Genitrix.png",
            ImageWidth: "800px",
            ImageHeight: "800px",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Ponte Basique : Peut pondre un œuf qui éclora après plusieurs tours (dans 3 tours, recharge en 2 tours).",
                "Connexion Psionique : Établit un lien mental de base avec sa progéniture pour percevoir leur emplacement.",
                "Canibalisme Matriciel : la Génitrixpeut se nourir de ses enfants pour se régénérer complètement",
                "Éclosion Accélérée : Peut mentalement accélérer le processus d'éclosion d'un œuf en concentrant son énergie dessus (reste à côté de son oeuf pendant 1 tour).",
                "Contrôle des Mouvements : Peut diriger les mouvements de sa progéniture en leur envoyant des signaux psychiques.",
                "Évolution Rapide : Les enfants de la Genetrix évoluent plus vite que la normale, devenant des adultes.",
                "Cri de la Mère : Peut émettre un cri qui commande sa progéniture et la rend plus agressive (+1D dégâts pendant 2 tours).",
                "Lien de Douleur : Quand un de ses enfants meurt, la Genetrix ressent une douleur, mais peut l'utiliser pour se renforcer (donne 3 points de protections).",
                "Création de Nids : Peut créer des nids pour ses enfants, qui leur donnent un bonus de régénération (1D4 par tour).",
                "Résilience de la Mère : La Genetrix est plus résistante aux dégâts.",
                "Mort de la Mère : Lorsque le Genetrix meurt, ses enfants se déchaînent, attaquant tout sans réfléchir (x2 dégâts, x2 vitesse, pendant 2 tours avant de mourir).",
                "Régénération de la Mère : La Genetrix peut se régénérer, soignant ses blessures mineures et moyennes rapidement.",
                "Ponte d'Œufs Avancée : Le Genetrix peut pondre un œuf qui éclosera instantanément.",
                "",
                "Régénération Ultime : La Genetrix peut régénérer n'importe quelle partie de son corps, même s'il est gravement blessé.",
                "",
                "Sacrifice de la Mère : Le Genetrix peut se sacrifier pour faire en sorte que ses enfants deviennent plus forts (x3 dégâts, x2 vitesse, pendant 5 tours).",
                "",
                "",
                "Ponte d'Œufs Ultime : Le Genetrix peut pondre plusieurs œufs en un seul tour (1D4, rechage en 5 tours)."
            ],
            Capacites: [
                "",
                "Nidification (Active) : La Génitrix se pose pendant 3 tours pour se poser et commencer à pondre en continue (1 oeuf par tour par salle complète), les murs et le sol commence petit à petit à changer de forme et de couleur, cette transformation se propage d'une case par tour (les ennemis qui sont dans cette zone ont 2 fois moins de vitesse, arrondi au supérieur)",
                "",
                "Évolution Rapide (Passive) : Les enfants du Genetrix évoluent plus vite.",
                "",
                "Mutation des Enfants (Active) : Le Genetrix peut muter sa progéniture.",
                "",
                "Résilience de la Mère (Passive) : Le Genetrix est plus résistant aux dégâts.",
                "",
                "Mutation d'Adulte (Active) : Le Genetrix peut muter sa progéniture pour qu'elle devienne adulte instantanément.",
                "",
                "Régénération de la Mère (Passive) : Le Genetrix peut se régénérer, soignant ses blessures sans dévorer sa progéniture.",
                "",
                "Bouclier de Nidation (Active) : La Genetrix peut sécréter une substance cristalline qui durcit instantanément, créant une barrière protectrice autour d'elle ou de ses œufs.",
                "",
                "Lien de Rage (Active) : Peut se concentrer pour imprégner sa progéniture d'une rage instinctive, augmentant leur vitesse et leur puissance d'attaque pendant un court instant.",
                "",
                "Essaim de Drones (Active) : Produit un petit essaim de créatures volantes qui harcèlent les ennemis, créant une diversion.",
                "",
                "Fusion (Active) : La Genetrix peut fusionner deux de ses enfants pour en faire un plus puissant, plus grand et plus dangereux (points de vie = addition des PV de tous les enfants; protection = addition de la protection de tous les enfants)."
            ],
            Genitrix: {
                Evolution1: "Quand un oeuf apparaît, il prend 2 tours avant d'éclore et donner un enfant",
                Evolution2: "Quand un enfant apparaît, il prend 4 tous avant de devenir jeune",
                Evolution3: "Quand un jeune appareît, il prend 6 tours avant de devenir adulte",
                Type_Evolution: [
                    {
                        Nom: "Oeuf", 
                        CheminImage: "/Images/CygnusProjects/Aliens/Oeuf.png",
                        ImageWidth: "400px",
                        ImageHeight: "447px",
                        Protection: "0",
                        PointsVie: "1"
                    },
                    {
                        Nom: "Enfant",
                        CheminImage: "/Images/CygnusProjects/Aliens/Enfant.png",
                        ImageWidth: "200px",
                        ImageHeight: "200px",
                        Protection: "0",
                        PointsVie: "10"
                    },
                    {
                        Nom: "Jeune",
                        CheminImage: "/Images/CygnusProjects/Aliens/Jeune.png",
                        ImageWidth: "230px",
                        ImageHeight: "230px",
                        Protection: "3",
                        PointsVie: "15"
                    },
                    {
                        Nom: "Adulte",
                        CheminImage: "/Images/CygnusProjects/Aliens/Adulte.png",
                        ImageWidth: "800px",
                        ImageHeight: "474,5px",
                        Protection: "6",
                        PointsVie: "20"
                    }
                ]
            }
        }
    },
    /*Necrosia*/
    {
        Id: "Necrosia",
        Titre: "Necrosia",
        Description: "Un alien qui répend des larve pour controler des corps comme des zombies.",
        Chemin: "/Necrosia",
        Icone: "\u{1F9DF}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "6",
            Charisme: "12",
            Protection: "6",
            PointsVie: "30",
            CheminImage: "/Images/CygnusProjects/Aliens/Necrosia.png",
            ImageWidth: "400px",
            ImageHeight: "500px",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Infection Basique : La Necrosia peut infecter un cadavre, l'animant en tant que \"zombie\" sous son contrôle (1 par tour).",
                "Lien Psionique : Établit une connexion mentale de base avec ses zombies pour percevoir leur emplacement et leurs actions.",
                "Parasite Cérébral : Le parasite implanté dans la nuque des zombies les rend extrêmement agressifs et résilients à la douleur.",
                "Sonde Parasitaire : Peut expulser un petit parasite volant qui agit comme un drone de reconnaissance, capable de repérer les ennemis et de revenir avec l'information.",
                "Contrôle de la Horde : Peut donner des ordres de base à sa horde, comme attaquer ou se défendre.",
                "",
                "Cri de Panique : Émet un cri qui peut faire paniquer les ennemis, les faisant fuir.",
                "",
                "Infection Avancée : Un zombie peut infecter un cadavre (recharge 2 tours).",
                "",
                "Résilience de la Horde : Les zombies de la Necrosia sont plus résistants aux dégâts.",
                "",
                "Infection Ultime : Un zombie peut infecter un cadavre plus rapidement (recharge 1 tour).",
                "",
                "Essaim de Drones : Peut créer une nuée de parasites volants qui harcèlent et distraient les ennemis, les laissant vulnérables aux attaques de la horde.",
                "",
                "Transfert de Conscience : Le Necrosia peut transférer sa conscience dans le corps d'un zombie, lui permettant de se déplacer et d'attaquer sans risquer son propre corps.",
                "",
                "",
                "Fusion de la Nécropole (Active) : La Necrosia utilise une puissante impulsion psionique pour regrouper tous ses zombies et les faire fusionner. Ces corps se tordent et se combinent en une seule entité grotesque, massive et incroyablement puissante, directement sous son contrôle. Cette monstruosité est un véritable \"golem de chair\" doté d'une force dévastatrice, d'une résilience hors du commun (4D4 dégâts, 20 protections)"
            ],
            Capacites: [
                "",
                "Résistance à la Douleur (Passive) : La Necrosia peut ignorer les dégâts, la rendant plus difficile à tuer.",
                "",
                "Assimilation de la Horde (Passive) : La Necrosia peut consommer les zombies de sa horde pour se soigner et se renforcer (1D4 par zombie).",
                "",
                "Cri de la Horde (Active) : Peut émettre un cri pour faire converger toute sa horde sur elle (les zombies gagnent x3 vitesse).",
                "",
                "Mutation des Zombies (Active) : Le Genetrix peut muter sa horde (2 zombies pour en faire un colosse 2D dégâts, x2 protection).",
                "",
                "Bombe Parasitaire (Active) : La Necrosia peut lancer un projectile organique qui explose à l'impact, libérant des parasites capables d'infecter plusieurs cadavres en une seule fois.",
                "",
                "Résilience de la Horde (Passive) : Les zombies sont plus résistants aux dégâts.",
                "",
                "Régénération de la Horde (Passive) : Les zombies peuvent se régénérer, soignant leurs blessures (1D4, recharge 4 tours).",
                "",
                "Sacrifice de la Horde (Active) : Le Necrosia peut sacrifier un zombie pour se soigner (1D6 HP rendu).",
                "",
                "Sacrifice de la Horde : Le Necrosia peut se sacrifier pour faire en sorte que sa horde devienne plus forte.",
                "",
                "Lien de Mort (Passif) : La Necrosia peut lier sa vie à celle de ses zombies. Tant qu'il y a un zombie en vie, la Necrosia ne peut pas mourir."
            ],
            Necrosia: {
                Larve: {
                    Nom: "Larve",
                    CheminImage: "/Images/CygnusProjects/Aliens/Larve.png",
                    ImageWidth: "450px",
                    ImageHeight: "273,5px",
                    Protection: "0",
                    PointsVie: "1"
                }
            }
        } 
    },
    /*Phylactère*/
    {
        Id: "Phylactere",
        Titre: "Phylactère",
        Description: "Un alien qui possède plusieurs corps et qui peut en changer n'importe quand.",
        Chemin: "/Phylactere",
        Icone: "\u{1F916}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "12",
            Intelligence: "12",
            Sagesse: "6",
            Charisme: "6",
            Protection: "0",
            PointsVie: "1",
            CheminImage: "",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Bouclier de Fortune : Le réceptacle peut déployer un petit bouclier d'énergie sur son avant-bras gauche, qui peut dévier les tirs et les attaques de mêlée.",
                "Surcharge du Canon : Le Phylactère peut surcharger le canon laser pour un tir unique et puissant, infligeant des dégâts accrus (3D6) en contrepartie d'un temps de rechargement.",
                "Dard Osseux Rétractable : Une lame énergétique rétractable peut jaillir du poignet droite du réceptacle, offrant une option de mêlée rapide et mortelle.",
                "Invisibilité : Le réceptacle peut devenir invisible pour une courte durée, ce qui lui permet de se cacher ou de surprendre ses ennemis (pendant 2 tours, recharge 5 tours).",
                "Grappin : Le réceptacle peut tirer un grappin qui lui permet de se déplacer rapidement ou d'attirer des ennemis (bras gauche).",
                "Vortex de Glace : Le réceptacle peut créer un tourbillon de glace qui piège les ennemis à l'intérieur, les blessant et les ralentissant.",
                "Bras de Feu : L'hôte peut surcharger son bras de feu pour créer un jet de flammes continu, capable d'infliger des dégâts sur la durée et de couvrir une zone.",
                "Mur de Flammes : L'Anthem peut créer une barrière verticale de flammes qui bloque les ennemis, infligeant des dégâts sur la durée à quiconque tente de la traverser.",
                "Tempête de Grêle : L'hôte peut générer au-dessus d'une zone ciblée une tempête qui fait pleuvoir de gros morceaux de glace, blessant et désorientant les ennemis.",
                "Fusion Élémentaire : L'Anthem peut combiner les énergies de ses deux bras pour créer un projectile qui fusionne le feu et la glace. Ce projectile inflige des dégâts massifs à l'impact et ralentis sur une vaste zone",
                "Canon à Fragmentation : Le gros canon de l'avant-bras peut tirer des obus qui explosent à l'impact, infligeant des dégâts de zone et désorientant les ennemis dans un sayon d'une case autour de l'impact.",
                "Pistolet à Plasma : Le petit pistolet laser est remplacé par un pistolet à plasma, qui inflige des dégâts massifs et peut faire fondre les armures ennemies.",
                "Système de Visée Automatique : Le réceptacle peut verrouiller une cible, garantissant que tous les tirs du canon sont d'une précision mortelle pendant une courte période.",
                "Hache énergétique : remplace le couteau par une hache énergétique",
                "Canon de l'Apocalypse : L'hôte peut surcharger son canon pour tirer un projectile à énergie massive. Ce projectile explose à l'impact, libérant une onde de choc dévastatrice qui repousse tout une zone (4 cases autour de l'impact, recharge en 15 tours, canon refroidis en 3 tours).",
                "Lance-flammes à Plasma : Le lance-flammes est amélioré pour tirer des jets de plasma, qui colle le sol et les murs, il cole aussi les ennemis pendant 1 tour (malus pendant ce tour).",
                "Marteau Sismique : Le marteau du Dreadnought est si puissant qu'il peut créer un tremblement de terre, qui repousse les ennemis dans un rayon de 1 case de l'impact.",
                "Mitrailleuse à Canon Rotatif : Le canon peut être remplacé par un minigun à haute cadence de tir, capable de saturer une zone de balles.",
                "Champ de Force : Un bouclier personnel qui peut protéger le Dreadnought des attaques (30 protections).",
                "Singularité Chronomancique : créer une distortion spation-temporelle qui ralenti les ennemis (vitesse /3, actions /3), il accélère les alliés (vitesse x3, x3 actions), dans une zone de 7 cases autour du réceptacle (lancer cette compétence détruira tous les réceptacles dans la zone), se termine 4 tours plus tard et se recharge en 20 tours",
            ],
            Capacites: [
                "",
                "Transfert d'Âme Basique : L'âme peut sortir de son orbe et se déplacer rapidement.",
                "",
                "Rapidité de l'Âme : L'âme se déplace très vite et peut parcourir de grandes distances (x2 vitesse).",
                "",
                "Surcharge de l'Âme : L'âme peut surcharger le corps de son hôte, lui donnant plus de force et de résistance (2D dégâts, x2 résistance mais explose dans 2 tours).",
                "",
                "Transfert de secours (Passive) : Le Phylactère peut transférer son âme juste avant que son receptacle ne soit détruit.",
                "",
                "Maîtrise du Transfert : L'âme peut transférer instantanément et sans risque (dans un rayon de 6 cases).",
                "",
                "Régénération de l'Âme : Un receptacle peut se régénérer, se soignant des blessures et des dégâts qu'il subit, uniquement hors combat (1D4 par tour).",
                "",
                "Invisibilité Éthérée (Active) : L'utilisateur peut se rendre invisible et devenir intouchable, se déplaçant à travers les objets solides et les murs fin.",
                "",
                "Champ de Force Impénétrable (Active) : Le réceptacle déploie un champ d'énergie d'une puissance colossale. Ce bouclier est capable de dévier et d'absorber tous les types de dégâts, qu'ils soient physiques, énergétiques ou psychiques. Il peut être utilisé pour protéger l'utilisateur et ses alliés, créant une barrière temporairement invulnérable. Recouvre toute la largeur d'une mièce ou d'un couloir (maximum 5 cases) pendant 1 tous (recharge en 15 tours)",
                "",
                "Téléportation (Active) : L'utilisateur peut se téléporter sur de courtes distances, ce qui lui permet d'esquiver les attaques et d'attaquer ses ennemis par surprise (dans un rayon de 5 cases, recharge en 10 tours).",
                "",
                "Régénération Absolue (Passive) : Le receptacle se régénère instantanément à un niveau cellulaire. Les blessures, même mortelles, se referment en une fraction de seconde, rendant son porteur pratiquement invincible (pendant 1 tours, recharge en 20 tours)."
            ],
            Phylactere: {
                PointsReceptacle1: "1",
                PointsReceptacle2: "1",
                PointsReceptacle3: "1",
                PointsReceptacle4: "1",
                PointsReceptacle5: "1",
                PointsReceptacle6: "2",
                PointsReceptacle7: "2",
                PointsReceptacle8: "2",
                PointsReceptacle9: "2",
                PointsReceptacle10: "2",
                PointsReceptacle11: "3",
                PointsReceptacle12: "3",
                PointsReceptacle13: "3",
                PointsReceptacle14: "3",
                PointsReceptacle15: "3",
                PointsReceptacle16: "4",
                PointsReceptacle17: "4",
                PointsReceptacle18: "4",
                PointsReceptacle19: "5",
                PointsReceptacle20: "6",
                Receptacle: [
                    {
                        Nom: "Normal",
                        Protection: "3",
                        PointsVie: "20",
                        Niveau: "1",
                        CheminImage: "/Images/CygnusProjects/Aliens/Phylactère type 1.png",
                        ImageWidth: "368px",
                        ImageHeight: "585,5px",
                        Details: "1,75m, humanoïde, petit cannon laser dans l'avant bras droit (1D6 dégâts)"
                    },
                    {
                        Nom: "Anthem",
                        Protection: "6",
                        PointsVie: "25",
                        Niveau: "6",
                        CheminImage: "/Images/CygnusProjects/Aliens/Phylactère type 2.png",
                        ImageWidth: "368px",
                        ImageHeight: "580,5px",
                        Details: "2,2m, humanoïde, levitation, bras droit \"invoque du feu\" (boule de feu), bras droit \"invoque de la glace\" (pique de glace, vitesse /2)"
                    },
                    {
                        Nom: "Space Marine",
                        Protection: "9",
                        PointsVie: "30",
                        Niveau: "11",
                        CheminImage: "/Images/CygnusProjects/Aliens/Phylactère type 3.png",
                        ImageWidth: "282px",
                        ImageHeight: "282px",
                        Details: "3m, humanoïde, lourd, gros canon dans le bras gauche (à la cobra), petit pistolet ou couteau laser pour la main droite"
                    },
                    {
                        Nom: "Dreadnought",
                        Protection: "12",
                        PointsVie: "35",
                        Niveau: "16",
                        CheminImage: "/Images/CygnusProjects/Aliens/Phylactère type 4.png",
                        ImageWidth: "300px",
                        ImageHeight: "660px",
                        Details: "4m, mini lance missile sur chaque épaule, lance flamme ou mitrailleuse bras gauche, marteau ou main grapin bras droit"
                    }
                ]
            }
        }
    },
    /*Skarr-Lyk*/
    {
        Id: "SkarrLyk",
        Titre: "Skarr-Lyk",
        Description: "Un alien qui lacère ses ennemies avec ses longues griffes.",
        Chemin: "/SkarrLyk",
        Icone: "\u{1F480}",
        Details: {
            Force: "12",
            Dextérité: "12",
            Constitution: "12",
            Intelligence: "6",
            Sagesse: "6",
            Charisme: "6",
            Protection: "6",
            PointsVie: "30",
            CheminImage: "/Images/CygnusProjects/Aliens/Skarr-Lyk.png",
            ImageWidth: "368px",
            ImageHeight: "398,5px",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Agilité Basique : Peut se déplacer avec agilité dans les environnements verticaux.",
                "Sens Aigus : Développe une capacité de vision nocturne et un odorat très développé.",
                "Course Murale : Peut courir sur les murs et les plafonds sur de courtes distances (3 cases max, 4 tours de recharge).",
                "Dislocation Articulaire : Capable de disloquer ses articulations pour se faufiler dans des endroits très étroits (plus étroits que les conduits).",
                "Exosquelette Acide : L'exosquelette du Skarr-Lyk peut libérer une petite quantité d'acide pour se protéger des attaques de mêlée.",
                "Morsure Mortelle : La morsure du Skarr-Lyk est si puissante qu'elle peut briser des os et des armures.",
                "Perception Sonique : Utilise l'écholocation pour se repérer dans les ténèbres les plus complètes.",
                "Régénération : Le Skarr-Lyk peut se régénérer, soignant ses blessures mineures et moyennes rapidement.",
                "Camouflage Biologique : Le Skarr-Lyk peut changer la pigmentation de sa peau pour se fondre dans son environnement.",
                "",
                "Résistance Acide : La peau du Skarr-Lyk est plus résistante aux attaques acides.",
                "",
                "Fureur de la Bête : Le Skarr-Lyk entre dans une rage qui augmente sa vitesse de 50% et sa force de 25% pendant 3 tours (15 tours de recharge).",
                "",
                "Fusion de l'Ombre : Le Skarr-Lyk peut se fondre dans l'ombre et disparaître.",
                "",
                "Régénération Ultime : Le Skarr-Lyk peut régénérer n'importe quelle partie de son corps, même s'il est gravement blessé (immobile pendant 5 tours).",
                "",
                "",
                "Invisibilité Partielle : Le Skarr-Lyk peut déformer la lumière autour de lui, le rendant plus difficile à repérer."
            ],
            Capacites: [
                "",
                "Griffes Rétractables (Active) : Le Skarr-Lyk peut sortir ses griffes et les rétracter à volonté (griffes sortient x2 dégâts).",
                "",
                "Passage dans les Conduits (Passive) : Le Skarr-Lyk peut se faufiler dans des conduits et des tuyaux.",
                "",
                "Queue Lancière (Active) : Le Skarr-Lyk peut utiliser sa queue comme une lance.",
                "",
                "Bond Predator (Active) : Le Skarr-Lyk peut bondir sur ses proies depuis le haut, les surprenant et les étourdissant (pendant 1 tour).",
                "",
                "Déchiquetage (Active) : Le Skarr-Lyk peut effectuer une série d'attaques rapides et violentes avec ses griffes, lacérant sa cible et lui infligeant des dégâts supplémentaires (3 attaque; prend en compte le statut des griffes).",
                "",
                "Perception Sonique (Passive) : Le Skarr-Lyk peut se repérer dans les ténèbres les plus complètes.",
                "",
                "Exosquelette Renforcé (Passive) : L'exosquelette du Skarr-Lyk est plus résistant aux dégâts physiques.",
                "",
                "Régénération Acide (Passive) : Le Skarr-Lyk peut se soigner plus rapidement des attaques acides.",
                "",
                "Cri de la Bête (Active) : Le Skarr-Lyk peut émettre un cri qui désoriente et étourdit les ennemis.",
                "",
                "Monarque de l'Ombre (Passive) : Le Skarr-Lyk est le maître des ombres, il ne peut être détecté et ses actions sont impossibles à anticiper."
            ]
        }
    },
    /*Vaz-Thun*/
    {
        Id: "VazThun",
        Titre: "Vaz-Thun",
        Description: "Un alien qui utilise ses capacitées psychiques pour s'attaquer à ses ennemies.",
        Chemin: "/VazThun",
        Icone: "\u{1F92F}",
        Details: {
            Force: "6",
            Dextérité: "6",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "12",
            Charisme: "12",
            Protection: "0",
            PointsVie: "35",
            CheminImage: "/Images/CygnusProjects/Aliens/Vaz-Thun.png",
            ImageWidth: "367,5px",
            ImageHeight: "256px",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Création d'Illusion Basique : Peut créer des illusions sonores et visuelles simples pour distraire ou tromper.",
                "Perception Psychique : Peut percevoir les émotions et les pensées de base des autres êtres.",
                "Projection d'Illusion Visuelle : Maîtrise les illusions visuelles complexes, capables de duper l'œil.",
                "Création de Balise : Le Vaz-Thun peut créer une balise de téléportation à volonté (5 tours entre chaque balise) et s'y téléporter.",
                "Lévitation : Peut se déplacer par lévitation, ce qui lui permet de se déplacer silencieusement et de surprendre ses ennemis (sur 15 cases, recharge 3 tours).",
                "Manipulation de l'Illusion : Peut faire bouger ses illusions pour les rendre plus réalistes et convaincantes.",
                "Création de Cauchemar : Peut créer un cauchemar pour un ennemi, le rendant incapable de se battre.",
                "Création de Balise : Le Vaz-Thun peut créer une balise de téléportation qui peut être utilisée par ses alliés.",
                "Maîtrise de la Projection Psychique : Peut projeter sa conscience pour une période prolongée, en gardant un lien avec son corps.",
                "Miroir d'Illusion : Peut créer une illusion qui réfléchit les attaques, les renvoyant à l'envoyeur.",
                "Contrôle Mental Basique : Peut contrôler l'esprit d'un ennemi pour le rendre inoffensif.",
                "Téléportation Avancée : Peut se téléporter vers n'importe quel point.",
                "Création de Trou Noir : Peut créer un petit trou noir qui aspire les ennemis et les objets.",
                "Maîtrise de la Téléportation : Le Vaz-Thun peut se téléporter à travers n'importe quel obstacle.",
                "",
                "Terreur : Peut émettre une aura de terreur qui effraie les ennemis et les rend incapables d'attaquer.",
                "",
                "Création d'Illusion Ultime : Peut créer une illusion si réaliste que les ennemis ne peuvent pas la différencier de la réalité.",
                "",
                "Distorsion Spatiale Basique : Peut tordre l'espace pour rendre les ennemis plus lents ou les faire disparaître."
            ],
            Capacites: [
                "",
                "Illusion Visuelle (Active) : Peut créer une illusion visuelle complexe pour duper.",
                "",
                "Téléportation (Active) : Peut se téléporter vers une balise de téléportation et automatiquement recréer une balise (15 tours de recharge).",
                "",
                "Projection Psychique (Active) : Le Vaz-Thun peut projeter sa conscience hors de son corps pour explorer.",
                "",
                "Désorientation Sensorielle (Active) : Le Vaz-Thun émet une impulsion psychique qui brouille les sens (vue, ouïe, équilibre) dans une ligne droite de 5 cases de long et 1 de large, les rendant incapables de se défendre.",
                "",
                "Manipulation de la Matière (Active) : Le Vaz-Thun peut modifier la composition d'un objet inorganique, le rendant plus solide ou plus fragile, voire le dissolvant.",
                "",
                "Réplication (Active) : Le Vaz-Thun peut créer une réplique non-tangible de lui-même. Cette copie fantomatique peut passer à travers les objets et les murs pour explorer ou sonder l'environnement sans risque.",
                "",
                "Miroir d'Illusion (Active) : Le Vaz-Thun peut créer une illusion qui réfléchit les attaques pendant 1 tour (recharge en 7 tours).",
                "",
                "Contrôle Mental (Active) : Le Vaz-Thun peut contrôler l'esprit d'un ennemi pendant 1 tour (recharge en 5 tours).",
                "",
                "Chant Funeste (Active) : Le Vaz-Thun émet un chant psychique qui cible l'esprit d'un ennemi, le submergeant de visions de fin des temps et de destruction cosmique, le rendant mentalement brisé et incapable de se battre.",
                "",
                "Déferlement d'Horreur : Le Vaz-Thun peut libérer une puissante vague d'énergie psychique qui inflige des dégâts massifs et déstabilise les ennemis dans une zone."
            ]
        }
    }
];