export const ListeOperateurs = [
    /*Droniste*/
    {
        Id: "Droniste",
        Titre: "Droniste",
        Description: "Un éclaireur qui utilise des drônes pour explorer et s'attaquer aux différentes menaces.",
        Chemin: "/Droniste",
        Icone: "\u{1F681}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "12",
            Charisme: "6",
            Protection: "3",
            PointsVie: "15",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Droniste.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Vision Standard.",
                "Module Auto - réparation(redonne 1D4 HP, activable tous les 5 tours)",
                "Vision Nocturne(infrarouge).",
                "Revêtement silencieux(réduit la distance de détection sonor)",
                "Vision Thermique.",
                "Module Sonar / Écho - localisation(détection à travers murs fins dans un rayon de 6 cases).",
                "Module de Manipulation Léger(bras articulé qui peut prendredéplacer des petits objets, appuyer sur les boutons, ...).",
                "Arme non létale(Type Taser, réduits les déplacements).",
                "Module de Projection Holographique(projète un holograme d'un allié)",
                "Filet de Capture(léger, non létal, projète un filet pouvant capturer ou limiter les déplacements).",
                "Arme Létale Légère(Type Micro - Laser fait 1D4 dégâts).",
                "Module de Dégagement(propulseur pour passer des obstacles utilisable tous les 10 tours, permet de sauter à 1 mètre de haut).",
                "Module Lanceur de grenade(fumigène, flash, lacrymo, prend 1 tour à se recharger, peut transporter 4 grenades)",
                "Système de Camouflage Optique(limité, permet d'être camouflé à longue et moyenne distance).",
                "Module de déploiement de capteurs passifs(place des capteurs qui sonnent quand quelque chose passe à côté, 6 capteurs, 2 tours avant d'en poser un autre)",
                "Arme Intermédiaire(Type Arme a feu standars, 1D6 dégâts).",
                "Émetteur d'Onde de Choc (non létale, pour désorienter la cible, immobilise la cible pendant 1 tour).",
                "Module d'injecteur de nano-bots (divise par 2 les mouvements et les dégâts de la cible pendant 5 tours, utilisable une fois)",
                "Arme Létale Avancée(Type Lance - Plasma, 1D8 dégâts).",
                "Module d'auto-destruction (explosif léger, fait 2d6 dégâts dans un rayon de 2 cases, explose au prochain tour)."
            ],
            Capacites: [
                "",
                "Déplacement Discret du Drone : Le drone fait moins de bruit pendant 2 tours, prend 15 tours pour se recharger",
                "",
                "Cartographie Rapide : Le drone peut cartographier une zone de 6 cases autour de lui, prend 1 tour (immobile), se recharge en 10 tours",
                "",
                "Retour Drone Sécurisé : Le drone peut tenter de revenir à l'éclaireur automatiquement, prend 20 tours pour se recharger",
                "",
                "Maîtrise des Drones : Bonus général aux jets de dés pour toutes les actions des drones (+1).",
                "",
                "Connexion Snaptique (utilisation des drône sans être immobile et concentré sur le pilotage), passif",
                "",
                "",
                "Coordination d'Assaut Dronisé : L'éclaireur peut coordonner une attaque simultanée de plusieurs drones, passif",
                "",
                "",
                "Analyse Prédictive du Drone : Le drone peut anticiper les mouvements ennemis grâce à l'analyse de données, le droniste peut voir la zone de déplacement de la cible",
                "",
                "",
                "",
                "Maître Droniste : L'éclaireur et ses drones deviennent une force de reconnaissance et de combat inégalée (+2 sur tous les jets du drone)."
            ],
            Droniste: {
                Equipements: [
                    "Drone Terrestre (Type Rouleur) : Robuste, idéal pour l'exploration de surface, se déplace en roulant (type R6) Prend 1 slot",
                    "Drone Araignée : Plus petit, articulé, idéal pour les conduits, l'escalade, le franchissement d'obstacles, déplacements possible sur les murs et le plafond. Prend 2 slots",
                    "Drone Volant : Agile, rapide, idéal pour l'exploration aérienne et le survol. Prend 3 slots",
                    "Drone Lourd : Plus grand, plus lent, mais avec un blindage conséquent et capable de porter des charges lourdes ou des armes puissantes. Utilise des chenilles pour se déplacer. Prend 4 slots"
                ],
                LevelEquipement: [
                    "1",
                    "8",
                    "13",
                    "18"
                ],
                Slots: [
                    "1",
                    "1",
                    "1",
                    "1",
                    "1",
                    "2",
                    "2",
                    "2",
                    "2",
                    "2",
                    "3",
                    "3",
                    "3",
                    "3",
                    "3",
                    "4",
                    "4",
                    "4",
                    "4",
                    "5"
                ]
            }
        }
    },
    /*Eclaireur Canin*/
    {
        Id: "Eclaireurcanin",
        Titre: "Éclaireur canin",
        Description: "Un éclaireur qui contrôle des chiens pôur explorer et s'attaquer aux différentes menaces.",
        CheminImage: " ./public/Images/CygnusProjects/Operateurs/Eclaireur Canin.png",
        Chemin: "/EclaireurCanin",
        Icone: "\u{1F415}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "6",
            Charisme: "12",
            Protection: "3",
            PointsVie: "15",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Eclaireur Canin.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Collier de communication : Permet de parler au chien à distance.",
                "Caméra Embarquée(Standard) : Permet de voir ce que voit le chien en temps réel.",
                "Protection Canine Renforcée : Armure plus solide, résiste mieux aux tirs légers.",
                "Augmentation Canine : Pattes renforcée(plus de rapiditées)",
                "Protection Canine Légère : Gilet pare - éclats ou armure souple, réduit les dégâts mineurs.",
                "Augmentation Canince : Capacitées oflactives accrues(entend, sent les choses plus loins)",
                "Augmentation Canine : Machoire renforcée(fait plus de dégâts)",
                "Vision Nocturne / Thermique(pour le chien) : Le chien peut \"voir\" dans l'obscurité ou détecter les signatures thermiques.",
                "Injecteur de stimulant : sur lui même ou sur un allier",
                "Système de Surcharge Sensorielle : Le chien peut émettre une impulsion lumineuse ou sonore désorientante pour les ennemis proches.",
                "Augmentation Canine : Dents modifiées pour injection de nano - bots(qui diminues les déplacements de la cible par 2 pendant 5 tours, utilisable une fois)",
                "Morsure traçante: permet de placer un traqueur dans la cible avec une mosure(pendant 3 tour une fois par chien).",
                "Module de Liaison Neuronale : Permet une communication télépathique simple avec le chien, améliorant la réactivité aux ordres.",
                "Bio - Analyseur: analyse une cible pour trouver ses points faibles(rester à 3 cases de la cible pendant 2 tours)",
                "Protection Canine Lourde / Blindage Léger : Augmente significativement la résistance aux dégâts, même contre des tirs modérés.",
                "Propulseurs d'Assaut (pour Mechagdog) : Permet au Mechagdog des bonds rapides ou des charges à haute vitesse.",
                "Lanceur de filet(pour Mechadog) : Permet de limiter les mouvements de la cible.",
                "Arme Létale Légère(pour Mechagdog) : Un petit laser ou lanceur de projectiles intégré, pour un soutien de tir limité.",
                "Pattes magnétiques : permet de marcher / courir sur les murs sur 20 cases maximum dans toute la partie",
                "Nanites de Réparation Rapide(pour Mechagdog) : Le Mechagdog peut auto - réparer ses dommages critiques rapidement."
            ],
            Capacites: [
                "",
                "Synergie au Combat : Le chien peut instinctivement couvrir ou assister l'éclaireur en mêlée.",
                "",
                "Communication Non-Verbale : L'éclaireur peut donner des ordres discrets par gestes.",
                "",
                "Pistage Avancé : Le chien peut suivre des pistes plus anciennes ou plus complexes.",
                "",
                "Diversion Canine : Le chien peut créer une diversion auditive ou visuelle pour attirer l'attention.",
                "",
                "Analyse Environnementale Canine : Le chien détecte et alerte des dangers environnementaux (gaz toxiques, radiations).",
                "",
                "Furtivité Coordonnée : L'éclaireur et ses chiens se déplacent plus discrètement en équipe.",
                "",
                "Rappel d'Urgence : Un chien peut être rappelé instantanément en sécurité, même hors de vue.",
                "",
                "Adaptation Environnementale Canine : Les chiens sont immunisés contre les effets de certains environnements extrêmes.",
                "",
                "Coordination d'Attaque Précise : Les chiens peuvent cibler les points faibles ennemis sur commande de l'éclaireur.",
                "",
                "Maître Canin Suprême : L'éclaireur et ses compagnons sont des unités de reconnaissance et de combat inégalées."
            ],
            Eclaireurcanin: {
                Equipements: [
                    "Un chien (Standard, 1 slot)",
                    "Horde Canine (chien frétile, petit chien qui fait peut de dégâts mais qui a une grande vitesse et peut de résistance, 0,5 slot)",
                    "Mechagdog (chien robot, vitesse moyenne, gros dégâts et grosse résistance, 1,5 slot)"
                ],
                LevelEquipement: [
                    "1",
                    "8",
                    "15"
                ],
                Slots: [
                    "1",
                    "1",
                    "1",
                    "1",
                    "1",
                    "1",
                    "2",
                    "2",
                    "2",
                    "2",
                    "2",
                    "2",
                    "2",
                    "3",
                    "3",
                    "3",
                    "3",
                    "3",
                    "3",
                    "4"
                ]
            }
        }
    },
    /*Eclaireur Cyber-Sensoriel*/
    {
        Id: "Eclaireurcybersensoriel",
        Titre: "Éclaireur cyber-sensoriel",
        Description: "Un éclaireur qui utilise des sens surdévelopper pour repérer les différentes menaces.",
        Chemin: "/EclaireurCyeberSensoriel",
        Icone: "\u{1F4E1}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "6",
            Charisme: "12",
            Protection: "3",
            PointsVie: "15",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Eclaireur Cyber-sensoriel.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "",
                "Implants Auditifs Améliorés : Écoute directionnelle, amplification des sons faibles.",
                "Implants Optiques Multi - Spectraux : Vision infrarouge(thermique) et ultraviolette.",
                "Capteurs Tactiles Avancés : Sensibilité accrue aux vibrations, à la chaleur, aux textures fines.",
                "Augmentations Musculaires Subtiles(Micro - Fibres)",
                "Système de Régulation Thermique Avancée",
                "Concentration Ciblée : Ignore les distractions sensorielles pour se concentrer sur une tâche.",
                "Capteurs Vibratoires Subterrains : Détection des mouvements et vibrations du sol ou des structures.",
                "Module d'Isolation Sensorielle : Capacité à bloquer volontairement certaines entrées sensorielles (bruit, lumière éblouissante).",
                "Interface Neurale de Données : Accès direct et téléchargement rapide de données depuis des terminaux.",
                "Amplificateurs de Réflexes Cérébelleux",
                "Système de Neutralisation des Douleurs Neuronales",
                "Module de Projection d'Imagerie Cérébrale : Peut projeter des schémas visuels internes (plans, données scannées) pour les alliés.",
                "Implants de Résistance aux Toxines / Pathogènes : Filtres sanguins et immunitaires cybernétiques.",
                "Implants de Régénération Cellulaire Accéléré",
                "Régénération Tissulaire Micro - Automatisée : Des nanites réparatrices intégrées qui accélèrent la guérison des blessures mineures.",
                "Implants de Surcharge Sensorielle Ciblée : Peut émettre une courte impulsion de données / fréquences qui désoriente une cible.",
                "Cœur / Poumons Cybernétiques Améliorés : Endurance physique et résilience aux environnements hostiles augmentées.",
                "Interface de Prédiction de Mouvement(Analyse des Micro - expressions) : Anticipe les actions des adversaires.",
                "Nexus Sensoriel Ultime : Fusion complète avec les réseaux de données, capacités sensorielles quasi - omniprésentes dans une zone."
            ],
            Capacites: [
                "",
                "Marqueur Olfactif Persistant : Peut \"fixer\" une odeur pour un suivi à long terme.",
                "",
                "Sismographe Corporel : Détecte les approches lourdes ou les tremblements lointains.",
                "",
                "Calme Cybernétique : Résistance accrue aux effets de peur, de confusion ou de douleur basés sur des stimuli externes.",
                "",
                "Écho de Confusion : Perturbe les sens d'un adversaire proche.",
                "",
                "Vision Prédictive : Bonus substantiel pour esquiver les attaques ou anticiper les pièges.",
                "",
                "Auto-Réparation Lente : Récupère progressivement des points de vie mineurs.",
                "",
                "Filtrage de Surcharge Sensorielle",
                "",
                "Projection de Silhouette Fantôme",
                "",
                "Intuition Cybernétique",
                "",
                "Maître de la Perception : Contrôle absolu sur son environnement sensoriel et celui de ses alliés proches."
            ]
        }
    },
    /*Capitaine Spatial*/
    {
        Id: "CapitaineSpatial",
        Titre: "Capitaine Spatial",
        Description: "Un capitaine qui pilote et commande des vaisseaux depuis décenies.",
        Chemin: "/CapitaineSpatiale",
        Icone: "\u{1F680}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "6",
            Sagesse: "12",
            Charisme: "12",
            Protection: "4",
            PointsVie: "12",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Capitaine Spatial.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Réparation d'Urgence : Capable d'effectuer des réparations sommaires sur les systèmes endommagés pour les maintenir en état de marche.",
                "Maniement Basique : Comprend les bases du pilotage, des manœuvres et du rôle de chaque membre d'équipage.",
                "Analyse de Boucliers : Maîtrise l'analyse des boucliers du vaisseau, détectant les faiblesses et les surcharges.",
                "Coordination d'Équipage : Peut donner des ordres clairs et précis à l'équipage pour une exécution efficace.",
                "Gestion des Systèmes de Combat : Comprend l'usage des systèmes de visée, des contre-mesures et des missiles.",
                "Réparation et Surcharge des Moteurs : Capable de pousser les moteurs à leurs limites et de les réparer en cas de surcharge.",
                "Tir de Barrage : Peut donner l'ordre de concentrer le feu sur un point précis de l'ennemi.",
                "Optimisation des Boucliers : Peut ajuster la fréquence et la charge des boucliers pour résister à un type d'arme spécifique.",
                "Manœuvre de Fuite : Peut ordonner une manœuvre rapide pour s'échapper d'une situation dangereuse.",
                "Maîtrise des Drones de Combat et de Réparation : Peut contrôler un essaim de drones de combat ou de réparation pour assister le vaisseau (drônes extérieurs, ils se déploient et effectuent leurs tâches à l'extérieur du vaisseau).",
                "Systèmes de Surcharge d'Armes : Capable de surcharger les armes pour augmenter leur puissance de feu et leur cadence de tir.",
                "Analyse des points faibles Structuraux : Peut analyser le vaisseau ennemi pour détecter ses faiblesses structurales.",
                "Gestion des Boucliers Interconnectés : Maîtrise la gestion de plusieurs boucliers et la manière dont ils s'interconnectent.",
                "Réparation Automatique Avancée : Peut programmer les systèmes de réparation du vaisseau pour qu'ils opèrent automatiquement.",
                "Tir Précis : Peut ordonner un tir de précision sur une faiblesse du vaisseau ennemi.",
                "Manœuvre de Feinte : Peut ordonner une manœuvre de feinte pour tromper l'ennemi et le faire tirer à côté.",
                "Manœuvre de Sabotage : Peut ordonner une manœuvre pour saboter les systèmes d'un vaisseau ennemi.",
                "",
                "",
                "Maître de la Technologie du Vaisseau : Maîtrise tous les systèmes du vaisseau et peut les manipuler à sa guise."
            ],
            Capacites: [
                "",
                "Tactique de Groupe (Passif, donne des bonus aux alliés proches, 5 cases)",
                "",
                "Ordre d'Énergie (Active) : Peut prioriser la distribution de l'énergie à un système de son choix pour un court instant.",
                "",
                "Diagnostic Rapide (Passif) : Le temps de diagnostic des pannes est réduit de moitié.",
                "",
                "Surcharge de Moteur (Active) : Le vaisseau peut temporairement accélérer, mais les moteurs saturent.",
                "",
                "Piège de Mine (Active) : Peut déployer un champ de mines extérieur pour piéger l'ennemi.",
                "",
                "Surcharge d'Armes (Active) : Les armes du vaisseau peuvent temporairement tirer plus vite et plus fort.",
                "",
                "Boucliers Intégrés (Active) : Les boucliers du vaisseau peuvent se relier pour une protection accrue.",
                "",
                "Réparation Automatique (Passif) : Les systèmes endommagés sont automatiquement réparés par le vaisseau.",
                "",
                "Maître Ingénieur (Passif) : L'efficacité de toutes les compétences d'ingénierie est accrue.",
                "",
                "Apogée du Capitaine (Active) : Peut pousser tous les systèmes du vaisseau à leurs limites, rendant le vaisseau temporairement invulnérable."
            ]
        }
    },
    /*Capitaine Des Forces Speciales*/
    {
        Id: "CapitaineDesForcesSpeciales",
        Titre: "Capitaine Des Forces Spéciales",
        Description: "Un capitaine qui dirige des soldats dans les pires environnements et contre les pires menaces.",
        Chemin: "/CapitaineDesForcesSpeciales",
        Icone: "\u{1F3AF}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "12",
            Intelligence: "6",
            Sagesse: "6",
            Charisme: "12",
            Protection: "6",
            PointsVie: "10",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Capitaine Force Speciale.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Esprit de Corps : Sait comment motiver son équipe et la faire travailler ensemble.",
                "Tir de Précision : Maîtrise le tir de précision avec la plupart des armes à feu.",
                "Maîtrise de la Mêlée : Peut se battre avec des armes de mêlée (couteaux, bâtons) avec une efficacité accrue.",
                "Maîtrise du Camouflage et de l'Infiltration : Comprend comment se camoufler et se déplacer discrètement sans être repéré.",
                "Nous récupérons les données... Veuillez patienter quelques secondes, puis réessayer de couper ou copier.",
                "Maîtrise du Poids et de l'Armure : Peut se battre avec une armure lourde ou légère sans perdre de mobilité.",
                "Démoralisation de l'Ennemi : Peut utiliser l'intimidation et la violence pour démoraliser l'ennemi (bonus pendant l'intimidation).",
                "Commandement Tactique : Peut donner des ordres tactiques à l'équipe, comme des feintes ou des embuscades (bonus lors de l'éxecution).",
                "Expert en Coordination : Maîtrise la coordination des actions de plusieurs équipes dans une bataille.",
                "Maîtrise des Arts Martiaux Avancés : Peut se battre avec des techniques avancées et des coups fatals.",
                "Influence de Groupe : Peut influencer le moral des alliés proches pour qu'ils ne paniquent pas.",
                "Défense de Groupe : Peut commander des actions défensives pour protéger ses alliés.",
                "Leadership Épique : Peut commander des actions d'assaut massives avec une efficacité accrue.",
                "Leadership Inébranlable : Sa présence rend l'équipe plus résistante à la peur, à la démoralisation et aux attaques psychologiques.",
                "Commandement de Sabotage : Peut commander une action de sabotage avec une efficacité accrue.",
                "",
                "Maîtrise des Aptitudes Médicales : Maîtrise les premiers secours et les soins médicaux de base.",
                "",
                "Maîtrise des Aptitudes de Sabotage : Maîtrise les aptitudes de sabotage et de destruction.",
                "Maîtrise Totale du Combat : Maîtrise toutes les formes de combat, du corps à corps à la guerre totale."
            ],
            Capacites: [
                "",
                "Ralliement (Active) : Peut rassurer ses alliés proches pour qu'ils ne paniquent pas.",
                "",
                "Marquage de Cible (Active) : Peut marquer une cible pour tous ses alliés (bonus pour attaque sur cette cible).",
                "",
                "Coopération (Passif) : L'efficacité des actions de l'équipe est améliorée.",
                "",
                "Guerrier (Passif) : Les attaques de mêlée du capitaine infligent des dégâts supplémentaires.",
                "",
                "Bannière de Combat (Active) : Peut inspirer ses alliés proches pour qu'ils se battent avec une force accrue.",
                "",
                "Médecin (Active) : Peut soigner un allié.",
                "",
                "Sabotage (Active) : Peut saboter un équipement ou une installation avec une efficacité accrue.",
                "",
                "Étoile Polaire (Passif): La réputation et la présence du Capitaine sont si imposantes qu'elles inspirent les alliés et démoralisent les ennemis. Les alliés ne peuvent plus être brisés par la peur ou le désespoir en sa présence.",
                "",
                "Fantôme Tactique (Active):  Le Capitaine peut coordonner l'équipe pour se déplacer avec une furtivité et une discrétion parfaites. ",
                "",
                "Assaut Final (Active): Le Capitaine donne l'ordre pour un assaut final. Il pousse son équipe à se battre avec une férocité et une détermination inégalées, transformant un combat désespéré en une victoire assurée."
            ]
        }
    },
    /*Artificier*/
    {
        Id: "Artificier",
        Titre: "Artificier",
        Description: "Un soldat qui manie les explosifs à la perfection.",
        CheminImage: " ./public/Images/CygnusProjects/Operateurs/Artificier.png",
        Chemin: "/Artificier",
        Icone: "\u{1F4A3}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "12",
            Intelligence: "6",
            Sagesse: "12",
            Charisme: "6",
            Protection: "6",
            PointsVie: "12",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Artificier.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Main Cybernétique avec Lanceur Intégré (lance les grenades plus loins)",
                "Main Cybernétique avec Lanceur Intégré",
                "Analyse de Résistance des Matériaux : Estime la puissance nécessaire.",
                "Augmentation Cérébrale(Calcul de Trajectoire) : Améliore la prédiction de lancer.",
                "Interface de Déclenchement Neuronale",
                "Identification des Points Faibles(Structures) : Repère les zones fragiles.",
                "Démolition Ciblée : Peut créer des brèches précises dans les murs.",
                "Préparation de Charge Rapide : Réduit le temps pour préparer une charge.",
                "Interface de Déclenchement Neuronale",
                "Utilisation Tactique des Grenades : Maîtrise les arcs de lancer.",
                "Réflexes Accrus pour les Détonations",
                "Absorption de l'Onde de Choc",
                "Système de Déploiement à Dépression",
                "Micro - Projecteur de Charges(projette des charges sur des courtes ou moyennes distances",
                "Dispensateur de Micro - Mines Adhésives",
                "Réacteur Musculaire Surchargeable(permet de lancer les grenade beaucoup plus loins et de lancer des charges)",
                "Camouflage de Pièges Basique : Rend les mines plus difficiles à repérer.",
                "Explosifs Magnétiques : Les grenades - charges peuvent se fixer sur toute surface métallique.",
                "Système de Contrôle de Détonation Temporel : Peut synchroniser des explosions pour des effets en chaîne.",
                "Implant d'Amplification d'Explosion"
            ],
            Capacites: [
                "",
                "Surcharge Structurelle : Les explosifs causent plus de dégâts aux structures.",
                "",
                "Connaissance des Risques Implicites",
                "",
                "Orchestration de Détonation Synchronisée",
                "",
                "Touche Finale : Déclenche des explosifs à distance avec précision mortelle.",
                "",
                "Résilience aux Souffles Explosifs (résistances aux ondes de chocs  / débris explosifs",
                "",
                "Optimisation des Effets de Zone",
                "",
                "Synthèse de Matière Explosive à la Volonté",
                "",
                "Chasseur de Pièges : Les mines se réorientent pour toucher les ennemis les plus menaçants.",
                "",
                "Champ de Mines Tactique : Peut rapidement miner une petite zone.",
                "",
                "Symphonie de la Destruction : Maîtrise les explosions multiples et synchronisées."
            ],
            Artificier: {
                Equipements: [
                    "Grenades à fragmentations",
                    "Grenades flash",
                    "Charges de démolitions légères (porte ou murs fins)",
                    "Grenades fumigènes",
                    "Grenades incendiaires",
                    "Grenade IEM",
                    "Mines de proximitées",
                    "Claymore",
                    "Charges de démolitions lourdes (murs en béton, murs épais)",
                    "Grenade à Singularité Quantique"
                ],
                LevelEquipement: [
                    "1",
                    "3",
                    "5",
                    "7",
                    "9",
                    "11",
                    "13",
                    "15",
                    "17",
                    "20"
                ],
                Slots: [
                    "2",
                    "2",
                    "2",
                    "4",
                    "4",
                    "4",
                    "5",
                    "5",
                    "5",
                    "6",
                    "6",
                    "6",
                    "7",
                    "7",
                    "7",
                    "8",
                    "8",
                    "8",
                    "9",
                    "10"
                ]
            }
        }
    },
    /*Berserker*/
    {
        Id: "Berserker",
        Titre: "Berserker",
        Description: "Un soldat qui préfère s'attaquer à ses adversaires au corps à corps.",
        CheminImage: " ./public/Images/CygnusProjects/Operateurs/Berserk.png",
        Chemin: "/Berserker",
        Icone: "\u{1FA93}",
        Details: {
            Force: "12",
            Dextérité: "6",
            Constitution: "12",
            Intelligence: "6",
            Sagesse: "6",
            Charisme: "12",
            Protection: "10",
            PointsVie: "10",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Berserker.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Endosquelette Renforcé (Léger) : Améliore la force et la résistance de base.",
                "Muscles Synthétiques Accélérés : Augmentent la vitesse de frappe et de réaction.",
                "Derme Sub - Dermal Renforcé : Réduit les dégâts des attaques contondantes / tranchantes.",
                "Injecteur de stimulants : boost les performances",
                "Articulation Cybergénique Améliorée : Augmente la souplesse et l'amplitude des mouvements.",
                "Système de Récupération Musculaire Accélérée : Réduit la fatigue en combat prolongé.",
                "Implants de Résistance à la Douleur Neuronale(Basique) : Atténue la douleur.",
                "Griffes / Lames Rétractables(mantis - blade) : Armes de mêlée naturelles intégrées.",
                "Réacteurs Musculaires Intégrés : Permettent des charges courtes et rapides.",
                "Implant de bouclier énergétique: implant dans l'avant bras qui déploit un bouclier énergétique (quand plus de PV il se recharge sur la durée)",
                "Système de Régénération Tissulaire(Accéléré) : Guérit plus vite les blessures légères.",
                "Squelette en Alliage Composite : Résistance aux chocs et aux fractures.",
                "Améliorations des Joints et Tendons(Hyper - Extensibles) : Sauts plus haut, course plus rapide.",
                "Système de Surcharge Musculaire Volontaire : Augmente la force brute ponctuellement.",
                "Implants Respiratoires / Circulatoires Optimisés : Endurance surhumaine.",
                "Implants de Surcharge Sensorielle(Tolérance) : Résiste mieux aux flashs / bruits.",
                "Système de Conversion d'Énergie Thermique (réduit le temps de récupération de certaines compétences)",
                "Cœur / Poumons Cybernétiques de Puissance : Force constante et régénération rapide.",
                "Armature Squelettique Intégrale Indestructible : Résistance extrême aux dégâts.",
                "Hyper - Adrénaline Synthétique Constante : Toujours en état de puissance maximale."
            ],
            Capacites: [
                "Rage Initiale (Active) : Augmente temporairement les dégâts CàC et la résistance.",
                "",
                "Cœur de Bataille (Passif) : Résistance accrue au stress et à la douleur mineure.",
                "",
                "Ténacité du Berserker (Passif) : Peut continuer à se battre malgré des blessures.",
                "",
                "Percée Rapide (Active) : Se jette sur un ennemi en ignorant les tirs de couverture (sur une cible à maximum 5 cases).",
                "",
                "Colosse (Passif) : Difficile à faire vaciller, résiste mieux aux poussées/prises.",
                "",
                "Bouclier de Rage (Active) : Réduit drastiquement les dégâts reçus pendant un court instant.",
                "",
                "Vague de Choc (Active) : Pousse/déséquilibre les ennemis proches par la force brute.",
                "",
                "Frappe Implacable (Active) : Ignore temporairement les défenses adverses( pendant 1 tour)",
                "",
                "Assaut Ininterrompu : Peut enchaîner les attaques sans malus",
                "",
                "",
                "Déchaînement Total (Active) : Devient invincible et inflige des dégâts massifs pendant un court instant."
            ]
        }
    },
    /*Commando Furtif*/
    {
        Id: "CommandoFurtif",
        Titre: "Commando Furtif",
        Description: "Un soldat capable de se camoufler dans tous les types d'environnement et de tous les types de mances.",
        Chemin: "/CommandoFurtif",
        Icone: "\u{1F441}",
        Details: {
            Force: "12",
            Dextérité: "12",
            Constitution: "12",
            Intelligence: "6",
            Sagesse: "6",
            Charisme: "6",
            Protection: "2",
            PointsVie: "20",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/CommandoFurtif.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Bottes Silencieuses Intégrées : Réduisent le bruit des pas.",
                "Gants à Surface Adhésive Réactive : Améliorent l'adhérence pour l'escalade légère.",
                "Vêtement à Tissage Acoustique : Absorbe les bruits corporels(tissu, frottements).",
                "Filtres Olfactifs Intégrés : Masquent l'odeur corporelle de l'opérateur.",
                "Implants de Camouflage Optique Passif : Légers changements de couleur / texture pour le mimétisme.",
                "Ouverture de Serrure Silencieuse : Peut crocheter ou pirater des serrures sans faire de bruit.",
                "Implants magnétiques et adhésifs(déplacements sur murs et plafonds)",
                "Revêtement Anti - Thermique Léger : Réduit la signature thermique du corps.",
                "Nettoyage de Scène Avancé : Peut effacer toutes les preuves biologiques d'un passage.",
                "Implants Auditifs de Substitution(Vision Sonore, a la dardevil)",
                "Peau Cybernétique à Camouflage Actif(Limité) : Peut s'adapter aux motifs et couleurs de l'environnement.",
                "Infiltration Spatiale : Accède à des zones très confinées ou difficiles d'accès.",
                "Générateur de Micro - Brouillage Sonore Actif(2 cases autour de lui, peut camoufler le bruits d'alliers)",
                "Implants de Flexibilité / Acoustique Optimisée : Permettent des mouvements de contorsion et des passages dans des espaces restreints sans bruit.",
                "Générateur de Micro - Champ de Déflexion Visuelle : Distord la lumière localement pour créer un flou autour de lui.",
                "Système d'Auto-Effacement de Données Temporaires : Efface activement sa présence des systèmes locaux en temps réel.",
                "Attaque / Défense Silencieuse Parfaite : Peut frapper ou parer sans aucun bruit résiduel.",
                "Esquive Prédictive Cybernétique : Anticipe et esquive les attaques avec une précision extrême.",
                "Fusion Furtive Ultime(Omni - Camouflage) : Son corps s'adapte à tous les spectres de détection (thermique, optique, IEM, sonore).",
                "Maître de la Non - Existence : Sa présence est presque impossible à détecter par tout moyen connu."
            ],
            Capacites: [
                "Maître de l'Ombre : Bonus passif aux jets de furtivité en milieu sombre.",
                "",
                "Déplacement Prudent : Peut se déplacer à vitesse normale en réduisant son bruit.",
                "",
                "Fantôme Olfactif : Indétectable par les chiens de traque basiques et la faune.",
                "",
                "Mort Silencieuse : Permet une élimination discrète et immédiate d'un ennemi.",
                "",
                "Invisible aux Ondes : Presque indétectable par les systèmes de détection électroniques avancés.",
                "",
                "Passage Inconnu : Peut se faufiler dans des ouvertures incroyablement petites sans faire de bruit.",
                "",
                "",
                "Mirage Personnel : Les capteurs visuels ennemis ont du mal à le verrouiller ou le suivre.",
                "",
                "Frappe Muette : Ses attaques sont inaudibles et sans résonance, même au contact.",
                "",
                "Mouvement Zéro : Peut effectuer des mouvements ou des actions rapides, semblant immobiles à l'ennemi.",
                "",
                "Le Vrai Fantôme : Totalement indétectable par tous les sens ou capteurs connus, sauf interaction directe."
            ]
        }
    },
    /*Medein De Campagne*/
    {
        Id: "MedecinDeCampagne",
        Titre: "Médecin De Campagne",
        Description: "Un médecin qui opère dans les pires zones de conflits sur les pires blessures.",
        CheminImage: " ./public/Images/CygnusProjects/Operateurs/Medecin Campagne.png",
        Chemin: "/MedecinDeCampagne",
        Icone: "\u{2695}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "12",
            Charisme: "6",
            Protection: "6",
            PointsVie: "15",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Medecin Campagne.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Premiers Secours de Base : Sait soigner les blessures légères, arrêter les saignements et stabiliser une victime.",
                "",
                "Antidotes et Vaccins : Est capable de créer des antidotes et des vaccins contre les poisons et les maladies courants.",
                "",
                "Réanimation de Combat : Peut réanimer un allié qui vient de mourir.",
                "",
                "Chirurgie d'Urgence : Peut opérer un allié sur le champ de bataille, sans avoir besoin d'une salle d'opération.",
                "",
                "",
                "Réparation de Membres : Peut réparer un membre brisé ou cassé avec un équipement de fortune.",
                "",
                "Médecine de Guerre Chimique : Peut utiliser des poisons ou des gaz pour neutraliser un ennemi.",
                "",
                "Maître de la Chirurgie de Guerre : Peut opérer n'importe qui, n'importe où, avec n'importe quel équipement.",
                "",
                "Médecine Régénérative : Peut régénérer des tissus et des organes endommagés pour guérir des blessures graves.",
                "",
                "",
                "Médecin de Guerre Ultime : Peut opérer et soigner n'importe qui, n'importe où, avec n'importe quel équipement, et avec une efficacité inégalée.",
                ""
            ],
            Capacites: [
                "",
                "Sérum d'Adrénaline (Active) : Peut injecter un allié pour le réveiller et lui donner un regain d'énergie temporaire (2 tours).",
                "",
                "Antidote Universel (Active) : Le médecin peut injecter un antidote à un allié pour le guérir d'un poison ou d'une maladie.",
                "",
                "Sauvetage Rapide (Active) : Le médecin peut réanimer un allié et lui redonner une petite santé.",
                "",
                "Esprit de Survie (Passif) : Le médecin a une force de volonté qui lui permet de résister à la douleur et aux blessures.",
                "",
                "Soins d'Urgence (Active) : Le médecin peut soigner un allié en un instant, lui rendant ses points de vie.",
                "",
                "Soutien de Groupe (Passif) : Le médecin peut soigner plusieurs alliés à la fois (2, divise par 2 les PV redonnés).",
                "",
                "Maître de la Chirurgie (Active) : Peut opérer un allié en un instant, lui rendant ses points de vie.",
                "",
                "Auto-Guérison (Passif) : Le médecin peut se soigner de manière automatique.",
                "",
                "Soutien de Groupe (Active) : Le médecin peut soigner plusieurs alliés à la fois (3, divise par 3 les PV redonnés).",
                "",
                "Ange de la Mort (Active) : Le médecin peut soigner tous les alliés et ressusciter les alliés morts."
            ]
        }
    },
    /*Nano Medecin*/
    {
        Id: "NanoMedecin",
        Titre: "Nano Médecin",
        Description: "Un médecin qui utilise des nano technologie pour opérer et soigner les blessés.",
        CheminImage: " ./public/Images/CygnusProjects/Operateurs/Nano Medecin.png",
        Chemin: "/NanoMedecin",
        Icone: "\u{1F493}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "12",
            Charisme: "6",
            Protection: "6",
            PointsVie: "15",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Nano Medecin.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Injection de Nanites de Soin : Peut injecter une faible dose de nanites pour soigner des blessures légères.",
                "Création de Stimulants : Peut créer des stimulants à partir de nanites pour augmenter temporairement la vitesse et la force d'un allié.",
                "Réparation Cellulaire Basique : Les nanites peuvent réparer les cellules et les tissus endommagés pour une guérison plus rapide.",
                "Réanimation Nanitique : Les nanites peuvent réanimer un allié qui vient de mourir et lui redonner la vie.",
                "Boost de Résistance : Les nanites peuvent renforcer le corps d'un allié, augmentant sa résistance aux dégâts physiques et psychologiques.",
                "Réparation de Membres : Peut réparer un membre brisé ou cassé avec des nanites.",
                "Boost de Force et de Vitesse : Les nanites peuvent stimuler les muscles d'un allié, augmentant sa force et sa vitesse.",
                "Médecine Expérimentale : Peut utiliser des nanites expérimentales pour guérir des maladies incurables ou des blessures graves (3 tours après injection de nanites, 1 tours de malus).",
                "Réanimation de Combat : Les nanites peuvent réanimer un allié et le protéger des dégâts.",
                "Chirurgie Nanitique Avancée : Les nanites peuvent opérer un allié pour le soigner et le guérir de ses blessures.",
                "Nano-Défense Active : Les nanites peuvent former un bouclier pour protéger un allié des dégâts.",
                "Réparation de Dégâts Graves : Les nanites peuvent réparer des dégâts graves, comme des os brisés ou des organes endommagés.",
                "Nano-Boost de Combat : Les nanites peuvent donner à un allié une force et une vitesse surhumaine pour le combat.",
                "Boost de Résistance aux Dégâts : Les nanites peuvent donner à un allié une résistance temporaire aux dégâts.",
                "Nano-Réanimation Ultime : Les nanites peuvent réanimer un allié qui vient de mourir et le protéger des dégâts.",
                "Boost de Combat : Les nanites peuvent donner à un allié une force et une vitesse surhumaine.",
                "Nano-Régénération : Les nanites peuvent régénérer des tissus et des organes endommagés pour guérir des blessures graves.",
                "Nano-Immunité : Les nanites peuvent rendre un allié immunisé contre les poisons et les maladies.",
                "",
                "Nano-Amélioration Ultime : Les nanites peuvent améliorer toutes les capacités d'un allié."
            ],
            Capacites: [
                "",
                "Guérison Rapide (Active) : Peut injecter un allié avec des nanites pour le soigner et lui rendre une partie de ses points de vie.",
                "",
                "Optimisation des Capacités (Active) : les nanites peuvent optimiser une des capacités d'un d'allié pendant 5 tours",
                "",
                "Nano-Protection (Active) : injecte des nanite à un allié qui lui donne un bouclier qui tank X dégâts",
                "",
                "Sérum d'Adrénaline (Active) : Le médecin peut injecter un allié pour lui donner un regain d'énergie temporaire.",
                "",
                "Soutien de Groupe (Passif) : Le médecin peut soigner plusieurs alliés à la fois.",
                "",
                "Soins d'Urgence (Active) : Le médecin peut soigner un allié en un instant.",
                "",
                "Maître des Nanites (Passif) : Les nanites du médecin sont plus puissantes et plus efficaces.",
                "",
                "Sérum de Combat (Active) : Le médecin peut injecter un allié pour lui donner une force et une vitesse surhumaine.",
                "",
                "Régénération (Passif) : Le médecin peut soigner un allié en un instant, lui rendant ses points de vie.",
                "",
                "Monarque des Nanites (Passif) : Le médecin peut manipuler les nanites à sa guise pour soigner, protéger et booster tous ses alliés."
            ]
        }
    },
    /*Technicien De l'Espace*/
    {
        Id: "TechnicienDeLespace",
        Titre: "Technicien De L'espace",
        Description: "Un technicien qui peut réparer tout ce qui lui passe sous la mains.",
        CheminImage: " ./public/Images/CygnusProjects/Operateurs/Technicien Espace.png",
        Chemin: "/TechnicienDeLespace",
        Icone: "\u{1F527}",
        Details: {
            Force: "12",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "6",
            Sagesse: "12",
            Charisme: "6",
            Protection: "8",
            PointsVie: "15",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Technicien Espace.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Réparation Basique : Peut réparer des dégâts mineurs et des dysfonctionnements simples sur des vaisseaux.",
                "",
                "",
                "Diagnostic de Panne : Peut identifier rapidement l'origine d'une panne ou d'un dysfonctionnement.",
                "",
                "",
                "Réparation de Moteurs : Peut réparer les moteurs de base d'un vaisseau.",
                "",
                "",
                "Maintenance de Systèmes de Communication : Peut réparer les systèmes de communication de base.",
                "",
                "",
                "Réparation de Systèmes de Vie : Peut réparer les systèmes de survie, les générateurs d'oxygène et les systèmes de température.",
                "",
                "",
                "Réparation de Systèmes de Propulsion Avancés : Peut réparer des moteurs de propulsion avancés.",
                "",
                "",
                "Maître de l'Espace : Peut réparer n'importe quel vaisseau.",
                ""
            ],
            Capacites: [
                "",
                "Réparation Rapide (Active) : Le technicien peut réparer un dysfonctionnement simple en un instant.",
                "",
                "Analyse de Système (Passif) : Le technicien peut évaluer l'état d'un système de vaisseau en un instant.",
                "",
                "Surcharge de Moteur (Active) : Le technicien peut surcharger le moteur d'un vaisseau pour qu'il soit plus rapide.",
                "",
                "Maître de la Réparation (Passif) : Le technicien est plus rapide pour réparer.",
                "",
                "Analyseur de Faiblesse (Passif) : Le technicien peut analyser un vaisseau ennemi et identifier ses points faibles, le rendant plus vulnérable aux attaques.",
                "",
                "Brouillage de Communication (Active) : Le technicien peut brouiller les communications ennemies, les rendant incapables de communiquer entre eux.",
                "",
                "Maintenance en Combat (Passif) : Le technicien peut effectuer des réparations mineures sur son propre équipement ou celui d'un allié à proximité.",
                "",
                "Câbles à Haute Tension (Active) : Le technicien peut déployer des câbles électrifiés qui peuvent piéger et étourdir les ennemis (branche un câble à un panneau electrique).",
                "",
                "Surcharge du Réacteur (Active) : Le technicien peut surcharger temporairement le réacteur d'un vaisseau pour augmenter massivement la puissance de tous les systèmes (boucliers, moteurs, armement), au risque de le faire surchauffer.",
                "",
                "Maître des Systèmes (Passif) : Le technicien peut réparer tous les systèmes de vaisseaux."
            ]
        }
    },
    /*Sentinelle De Defense*/
    {
        Id: "SentinelleDeDefense",
        Titre: "Sentinelle De Défense",
        Description: "Une sentinelle qui poste des défense pour empêcher le contournement des alliés par des menaces.",
        CheminImage: " ./public/Images/CygnusProjects/Operateurs/Sentinelle Defense.png",
        Chemin: "/SentinelleDeDefense",
        Icone: "\u{265C}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "12",
            Charisme: "6",
            Protection: "3",
            PointsVie: "20",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Sentinelle Defense.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Vision Standard.",
                "Module de Verrouillage de Cible Avancé",
                "Interface de Déclenchement à Distance",
                "Cœur du Rempart (Active) : Peut activer un mode de tir accru pour une tourelle.",
                "Module de Surcharge Énergétique (mines).",
                "Blindage Renforcé.",
                "Module de Vision Thermique.",
                "Détention de Zone (Active) : Déclenche simultanément plusieurs mines à effet de zone pour bloquer une avancée.",
                "Vecteur de Menace (Passif) : Les tourelles reçoivent un bonus de dégâts contre les cibles repérées par un drone.",
                "Système de Ciblage Avancé (tourelles multi-cibles).",
                "Module de Récupération Magnétique (tourelles).",
                "Système d'Identification Ami/Ennemi (mines).",
                "Module d'Amplification Optique (tourelles de précision).",
                "Module d'Auto-déploiement (mines).",
                "Système de Ciblage Prédictif",
                "Système d'Analyse des Faiblesses",
                "Module de Furtivité Active (mines).",
                "Kit de Mouvement Lévitationnel (la tourelle peut se déplacer de X cases maximum dans tout le scénario)",
                "Système de Défense Auto-Réparateur (Nanobots).",
                "IA de Coordination de Défense (arsenal)."
            ],
            Capacites: [
                "",
                "Déploiement Rapide (Passif) : Réduit le temps de mise en place des tourelles et mines.",
                "",
                "Champ de Perturbation (Passif) : Les mines ont un petit effet secondaire (lumière, bruit) à l'approche.",
                "",
                "Aura de Surveillance (Passif) : Détecte les ennemis entrant dans une petite zone autour d'une tourelle.",
                "",
                "Écran Aveuglant (Active) : La tourelle peut aveugler les ennemis pour les désorienter.",
                "",
                "Ami ou Ennemi (Passif) : Les mines et tourelles ne s'activent plus sur les alliés.",
                "",
                "Neutralisation Ciblée (Active) : La tourelle priorise et cible les ennemis désignés avec une précision mortelle.",
                "",
                "Ciel Verrouillé (Active) : Neutralise ou abat les menaces aériennes dans sa zone.",
                "",
                "Furtivité Mortelle (Passif) : Les mines ne sont détectables que par des scanners très spécialisés ou après activation.",
                "",
                "Persévérance du Gardien (Passif) : Les structures défensives regagnent des points de vie au fil du temps.",
                "",
                "Zone Inviolable (Active) : Les défenses déchaînent un barrage de feu et de pièges parfaitement coordonné."
            ],
            SentinelleDeDefense: {
                Equipements: [
                    "Tourelle Automatisée Légère : Faible cadence de tir. Prend 1 slot.",
                    "Mines de Proximité (Basiques) : Prend 0,5 slot.",
                    "Mine Incendiaire / Électromagnétique (Faible) : Prend 0,5 slot.",
                    "Tourelle Lourde : Mitrailleuse ou Projecteur à Plomb. Prend 2 slots.",
                    "Mines à Effet de Zone (Gaz Lacrymogène, Colle) : Prend 1 slot.",
                    "Tourelle Multi-Cible : Prend 2,5 slots.",
                    "Mine Intelligente (Ciblage Sélectif) : Prend 0,5 slot.",
                    "Tourelle de Précision (Sniper / Laser ciblé) : Prend 3 slots.",
                    "Mines Réactives Camouflées (Optique/Thermique) : Prend 0,5 slot.",
                    "Arsenal Défensif Intelligent (IA Avancée, adaptative peut faire tous les types de tourelles) : Prend 5 slots."
                ],
                LevelEquipement: [
                    "1",
                    "3",
                    "5",
                    "7",
                    "9",
                    "11",
                    "13",
                    "15",
                    "17",
                    "19"
                ],
                Slots: [
                    "1",
                    "1,5",
                    "2",
                    "2,5",
                    "3",
                    "3,5,",
                    "4",
                    "4,5",
                    "5",
                    "5,5",
                    "6",
                    "6,5",
                    "7",
                    "7,5",
                    "8",
                    "8,5",
                    "9",
                    "9,5",
                    "10",
                    "11"
                ]
            }
        }
    },
    /*Sentinelle De Controle d'Acces*/
    {
        Id: "SentinelleDeControleDacces",
        Titre: "Sentinelle De Contrôle D'accès",
        Description: "Une sentinelle qui bloque des zone et empêche le passage des menaces.",
        CheminImage: " ./public/Images/CygnusProjects/Operateurs/Sentinelle Controle Acces.png",
        Chemin: "/SentinelleDeControleDacces",
        Icone: "\u{1F512}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "12",
            Charisme: "6",
            Protection: "4",
            PointsVie: "18",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Sentinelle Controle Acces.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Illusion de Réalité (Active) : La Sentinelle utilise son réseau de caméras, de capteurs et de drones interconnectés pour générer des hologrammes, des signaux fantômes ou de fausses lectures de capteurs.",
                "",
                "Illusion de Réalité (Active) : La Sentinelle utilise son réseau de caméras, de capteurs et de drones interconnectés pour générer des hologrammes, des signaux fantômes ou de fausses lectures de capteurs.",
                "",
                "Plaques d'Absorption : Les plaques de la barricade absorbent les dégâts des balles et des explosions pour une durabilité accrue.",
                "",
                "",
                "Charge Énergétique : Le mur d'énergie peut générer une impulsion pour repousser les ennemis qui tentent de le traverser.",
                "",
                "Analyse de Réseau : Le verrou peut scanner le réseau de communication local pour ouvrir automatiquement aux alliés.",
                "Module de Refroidissement Actif (la barricade paraît comme un mur lambda thermiquement)",
                "",
                "",
                "Surcharge de Pression : Le mur de pression peut être surchargé pour projeter les ennemis.",
                "Mur de Lumière Multi-Focal (permet de berner plusieurs cibles à la fois max 2-3)",
                "Analyse d'ADN : Le verrou peut scanner la signature génétique des alliés pour un déverrouillage instantané.",
                "",
                "Adaptation au Terrain : Les modules de la barricade peuvent se connecter pour s'adapter au terrain (se cole parfaitement au mur, utilise les gravas).",
                "",
                ""
            ],
            Capacites: [
                "Aura de Surveillance (Passif) : Détecte les ennemis qui approchent dans une petite zone.",
                "Préparation Rapide (Passif) : Réduit le temps de mise en place des équipements.",
                "Impulsion Éblouissante (Active) : La barricade lumineuse émet un flash aveuglant à l'activation.",
                "Déclenchement Manuel (Active) : Peut déclencher un piège à distance par la pensée.",
                "Isolation (Active) : Peut verrouiller des portes à distance, coupant la route de l'ennemi.",
                "Inébranlable (Passif) : Ses barricades sont plus résistantes aux explosions.",
                "Marquage (Passif) : Les ennemis détectés par les capteurs sont marqués pour tous les alliés.",
                "Immunité d'Accès (Passif) : Les alliés peuvent traverser ses murs d'énergie sans encombre.",
                "Ralentissement de Champ (Active) : Peut ralentir les ennemis dans un champ de gravité pendant un court instant.",
                "Porte Ouverte (Passif) : Les portes qu'il verrouille avec son code s'ouvrent automatiquement pour les alliés.",
                "Persévérance du Gardien (Passif) : Ses barrières regagnent des points de vie au fil du temps.",
                "Arrêt Brutal (Active) : Peut déclencher une mine à colle à distance pour immobiliser un ennemi.",
                "Mirage de Zone (Active) : Le mur de lumière peut créer un mirage optique pour perturber l'ennemi.",
                "Repoussement (Active) : La barrière peut repousser un ennemi et le projeter sur une courte distance.",
                "Biométrie d'Accès (Passif) : Les alliés peuvent traverser ses verrouillages sans le moindre problème.",
                "Forteresse Immobile (Active) : Crée un bouclier de zone qui repousse toute attaque pendant un temps limité.",
                "Furtivité Mortelle (Passif) : Les mines ne sont détectables que par des scanners très spécialisés ou après activation.",
                "Forme et Fonction (Active) : Peut changer la forme d'une barricade déployée pour l'adapter au terrain.",
                "Inversion (Active) : Peut inverser la gravité sur une zone pour une courte durée, immobilisant les ennemis.",
                "Verrouillage Total (Active) : Toutes les défenses se déchaînent pour bloquer, immobiliser et repousser l'ennemi."
            ],
            SentinelleDeControleDacces: {
                Equipements: [
                    "Barricade de Déploiement Rapide : Barrière solide mais facile à briser.",
                    "Verrou de Porte Renforcé : Permet de verrouiller une porte, même électronique, la rendant très difficile à ouvrir.",
                    "Barricade de Blindage Lourd : Très solide, elle nécessite des explosifs ou des efforts colossaux pour être brisée.",
                    "Barricade Auto-Réparatrice : Repousse les dégâts mineurs grâce à des nanites de réparation intégrées.",
                    "Mur de Lumière Focalisé (Écran Optique) : Crée un mur de lumière qui brouille la vue des ennemis (comme dans mission impossible fait croire à un mur).",
                    "Générateur de Mur de Pression : Crée une barrière de pression qui peut repousser les ennemis qui tentent de la traverser.",
                    "Verrou Bio-Sécurisé : Se base sur le code ADN des alliés pour ouvrir des portes, rendant son verrouillage impossible à pirater.",
                    "Barricade Modulaire Auto-Déployable : Une barricade qui peut se déployer automatiquement en un instant et prendre différentes formes pour s'adapter à la zone (il faut juste placer le dispositif au sol et quand il y a du mouvement dans la zone il se déploit.",
                    "Arsenal de Contrôle d'Accès Intelligent (IA Avancée) : Les défenses collaborent via une IA centrale pour un contrôle d'accès total (s'intsalle sur l'ordinateur centrale du vaisseau et utilise le réseau de caméra encore fonctionnelles pour contrôler l'accès aux zones quand l'alien approche)."
                ],
                LevelEquipement: [
                    "1",
                    "3",
                    "5",
                    "7",
                    "9",
                    "12",
                    "15",
                    "18",
                    "20"
                ]
            }
        }
    },
    /*Sentinelle De Surveillance*/
    {
        Id: "SentinelleDeSurveillance",
        Titre: "Sentinelle De Surveillance",
        Description: "Une sentinelle qui pose des caméra et autre matériel de surveillance.",
        CheminImage: " ./public/Images/CygnusProjects/Operateurs/Sentinelle Surveillance.png",
        Chemin: "/SentinelleDeSurveillance",
        Icone: "\u{1F4BB}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "12",
            Charisme: "6",
            Protection: "4",
            PointsVie: "18",
            CheminImage: " ./public/Images/CygnusProjects/Operateurs/Sentinelle Surveillance.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Déclenchement Silencieux : Le piège s'active sans faire de bruit, ce qui permet de surprendre l'ennemi.",
                "Analyse Visuelle : Apprend à surveiller plusieurs caméras simultanément.",
                "Fil de Tension Camouflé : Le fil devient presque invisible, ce qui rend le piège plus difficile à repérer.",
                "Furtivité de la Détection : Maîtrise la détection discrète pour ne pas alerter l'ennemi.",
                "Caméra : vision nocturne",
                "Analyse Sonore : Apprend à distinguer les bruits de pas d'un allié de ceux d'un ennemi.",
                "Module de Camouflage Optique : Un revêtement qui permet à une caméra de se fondre dans son environnement, la rendant difficile à repérer.",
                "Surveillance de Nuit : Maîtrise la surveillance en milieu peu éclairé ou totalement sombre.",
                "Détection de Furtivité : Maîtrise la détection de cibles furtives ou camouflées.",
                "Caméra : vision thermique",
                "Système de Marquage Automatique : La caméra identifie automatiquement un ennemi et le marque sur le HUD de toute l'équipe.",
                "Module de Démarrage Rapide : Permet à un équipement d'être déployé en un instant, réduisant le temps de mise en place.",
                "Transmission de Données Directe : La caméra peut retransmettre en direct à tous les alliés les images qu'elle capte.",
                "Détection de Menace Avancée : L'IA de la caméra peut analyser les mouvements ennemis et prédire leur position future.",
                "Maîtrise de la Surveillance : Peut surveiller plusieurs caméras à la fois et les coordonner.",
                "Module de Camouflage Optique : Un revêtement qui permet à un détecteur de se fondre dans son environnement, la rendant difficile à repérer.",
                "Module d'immobilisation: profette une mousse qui se solidifie pour entraver les mouvements de la cible (se désagrège en 2 tours)",
                "Module de pistage: envoie une balise GPS sur la cible pour la tracer pendant 5 tours.",
                "Œil à Hologramme : L'œil peut créer un hologramme d'un allié pour tromper un ennemi.",
                "Œil de la Sentinelle : L'œil peut retransmettre en direct à tous les alliés les images qu'il capte, offrant une vision globale du champ de bataille pour toute l'équipe."
            ],
            Capacites: [
                "",
                "Transmission de Données (Passif) : Les caméras peuvent envoyer des images simples à la sentinelle quand quelque chose passe devant.",
                "",
                "Résilience (Passif) : La caméra est plus résistante aux dégâts.",
                "",
                "Piège (Active) : Le fil peut envoyer une impulsion electrique si un ennemi le traverse lui infligeant de très faibles dégâts et le ralentissant au prochain tour.",
                "",
                "Reconnaissance Faciale (Passif) : La caméra peut identifier les ennemis et les marquer.",
                "",
                "Zoom (Active) : La sentinelle peut zoomer sur une cible pour l'analyser.",
                "",
                "Vue Globale (Active) : Le capitaine peut retransmettre en direct à tous les alliés les images d'une caméra.",
                "",
                "Sonar d'Écho (Active) : peut utiliser une caméra comme sonar pour détecter les mouvement d'une zone autour d'elle",
                "",
                "Analyse de Menace (Passif):  L'IA des caméras de la sentinelle peut identifier les points faibles des véhicules ennemis ou les cibles prioritaires dans une foule, marquant automatiquement les menaces pour toute l'équipe.",
                "",
                "Redéploiement Éclair (Active): La sentinelle peut téléporter un de ses équipements (fil, caméra) à un autre endroit. L'objet se matérialise instantanément et sans bruit, permettant un changement de stratégie en plein combat.",
                "",
                "Illusion de Réalité (Active) : La Sentinelle utilise son réseau de caméras, de capteurs et de drones interconnectés pour générer des hologrammes, des signaux fantômes ou de fausses lectures de capteurs."
            ],
            SentinelleDeSurveillance: {
                Equipements: [
                    "Fil Détecteur de Mouvement : Détecte un passage et émet un signal sonore simple pour alerter.",
                    "Caméra de Surveillance Fixe : Une caméra standard qui peut être posée pour surveiller un angle.",
                    "Caméra Blindée : Une caméra plus robuste qui peut résister.",
                    "Fil Détecteur Silencieux : Détecte un passage mais envoie un signal silencieux à la sentinelle.",
                    "Caméra 360° : Une caméra qui peut filmer dans toutes les directions pour couvrir une zone entière.",
                    "Détecteur de Mouvement Sonore : Détecte les bruits de pas et d'armes pour alerter la sentinelle.",
                    "L'Œil de la Sentinelle: une caméra qui voit par tous les spectre possibles."
                ],
                LevelEquipement: [
                    "1",
                    "4",
                    "7",
                    "10",
                    "13",
                    "16",
                    "19"
                ]
            }
        }
    },
    /*Le Saboteur*/
    {
        Id: "LeSaboteur",
        Titre: "Le Saboteur",
        Description: "Un hacker qui se déplace en silence et qui détruit ou sabote tout le matériel ennemie.",
        Chemin: "/LeSaboteur",
        Icone: "\u{1F6AB}",
        Details: {
            Force: "6",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "12",
            Sagesse: "12",
            Charisme: "6",
            Protection: "6",
            PointsVie: "12",
            CheminImage: "./public/Images/CygnusProjects/Operateurs/Saboteur.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Dysfonctionnement Basique : Peut causer des dysfonctionnements mineurs sur des appareils électroniques simples.",
                "Brouillage de Signal : Peut brouiller les signaux radio et les communications simples.",
                "Coupure de Courant : Peut couper le courant dans un bâtiment ou une zone spécifique.",
                "Désactivation de Caméra : Peut désactiver des caméras de sécurité pour une courte période.",
                "Bombe IEM : Peut utiliser une bombe IEM qui désactive tous les systèmes électroniques dans une zone de 2 salles autour de la bombe (2 bombes max).",
                "Distraction Sonore : Peut créer une distraction sonore pour attirer les ennemis dans un piège (avec les hauts parleurs du vaisseau).",
                "Surcharge de Réseau : Peut surcharger un réseau pour le faire planter.",
                "Pirate de Réseau : Peut pirater un réseau pour le contrôler.",
                "Surcharge de Circuit : Peut surcharger un circuit électrique pour provoquer un court-circuit.",
                "Désactivation de Systèmes : Peut désactiver des systèmes de sécurité, comme des caméras ou des lasers.",
                "",
                "Coupure de Courant Ciblée : Capable de couper l'alimentation électrique d'un bâtiment ou d'une zone sans affecter les autres systèmes environnants.",
                "",
                "Inversion de Fonction : Est capable de reprogrammer un système pour qu'il ait un effet inverse, par exemple, faire en sorte qu'une porte sécurisée s'ouvre au lieu de se fermer.",
                "",
                "Surcharge de Réseau de Données : Peut surcharger un réseau de communication pour le faire planter, empêchant l'échange d'informations.",
                "",
                "Générateur de Fausse Alerte : Est capable de déclencher des alarmes ou des systèmes d'urgence pour provoquer la panique et créer une diversion.",
                "",
                "Détonation à Distance : Peut modifier une machine ou un appareil pour qu'il explose à distance, créant une diversion ou détruisant un obstacle."
            ],
            Capacites: [
                "",
                "Désactivation de Système (Active) : Le saboteur peut désactiver un système de sécurité.",
                "",
                "Mine Électronique (Active) : Le saboteur peut créer une mine électronique.",
                "",
                "Désactivation d'Armement (Active) : Le saboteur peut désactiver un système d'armement ennemi.",
                "",
                "Maître du Sabotage (Passif) : Le saboteur est plus rapide pour saboter.",
                "",
                "Déstabilisation de Masse (Active) : Le saboteur peut déstabiliser une zone entière.",
                "",
                "Maître de l'Ingénierie (Passif) : Le saboteur est plus rapide pour saboter.",
                "",
                "Amplificateur de Signal (Active)  : Le saboteur peut manipuler un signal radio pour qu'il soit si fort qu'il devienne une arme sonique, désorientant et étourdissant les ennemis à proximité.",
                "",
                "Piste d'Évasion (Active) : Le saboteur peut créer une piste d'évasion en manipulant les systèmes de sécurité pour qu'ils s'ouvrent ou se ferment à sa guise, le rendant plus difficile à poursuivre.",
                "",
                "",
                "Monarque du Chaos (Passif) : Le saboteur peut manipuler des systèmes.",
                ""
            ]
        }
    },
    /*LE SPECTRE*/
    {
        Id: "LeSpectre",
        Titre: "Le Spectre",
        Description: "Un hacker qui se déplace dans l'ombre et qui assassine les adversaires tout en pouvant s'en prendre à leurs installations.",
        Chemin: "/LeSpectre",
        Icone: "\u{1F47B}",
        Details: {
            Force: "12",
            Dextérité: "12",
            Constitution: "6",
            Intelligence: "6",
            Sagesse: "12",
            Charisme: "6",
            Protection: "0",
            PointsVie: "25",
            CheminImage: "./public/Images/CygnusProjects/Operateurs/Spectre.png",
            Niveaux: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
            Competences: [
                "Se faufiler dans l'ombre et utiliser des abris pour passer inaperçu.",
                "Maîtrise de l'escalade et des déplacements en hauteur.",
                "Se fondre dans une foule pour passer inaperçu, même en terrain ouvert.",
                "Établir un pont sécurisé pour le transfert de données à distance sans laisser de trace.",
                "Utiliser le bruit ambiant (machines, vent) pour couvrir ses mouvements.",
                "Déploiement de fumée tactique pour la dissimulation et l'évasion (grenade fumigène, grenade disparition ninja).",
                "Traverser des champs de capteurs sans déclencher d'alarme.",
                "Se déplacer dans des conduits de ventilation.",
                "Maîtrise du combat au couteau pour la neutralisation silencieuse.",
                "Décoder des fichiers cryptés avec des méthodes de force brute sophistiquées.",
                "Se déplacer à travers un réseau de lasers sans les toucher.",
                "Analyser des réseaux pour repérer les faiblesses et les vulnérabilités.",
                "Manipuler des données de localisation pour tromper les systèmes de suivi.",
                "Créer de fausses empreintes pour tromper les gardes.",
                "Décodage de données de capteurs pour prédire les mouvements des ennemis.",
                "Infiltrer des bases de données ultra-sécurisées sans déclencher d'alarme.",
                "Manipuler l'environnement pour créer un passage secret.",
                "Modifier des systèmes de sécurité pour les rendre inefficaces.",
                "Créer de fausses alertes pour provoquer la panique et créer une diversion.",
                "Créer un programme d'espionnage pour surveiller les ennemis."
            ],
            Capacites: [
                "",
                "Onde Silencieuse (Active) : Le Spectre peut créer une bulle qui absorbe les sons pendant un court instant.",
                "",
                "Détection de Piège (Passif) : Le Spectre peut détecter les pièges et les systèmes de sécurité cachés.",
                "",
                "Coup de Foudre (Active) : Le Spectre peut surcharger un appareil électronique pour le rendre inopérant.",
                "",
                "Invisibilité Optique (Active) : Le Spectre peut se rendre invisible pour une courte durée, en utilisant des champs de distorsion.",
                "",
                "Inspiration de Groupe (Passif) : La présence du Spectre inspire ses alliés, les rendant plus discrets et plus rapides.",
                "",
                "Détection de Faiblesse (Passif) : Le Spectre peut détecter les faiblesses des systèmes et des personnes.",
                "",
                "Piratage Ultime (Active) : Le Spectre peut pirater n'importe quel système et en prendre le contrôle.",
                "",
                "Sérum d'Adrénaline (Active) : Le Spectre peut s'injecter ou injecter à un allié un boost de vitesse et de force.",
                "",
                "Trompe-L'œil Sonique (Active) : : En utilisant un appareil spécialisé, le Spectre peut émettre un son d'impact (comme un coup de feu ou une explosion) à un autre endroit, créant une diversion parfaite.",
                "",
                "Monarque des Ombres (Passif) : Le Spectre est le maître des ombres, il ne peut être détecté et ses actions sont impossibles à anticiper."
            ]
        }
    }
];